MassTransit/MassTransit

doc/source/installation/index.rst

This is just correcting "were" to "where", that's all.

Typo fix in installation instructions page

---

src/MassTransit.sln
src/Persistence/MassTransit.EntityFrameworkIntegration.Tests/App.config
src/Persistence/MassTransit.EntityFrameworkIntegration.Tests/ContextSetup.cs
src/Persistence/MassTransit.EntityFrameworkIntegration.Tests/DbQuery.cs
src/Persistence/MassTransit.EntityFrameworkIntegration.Tests/MassTransit.EntityFrameworkIntegration.Tests.csproj
src/Persistence/MassTransit.EntityFrameworkIntegration.Tests/Properties/AssemblyInfo.cs
src/Persistence/MassTransit.EntityFrameworkIntegration.Tests/SagaDbContextFactoryProvider.cs
src/Persistence/MassTransit.EntityFrameworkIntegration.Tests/SagaLocator_Specs.cs
src/Persistence/MassTransit.EntityFrameworkIntegration.Tests/SimpleSagaEntity.cs
src/Persistence/MassTransit.EntityFrameworkIntegration.Tests/SimpleSagaMap.cs
src/Persistence/MassTransit.EntityFrameworkIntegration.Tests/packages.config
src/Persistence/MassTransit.EntityFrameworkIntegration.Tests/test.log4net.xml
src/Persistence/MassTransit.EntityFrameworkIntegration/MassTransit.EntityFrameworkIntegration.csproj
src/Persistence/MassTransit.EntityFrameworkIntegration/Properties/AssemblyInfo.cs
src/Persistence/MassTransit.EntityFrameworkIntegration/Saga/EfSagaConsumeContext.cs
src/Persistence/MassTransit.EntityFrameworkIntegration/Saga/EfSagaRepository.cs
src/Persistence/MassTransit.EntityFrameworkIntegration/SagaClassMapping.cs
src/Persistence/MassTransit.EntityFrameworkIntegration/SagaDbContext.cs
src/Persistence/MassTransit.EntityFrameworkIntegration/SagaEntity.cs
src/Persistence/MassTransit.EntityFrameworkIntegration/packages.config

Hello, I've added support for Entity Framework, and structured it similar to the NHibernate. The same unit tests that MassTransit.NHibernateIntegration.Tests were implemented for EntityFramework and passed.
I added some comments to the commits to help explain some decisions that were made.
Also one library you'll notice that I used was Mehdime.Entity. I've used it before in production code and it has worked great.
If you look at the `EfSagaRepository.cs` for example, you'll notice that EF doesn't have the NHibernate SessionFactory.
Instead you'll see:
```csharp
using (var dbContextScope = _dbContextScopeFactory.Create())
```
Basically it lets you get the benefits of a scoped connection (doesn't create a new db connection if called within a parent scope), similar to NHibernate …

Added persistence support for Sagas in Entity Framework

---

src/Containers/MassTransit.AutoFacIntegration/MassTransit.AutoFacIntegration.csproj
src/Containers/MassTransit.AutoFacIntegration/RegistrationExtensions.cs
src/Containers/MassTransit.Containers.Tests/AutofacRegistrationExtension_Specs.cs
src/Containers/MassTransit.Containers.Tests/MassTransit.Containers.Tests.csproj

Simple extension method for registration scanning of the marker interface IConsumer

Added autofac registration extension method for registering all consumers found through scanning assemblies/

---

src/Loggers/MassTransit.NLogIntegration/Logging/NLogLogger.cs

Fixes MassTransit#352
I have tested this change and it has resolve the issue.

Fix NullReferenceException when using the NLogLogger default constructor

---

src/MassTransit.Tests/BinarySerializer_Specs.cs
src/MassTransit.Tests/MassTransit.Tests.csproj
src/MassTransit/Events/FaultEvent.cs
src/MassTransit/Events/FaultExceptionInfo.cs
src/MassTransit/Serialization/StaticConsumeContext.cs

* The `ConsumeContext.NotifyFaulted` implementation in `StaticConsumeContext` was calling `GenerateFault` passing the context instance instead of the message. Since `GeneratingFault` is a generic method no error was reported by the compiler. Instead a serialization exception was thrown at run-time.
* The `FaultEvent` and `FaultExceptionInfo` need to be serializable to work when the bus is configured to use binary serialization. Since interfaces are used (`IFault` and `ExceptionInfo`) in the surface API model, this probably need some additional analysis because it impose additional implicit requirements on alternative implementations (they need to be serializable).

Fixed binary serialization issues when dealing with faults

---

src/MassTransit.QuartzIntegration.Tests/Recurring_Specs.cs
src/MassTransit.QuartzIntegration/CancelScheduledMessageConsumer.cs

This is so that you can cancel a recurring schedule with the schedule id you used to create the recurring schedule.  
If someone had used a work around where they prepended the schedule id with "Recurring.Trigger." it will still work as I checked for that scenario before prepending in the consumer.
I added a test to confirm that it works also.

Fixing cancelled recurring schedules

---

src/MassTransit.RabbitMqTransport.Tests/HostConfigurator_Specs.cs
src/MassTransit.RabbitMqTransport/Configuration/Configurators/ConfigurationHostSettings.cs
src/MassTransit.RabbitMqTransport/Configuration/Configurators/IRabbitMqSslConfigurator.cs
src/MassTransit.RabbitMqTransport/Configuration/Configurators/RabbitMqHostConfigurator.cs
src/MassTransit.RabbitMqTransport/Configuration/Configurators/RabbitMqSslConfigurator.cs
src/MassTransit.RabbitMqTransport/Hosting/RabbitMqHostBusFactory.cs
src/MassTransit.RabbitMqTransport/RabbitMqAddressExtensions.cs
src/MassTransit.RabbitMqTransport/RabbitMqHostSettings.cs

Follow up to #458
This change removes the need to specify a username and password as part of the set-up of RabbitMQ configuration, instead the SSL client certificate can be used (if RabbitMQ has been configured to allow it).  Having this in place means that no username or passwords need to be stored in the app's configuration file.
Sample usage:
```c#
IBusControl bus = MassTransit.Bus.Factory.CreateUsingRabbitMq(x =>
{
IRabbitMqHost host = x.Host(_hostAddress, h =>
{
h.UseSsl(ssl =>
{
ssl.Certificate = LoadCertificate(); //read from some location such as Windows cert store
ssl.UseCertificateAsAuthenticationIdentity = true;  //<-- new configuration option here
});
});
}
```
Note that this provides an either/or authentication scenario - a client system may use username and password **or** a …

Allow SSL client certificate to use used as login identity

---

src/MassTransit.AzureServiceBusTransport/Configuration/AzureServiceBusHostConfigurator.cs
src/MassTransit.AzureServiceBusTransport/Hosting/ServiceBusAmqpTransportSettings.cs
src/MassTransit.AzureServiceBusTransport/Hosting/ServiceBusNetMessagingTransportSettings.cs
src/MassTransit.AzureServiceBusTransport/IServiceBusHostConfigurator.cs
src/MassTransit.AzureServiceBusTransport/ServiceBusHost.cs

Left the batch intervals as the transport setting defaults, and added links to more information for tuning the Azure SB client. Also the ServiceBusHost wasnt using settings provided by the configurator interface when CreateNetMessagingFactory() was called to create the Session Messaging Factory.

Azure sb default batch interval

---

doc/source/configuration/bus_configuration.rst
doc/source/configuration/gotchas.rst
doc/source/middleware/circuit_breaker.rst
doc/source/middleware/custom.rst
doc/source/middleware/rate_limiter.rst
doc/source/overview/publishing.rst
doc/source/usage/messages.rst

- Add an example of configuring an Azure Service Bus
- Fix typos and passive voice in docs

Fix typos in docs and add Azure Service Bus configuration example

---

README.md

Hope this small clarification is helpful.

Specify that .net 4.5.2 is required to install MassTransit package.

---

src/.nuget/NuGet.targets
src/MassTransit.Reactive.Tests/MassTransit.Reactive.Tests.csproj
src/MassTransit.Reactive.Tests/packages.config
src/MassTransit.Reactive/MassTransit.Reactive.csproj
src/MassTransit.Reactive/packages.config

This commit resolves #607 
I had to change NuGet.exe download URL to latest version, since new rx packages
cannot be installed with the old one.
Existing URL [https://nuget.org/nuget.exe] points to 2.8 but rx 3.0 requires >=2.12. 
Also, not sure if this dependency update is a as breaking change or not, since new assemblies have new strong key.

Updated Reactive Extensions references to 3.0.

---

src/MassTransit.QuartzIntegration/ScheduleMessageConsumer.cs

You have this rescheduling logic for recurring jobs, but not for single jobs. We have a situation where we have single jobs that can be retried manually. The correlation id happens to be the same and if we want to happen to redeliver again, an exception gets thrown by Quartz because the job already exists. I didn't see any harm in making both job types function the same.

Checking job exists so exception doesn't get thrown

---

src/MassTransit.AzureServiceBusTransport/Transport/ServiceBusSendEndpointProvider.cs

Simple fix - The SendObjecver was not connected (did the same logic as in the rabbitMQ transport

SendObserver is not called using Azure Service Bus Transport #782

---

src/MassTransit.RabbitMqTransport/Topology/RabbitMqExchangeBindingExtensions.cs

Currently we cannot make custom bindings with a routing key other then "".
This pull request lets the custom bindings actually use the routing key that is set in the callback given to Bind().

Let RabbitMqReceiveEndpointSpecification.Bind() actually use the specified RoutingKey to create the RabbitMq bindings

---

docs/learn/README.md

Update README.md 

---

src/MassTransit/Transports/ReceiveEndpointLoggingExtensions.cs

Change ReceivedEndpointLoggingExtensions to log passing the exception along instead of formating inside text string. This is related to issue #871

Change ReceivedEndpointLoggingExtensions to log passing the exception along

---

docs/advanced/sagas/persistence.md

Some more work is required to split the concurrency section from Entity Framework, since it is generic. Will try to fix it later.

Fixing the EF section in saga persistence

---

src/MassTransit.RabbitMqTransport/Transport/RabbitMqSendTransport.cs

Fix for issue #884 
When using RabbitMQ the custom serializer ran only when requesting the context.Body, so the custom transport headers were not populated in time. The Azure service bus implementation worked because the body stream was requested before populating the header collection.

Fix when on RabbitMQ transport headers missing (Issue #884)

---

src/Containers/MassTransit.Containers.Tests/AutofacStateMachineSaga_Specs.cs
src/MassTransit.AutomatonymousIntegration/MassTransitStateMachine.cs
src/MassTransit.AzureServiceBusTransport/Configuration/ServiceBusTopicSubscriptionExtensions.cs
src/MassTransit.HttpTransport/Clients/HttpSendTransport.cs
src/MassTransit.RabbitMqTransport/Topology/RabbitMqExchangeBindingExtensions.cs
src/MassTransit.RabbitMqTransport/Topology/RabbitMqTopology.cs
src/MassTransit.Tests/Conventional/CustomConsumerMessageConvention.cs
src/MassTransit/Configuration/ConsumeConnectors/AsyncConsumerMessageConvention.cs
src/MassTransit/Configuration/ConsumeConnectors/LegacyConsumerMessageConvention.cs
src/MassTransit/MessageUrn.cs
src/MassTransit/Saga/SagaMetadataCache.cs
src/MassTransit/Scheduling/DefaultRecurringSchedule.cs
src/MassTransit/Serialization/BinaryMessageSerializer.cs
src/MassTransit/Serialization/JsonConverters/ListJsonConverter.cs
src/MassTransit/Transports/DefaultMessageNameFormatter.cs
src/MassTransit/Util/BusHostInfo.cs
src/MassTransit/Util/Scanning/AssemblyScanner.cs
src/MassTransit/Util/TypeMetadataCache.cs
src/Persistence/MassTransit.MongoDbIntegration/MassTransitMongoDbConventions.cs

New code in MT repo uses the `TypeInfo` to get type information. Microsoft API compatibility checker advises to use that type as well. So I changed all suggested calls to use `TypeInfo` instead of `Type`.

Changing System.Type calls to use TypeInfo

---

src/Containers/MassTransit.SimpleInjectorIntegration/MassTransit.SimpleInjectorIntegration.csproj
src/MassTransit.Reactive/MassTransit.Reactive.csproj
src/MassTransit.TestFramework/IntentionalTestException.cs
src/MassTransit.TestFramework/MassTransit.TestFramework.csproj
src/MassTransit.TestFramework/SerializerCache.cs
src/MassTransit.TestFramework/TestConsumeContext.cs
src/MassTransit.TestFramework/TestSymmetricKeyProvider.cs

These changes add support for .net standard 1.6 to following projects, as discussed in #909 
- MassTransit.SimpleInjectorIntegration
- MassTransit.Reactive
- MassTransit.TestFramework
Test project for reactive MassTransit.Reactive.Tests can also be easily ported, but that requires 
[referencing NUnit3TestAdapter version 3.8](http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/), which is still in alpha state.

.net standard support to SimpleInjector, Reactive, TestFramework

---

src/Containers/MassTransit.WindsorIntegration/WindsorContainerExtensions.cs

If Castle Windsor component(consumer) is registed like: 
```c#
Component.For<IService>().ImplementedBy<ServiceImpl>();
```
The integration doesn't work as expected because the valid registration
```c#
Component.For<ServiceImpl>().ImplementedBy<ServiceImpl>();
```

Castle Windsor service must be selected instead of implementation

---

src/MassTransit.RabbitMqTransport.Tests/MassTransit.RabbitMqTransport.Tests.csproj
src/MassTransit.Tests/CachingTests/TestException.cs
src/MassTransit.Tests/Configuration/SendSpecification_Specs.cs
src/MassTransit.Tests/ContextSetup.cs
src/MassTransit.Tests/Courier/EncryptedArgument_Specs.cs
src/MassTransit.Tests/HostInfo_Specs.cs
src/MassTransit.Tests/MassTransit.Tests.csproj
src/MassTransit.Tests/MessageData/DataBus_Specs.cs
src/MassTransit.Tests/MessageData/FileSystem_Specs.cs
src/MassTransit.Tests/Retry_Specs.cs
src/MassTransit.Tests/Saga/RegisterUserController.cs
src/MassTransit.Tests/Saga/RegisterUser_Specs.cs
src/MassTransit.Tests/Serialization/Interface_Specs.cs
src/MassTransit.Tests/Serialization/JsonSerialization_Specs.cs
src/MassTransit.Tests/Serialization/ReceiveFault_Serialization_Specs.cs
src/MassTransit.Tests/Serialization/SeparateSerializer_Specs.cs
src/MassTransit.Tests/Serialization/SerializationTest.cs
src/MassTransit.Tests/SerializationFault_Specs.cs
src/MassTransit/NetCore.cs

In order to test libraries built for .net standard, new tests profiles were added targeting .net core.
I had to explicitly target .net core version 1.1.1, otherwise build log was full of system.runtime version mismatch warning.

migrate masstransit.tests and rabbitmq.tests to .net core

---

src/Containers/MassTransit.Containers.Tests/AutofacRegistrationExtension_Specs.cs
src/Containers/MassTransit.Containers.Tests/MassTransit.Containers.Tests.csproj
src/Containers/MassTransit.Containers.Tests/Unity_Specs.cs
src/Containers/MassTransit.WindsorIntegration/MassTransit.WindsorIntegration.csproj
src/MassTransit.Reactive.Tests/MassTransit.Reactive.Tests.csproj
src/Persistence/MassTransit.DocumentDbIntegration.Tests/MassTransit.DocumentDbIntegration.Tests.csproj
src/Persistence/MassTransit.EntityFrameworkCoreIntegration.Tests/AuditContextFactory.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration.Tests/AuditStore_Specs.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration.Tests/ContextFactory.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration.Tests/MassTransit.EntityFrameworkCoreIntegration.Tests.csproj
src/Persistence/MassTransit.MartenIntegration.Tests/MassTransit.MartenIntegration.Tests.csproj
src/Persistence/MassTransit.MongoDbIntegration.Tests/MassTransit.MongoDbIntegration.Tests.csproj

This pr continues .net core/.net standard migration as discussed in #909 
- it adds .net standard support to castle windsor integration
- .net core tests suppport to containers tests (except for unsupported containers), ef core, marten, mongo db, rx. All tests pass.

add .net core test profiles to more projects according to issue #909

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

I modified the create-react-app ones to suite our needs, would be good to have a new these template to aid how people file issues. 
Would reduce ~aggressive~ comments like these. https://github.com/MassTransit/MassTransit/issues/957#issuecomment-320874708
Having an issue templated makes it clear what we expect to see in an issue, and how we priorities these issue, and where to post questions.

Created github issue and pull request template.

---

src/MassTransit/MassTransit.csproj
src/MassTransit/RespondAsyncExecuteExtensions.cs

Obviously the callback extensions for `RespondAsync` do not exist. This should fix it. Not sure about the file/class name though.

Adding callbacks to RespondAsync

---

build.fsx
src/Directory.Build.props

Pass version arguments to dotnet restore in fake, so that internal NuGet package references are correct

Pass version arguments to dotnet restore in fake

---

src/Persistence/MassTransit.MartenIntegration/MartenSagaRepository.cs

Since Marten 2 returns `IReadOnlyList` and not `IList`, `IList` has been changed to just `var` so it will work in Marten 1 and 2.

Support for Marten 2

---

src/Persistence/MassTransit.MartenIntegration/MartenSagaRepository.cs

`var` does not change the type! By using `IEnumerable` we establish compatibility with both versions of Marten.

Fixes #973

---

src/MassTransit.QuartzIntegration/QuartzIntegrationExtensions.cs

Now when using in-memory scheduler, which runs on a real transport, the queue name is defaulted to `quartz`, which makes this feature unusable when multiple services run on the same RMQ. It would be great to allow specifying the queue name. The default will be the same.

Make it possible to specify scheduling queue name

---

src/MassTransit.RabbitMqTransport/Exceptions/MessageNotConfirmedException.cs
src/MassTransit.RabbitMqTransport/Exceptions/PublishNackException.cs
src/MassTransit.RabbitMqTransport/Exceptions/PublishReturnedException.cs
src/MassTransit.RabbitMqTransport/Exceptions/RabbitMqConnectionException.cs
src/MassTransit.Tests/ContextSetup.cs
src/MassTransit.Tests/MassTransit.Tests.csproj
src/MassTransit.Tests/MessageData/DataBus_Specs.cs
src/MassTransit/Exceptions/CommandException.cs
src/MassTransit/MassTransit.csproj
src/MassTransit/Util/BusHostInfo.cs
src/MassTransit/Util/LimitedConcurrencyLevelTaskScheduler.cs
src/MassTransit/Util/Scanning/AssemblyScanner.cs

This adds .net standard 2.0 build target to core masstransit lib and .net core 2.0 profile for tests for tests. 
It doesn't remove .net standard 1.6, since other projects depend on it.

Add support for .net standard 2.0 for core lib

---

src/MassTransit/Pipeline/Filters/ConsumeContextRetryPolicyContext.cs

I fixed an oversight in logging

Do not log R-RETRY when not going to retry

---

src/Persistence/MassTransit.MartenIntegration.Tests/Messages.cs
src/Persistence/MassTransit.MartenIntegration.Tests/SagaPersistenceTests.cs
src/Persistence/MassTransit.MartenIntegration.Tests/SimpleSaga.cs
src/Persistence/MassTransit.MartenIntegration/MartenSagaRepository.cs

Fixes #1016 
I verified the fix by first adding a new test that uses observed messages, rather than orchestrated messages. That test failed, as expected since it can't find the saga instance with the Observed property to true since the state isn't being changed in the database. I then changed the MartenSagaRepository to use a dirty tracked session for the SendQuery path as well, which made the test turn green. Existing tests were unmodified and are still green.

Fix an issue where Saga instance wasn't being saved properly

---

src/Containers/MassTransit.Containers.Tests/MassTransit.Containers.Tests.csproj
src/Containers/MassTransit.Containers.Tests/Unity_Specs.cs
src/Containers/MassTransit.NinjectIntegration/MassTransit.NinjectIntegration.csproj
src/Containers/MassTransit.UnityIntegration/MassTransit.UnityIntegration.csproj
src/Containers/MassTransit.UnityIntegration/UnityCompensateActivityScopeProvider.cs
src/Containers/MassTransit.UnityIntegration/UnityConsumerFactory.cs
src/Containers/MassTransit.UnityIntegration/UnityConsumerScopeProvider.cs
src/Containers/MassTransit.UnityIntegration/UnityExecuteActivityScopeProvider.cs
src/Containers/MassTransit.UnityIntegration/UnityExtensions.cs
src/Containers/MassTransit.UnityIntegration/UnitySagaRepository.cs
src/Containers/MassTransit.UnityIntegration/UnitySagaRepositoryFactory.cs
src/Containers/MassTransit.UnityIntegration/UnitySagaScopeProvider.cs

This pr updates Ninject and Unity libraries to versions that support .Net Standard.

NInject and Unity .net standard support

---

src/MassTransit/MessageHeaders.cs
src/MassTransit/Pipeline/Filters/MoveExceptionToTransportFilter.cs

The type of thrown exception flows to the consumers in message header **MT-Fault-ExceptionType**. It is simple addition, not verified anyhow.

#1048 Exception type added to the message headers

---

src/MassTransit.AutomatonymousIntegration.Tests/MassTransit.AutomatonymousIntegration.Tests.csproj
src/MassTransit.AutomatonymousIntegration.Tests/SingleConnectionSessionFactory.cs
src/MassTransit.AutomatonymousIntegration.Tests/SqlLiteSessionFactoryProvider.cs
src/MassTransit.Futures.Tests/MassTransit.Futures.Tests.csproj
src/Persistence/MassTransit.NHibernateIntegration.Tests/DbQuery.cs
src/Persistence/MassTransit.NHibernateIntegration.Tests/MassTransit.NHibernateIntegration.Tests.csproj
src/Persistence/MassTransit.NHibernateIntegration.Tests/SingleConnectionSessionFactory.cs
src/Persistence/MassTransit.NHibernateIntegration.Tests/SqlLiteSessionFactoryProvider.cs
src/Persistence/MassTransit.NHibernateIntegration/BinaryGuidType.cs
src/Persistence/MassTransit.NHibernateIntegration/MassTransit.NHibernateIntegration.csproj
src/Persistence/MassTransit.NHibernateIntegration/Saga/NHibernateSagaConsumeContext.cs
src/Persistence/MassTransit.NHibernateIntegration/Saga/NHibernateSagaRepository.cs
src/Persistence/MassTransit.NHibernateIntegration/UriUserType.cs

Due to NH version limitations, 4.5.2 is not supported. 4.6.1 and .NET Standard 2.0 are there.
All sync db calls are replaced to async.

Updating to NHibernate 5.1

---

src/Persistence/MassTransit.RedisIntegration/RedisSagaRepository.cs

Solving of problem with concurrency write.
Mistake in line 133 leads to dirty data write.
Using of locking mechanism in Redis prevents dirty data write.
I have tested the code on production environment (docker mono) and didn't  find  any  performance issue.

Beter solution for concurency write in RedisSagaRepository.

---

appveyor.yml
src/MassTransit.AutomatonymousIntegration.Tests/MassTransit.AutomatonymousIntegration.Tests.csproj
src/MassTransit.AutomatonymousIntegration.Tests/SqlLiteSessionFactoryProvider.cs
src/Persistence/MassTransit.NHibernateIntegration.Tests/MassTransit.NHibernateIntegration.Tests.csproj
src/Persistence/MassTransit.NHibernateIntegration.Tests/NHibernateSessionFactoryProvider.cs
src/Persistence/MassTransit.NHibernateIntegration.Tests/SagaLocator_Specs.cs
src/Persistence/MassTransit.NHibernateIntegration.Tests/SqlLiteSessionFactoryProvider.cs

Fixing SQLite tests for NHibernate
Adding NHibernate integration tests to the build
Tests that involve the RequestClient fail but this does not seem to be related to the persistence.
`Should_publish_the_event_of_the_missing_instance` fails because the `status.Status` is `Cancelled`.

Fixing SQLite tests for NHibernate

---

src/MassTransit.AzureServiceBusTransport/Transport/Receiver.cs

Example log via NLog
```
DEBUG|MassTransit.AzureServiceBusTransport.Transport.Receiver|Receiving {0}:{1}({3})|
```
Corrected log via NLog
```
DEBUG|MassTransit.AzureServiceBusTransport.Transport.Receiver|Receiving 8:650f00005d6e0015d69308d5b1bd2193 - MY.PROJECT.HERE|
```
Happy to write unit test but can't see any good examples given the dependencies.

Logging format fix.

---

src/MassTransit/BusControlExtensions.cs

There is no `Start` extension method for `BusControl` that accept timeout parameter unlike `Stop` method.
I add `Start` method overload.
void Start(IBusControl, TimeSpan)

new start extension method is added

---

src/MassTransit.ActiveMqTransport/ActiveMqBusFactory.cs
src/MassTransit.ActiveMqTransport/ActiveMqHostSettings.cs
src/MassTransit.ActiveMqTransport/Configuration/ActiveMqHostConfigurationExtensions.cs
src/MassTransit.ActiveMqTransport/Configuration/BusFactoryConfiguratorExtensions.cs
src/MassTransit.ActiveMqTransport/Configuration/IActiveMqHostConfigurator.cs
src/MassTransit.ActiveMqTransport/Configuration/IActiveMqReceiveEndpointConfigurator.cs
src/MassTransit.ActiveMqTransport/Configuration/IQueueConfigurator.cs
src/MassTransit.ActiveMqTransport/Configuration/ITopicConfigurator.cs
src/MassTransit.ActiveMqTransport/ConnectionContext.cs
src/MassTransit.ActiveMqTransport/Pipeline/ActiveMqBasicConsumer.cs
src/MassTransit.ActiveMqTransport/Topology/Entities/Consumer.cs
src/MassTransit.ActiveMqTransport/Topology/Entities/Queue.cs
src/MassTransit.ActiveMqTransport/Topology/Entities/Topic.cs
src/MassTransit.ActiveMqTransport/Topology/IActiveMqHostTopology.cs
src/MassTransit.ActiveMqTransport/Transport/ActiveMqHost.cs
src/MassTransit.ActiveMqTransport/Transport/ActiveMqReceiveTransport.cs

Was reviewing ActiveMQ transport and saw a few references of RabbitMQ replaced them with ActiveMQ.

Removed all references of RabbitMQ from ActiveMQ transport

---

src/MassTransit.RabbitMqTransport.Tests/Encrypted_Specs.cs
src/MassTransit.Tests/Serialization/GivenAComplexMessage.cs
src/MassTransit.Tests/Serialization/IEnumerable_Specs.cs
src/MassTransit.Tests/Serialization/Interface_Specs.cs
src/MassTransit.Tests/Serialization/JsonSerialization_Specs.cs
src/MassTransit.Tests/Serialization/MessageDataSerialization_Specs.cs
src/MassTransit.Tests/Serialization/MoreSerialization_Specs.cs
src/MassTransit.Tests/Serialization/Performance_Specs.cs
src/MassTransit.Tests/Serialization/PropertyType_Specs.cs
src/MassTransit.Tests/Serialization/ReceiveFault_Serialization_Specs.cs
src/MassTransit.Tests/Serialization/SerializationTest.cs
src/MassTransit/Configuration/SerializerConfigurationExtensions.cs
src/MassTransit/Serialization/AesCryptoStreamProvider.cs
src/MassTransit/Serialization/AesCryptoStreamProviderV2.cs
src/MassTransit/Serialization/ConstantSecureKeyProvider.cs
src/MassTransit/Serialization/DisposingCryptoStream.cs
src/MassTransit/Serialization/EncryptedMessageDeserializerV2.cs
src/MassTransit/Serialization/EncryptedMessageSerializerV2.cs
src/MassTransit/Serialization/ICryptoStreamProviderV2.cs
src/MassTransit/Serialization/ISecureKeyProvider.cs

PR includes a new encrypted message serializer and deserializer that supports reading and writing the IV to the start of the stream. The IV is also rotated on each message so that even if we have the same message content the cyphertext will differ each time.
I've also ended the basic `ISecureKeyProvider` so this takes in `ReceiveContext` and `SendContext` to allow other implementation such as AWS KMS (See [KmsSecureKeyProvider](https://github.com/BigChangeApps/BigChange.MassTransit.AWSKeyManagementService/blob/master/src/BigChange.MassTransit.AwsKeyManagementService/KmsSecureKeyProvider.cs)).
This change is forward compatible due to the content type being changed to include a version (`application/vnd.masstransit.v2+aes`) so both the old and new can be run side by side until people have …

V2 EncryptedMessage Serializer/Deserializer

---

README.md

Current URL is returning 404, updated logo url to https://avatars2.githubusercontent.com/u/317796?s=200&v=4

Updated Logo URL

---

.gitignore
src/MassTransit.AzureServiceBusTransport.Tests/AzureServiceBusTestFixture.cs
src/MassTransit.AzureServiceBusTransport.Tests/Configuration.cs
src/MassTransit.AzureServiceBusTransport.Tests/ConfiguringAzure_Specs.cs
src/MassTransit.AzureServiceBusTransport.Tests/TestAzureServiceBusAccountSettings.cs
src/MassTransit.AzureServiceBusTransport.Tests/TwoScopeAzureServiceBusTestFixture.cs
src/MassTransit.AzureServiceBusTransport.Tests/Verify_account_settings.cs

The Azure Service Bus settings for the Azure Service Bus tests are hard-coded and this bus is not accessible for external developers. This PR makes the settings configurable by providing them in a [.runsettings](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file) file. This allows external developers to configure their own service bus and run the tests. If none is provided or if the settings are not present, the same values from the original code are returned, so no change to the current build pipeline should be needed when merging this PR.
Example: default.runsettings
```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
<TestRunParameters>
<Parameter name="ServiceNamespace" value="masstransit-build" />
<Parameter name="KeyName" …
```

Make Azure Service Bus test settings configurable

---

src/MassTransit.Azure.ServiceBus.Core.Tests/AzureServiceBusTestFixture.cs
src/MassTransit.Azure.ServiceBus.Core.Tests/BasicAzureServiceBusAccountSettings.cs
src/MassTransit.Azure.ServiceBus.Core.Tests/Basic_Specs.cs
src/MassTransit.Azure.ServiceBus.Core.Tests/Configuration.cs
src/MassTransit.Azure.ServiceBus.Core.Tests/ConfiguringAzure_Specs.cs
src/MassTransit.Azure.ServiceBus.Core.Tests/TestAzureServiceBusAccountSettings.cs
src/MassTransit.Azure.ServiceBus.Core.Tests/TwoScopeAzureServiceBusTestFixture.cs
src/MassTransit.Azure.ServiceBus.Core.Tests/Verify_account_settings.cs

The Azure Service Bus settings for the Azure Service Bus Core tests are hard-coded and this bus is not accessible for external developers. This PR makes the settings configurable by providing them in a .runsettings file. This allows external developers to configure their own service bus and run the tests. If none is provided or if the settings are not present, the same values from the original code are returned, so no change to the current build pipeline should be needed when merging this PR.
Example: default.runsettings
```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
<TestRunParameters>
<Parameter name="ServiceNamespace" value="masstransit-build" />
<Parameter name="KeyName" value="MassTransitBuild" />
<Parameter name="SharedAccessKey" …
```

Make Servicebus settings configurable for .net core test project

---

src/MassTransit.AutomatonymousIntegration/Activities/FaultedSendActivity.cs
src/MassTransit.AutomatonymousIntegration/Activities/SendActivity.cs
src/MassTransit.AutomatonymousIntegration/SendWithConventionsExtensions.cs

We are missing Send activity overloads that use endpoint convention to send messages, without specifying the destination address. This PR fixes it.

Add Send activity that uses endpoint convention

---

src/MassTransit/Transports/InMemory/Fabric/MessageFabric.cs
src/MassTransit/Transports/InMemory/GraphValidation/CyclicGraphException.cs
src/MassTransit/Transports/InMemory/GraphValidation/DependencyGraph.cs

This fixes issues that I discovered when I was running highly concurrent tests and they were building a lot of in memory transports. The exception told that graph was cyclic when in fact the inner exception told that there was a concurrent modification.
```
System.InvalidOperationException: The exchange binding would create a cycle in the messaging fabric. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
at MassTransit.Transports.InMemory.Fabric.MessageFabric.ValidateBinding(IMessageSink`1 destination, IInMemoryExchange sourceExchange)
--- End of inner exception stack trace ---
at MassTransit.Transports.InMemory.Fabric.MessageFabric.ValidateBinding(IMessageSink`1 …
```

Better exception when cyclic graph detect and concurrency protections

---

src/MassTransit.Azure.ServiceBus.Core/ServiceBusHost.cs

AMQP is forced even if you want to use "AmqpWebSockets" transport type.

Remove forcing AMQP protocol

---

src/MassTransit.Tests/Serialization/JsonSerialization_Specs.cs
src/MassTransit/Serialization/JsonMessageSerializer.cs

Add StringDecimalConverter to default Serializer converters to match Deserializer converters. Decimals across full range and precision now serialize/deserialize correctly.
New test added to verify change.

Add StringDecimalConverter to default Serializer converters.

---

src/MassTransit.Azure.ServiceBus.Core/Hosting/ServiceBusServiceConfigurator.cs
src/MassTransit.AzureServiceBusTransport/Hosting/ServiceBusServiceConfigurator.cs
src/MassTransit.RabbitMqTransport/Hosting/RabbitMqServiceConfigurator.cs
src/MassTransit/Configuration/BusConfigurators/BusFactoryConfigurator.cs
src/MassTransit/Configuration/EndpointSpecifications/ReceiveSpecification.cs
src/MassTransit/Configuration/IBusFactoryConfigurator.cs
src/MassTransit/Configuration/IReceiveEndpointConfigurator.cs
src/MassTransit/Configuration/ManagementEndpointConfigurator.cs
src/MassTransit/Turnout/Configuration/TurnoutServiceSpecification.cs

I messed up my last PR for [clearing message deserializers](https://github.com/MassTransit/MassTransit/pull/1205) 👎 
Looks like I ended up binning half my changes when I rebased, so here's another PR to exposing clearing message deserializers via `IBusFactoryConfigurator` and `IReceiveEndpointConfigurator` interfaces.
Sorry about the 2 PRs for one simple change.

Clearing message deserializers (missing bits)

---

src/Containers/MassTransit.AspNetCoreIntegration/MassTransit.AspNetCoreIntegration.csproj
src/Containers/MassTransit.AspNetCoreIntegration/MassTransitHostedService.cs
src/Containers/MassTransit.AspNetCoreIntegration/ServiceCollectionExtensions.cs
src/MassTransit.sln

The existing MS DI integration is a bit confusing. Usually, when third-party packages have `services.AddSomething` extensions, it means that everything will be properly registered. However, the existing `AddMassTransit` extension only allows registering consumers and sagas.
This package is less for DI but more for a better integration with ASP.NET Core, including the hosting. It allows registering and hosting the resolved instance, which uses the existing `AddMassTransit`, or a pre-made bus instance, when consumers are configured without the container, or using a resolved instance if consumers are added to the container differently, or the existing `AddMassTransit` has already been called.
If it gets accepted, I will write the documentation.

Hosting for ASP.NET Core

---

src/MassTransit/BusControlExtensions.cs

Pretty simple change - just adds `this` to the `DeployAsync` method so that it can be used from the `IBusControl` context.
Thanks!

Make DeployAsync an extension method

---

README.md

Nuget says works on netstandard2.0, so updated README to match

Updated requirements to include netstandard2.0

---

src/MassTransit.RabbitMqTransport/RabbitMqAddressExtensions.cs

This change makes able to perform IBus.Send(...) when RabbitMQ virtual host name contains slashes. E.g. "/test" or "/other/test". This is part of AMQP spec, which RabbitMQ follows. See  [https://www.rabbitmq.com/uri-spec.html](url) section "2.4. Vhost".

RabbitMQ: support slashes in vhosts names

---

appveyor.yml

The uninstall command was failing, so we use a tweaked command.

Fix Uninstall for CosmosDb Emulator

---

src/MassTransit.ApplicationInsights/ApplicationInsightsFilter.cs

I've just moved AI StopOperation to finally block, based on MS docs for queues: 
https://docs.microsoft.com/en-us/azure/application-insights/application-insights-custom-operations-tracking#queue-instrumentation

Move StopOperation into finally block

---

src/MassTransit.ApplicationInsights/ApplicationInsightsMiddlewareConfiguratorExtensions.cs

As discussed on Gitter - removed the redundant extension methods which cause ambiguous reference issues on configuring the bus.

AppInsights: Removed redundant extension methods.

---

src/MassTransit.ApplicationInsights.Tests/ApplicationInsightsPublishFilter_Specs.cs
src/MassTransit.ApplicationInsights.Tests/ApplicationInsightsSendFilter_Specs.cs
src/MassTransit.ApplicationInsights/ApplicationInsightsPublishFilter.cs
src/MassTransit.ApplicationInsights/ApplicationInsightsSendFilter.cs

As discussed on gitter - this allows for updated op Ids sent in from ASP.NET to be sent through to consumers.

AppInsights - Updating configure operation invoke to run before context headers are set

---

src/MassTransit.AutomatonymousIntegration.Tests/DiscardEvent_Specs.cs
src/MassTransit.AutomatonymousIntegration.Tests/NHibernateFactory_Specs.cs
src/MassTransit.AutomatonymousIntegration.Tests/UsingEntityFrameworkConcurrencyFail_Specs.cs
src/MassTransit.AutomatonymousIntegration.Tests/UsingEntityFrameworkConcurrencyOptimistic_Specs.cs
src/MassTransit.AutomatonymousIntegration.Tests/UsingEntityFrameworkConcurrencyPessimistic_Specs.cs
src/MassTransit.AutomatonymousIntegration.Tests/UsingEntityFramework_Specs.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration.Tests/SagaLocator_Specs.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreMetadataHelper.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration/ISagaDbContextFactory.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration/MassTransit.EntityFrameworkCoreIntegration.csproj
src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Saga/DelegateSagaDbContextFactory.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Saga/EntityFrameworkSagaRepository.cs
src/Persistence/MassTransit.EntityFrameworkIntegration.Tests/SagaLocator_Specs.cs
src/Persistence/MassTransit.EntityFrameworkIntegration/MassTransit.EntityFrameworkIntegration.csproj
src/Persistence/MassTransit.EntityFrameworkIntegration/Saga/DelegateSagaDbContextFactory.cs
src/Persistence/MassTransit.EntityFrameworkIntegration/Saga/EntityFrameworkSagaRepository.cs
src/Persistence/MassTransit.EntityFrameworkIntegration/SagaDbContextFactory.cs

The current DbContext creation with EF doesn't allow a way to resolve from a scoped lifecycle.

Changing EF to use a scope-focused DbContext factory

---

docs/introduction/packages.md

Hi
When setting up logging in my project, I noticed that this Nuget link to MassTransit.SeriLog in the documentation returned a 404. I've corrected it.
Cheers,
Andrew

Correct the name of MassTransit.SeriLogIntegration nuget package in docs

---

src/MassTransit.SignalR.Tests/HubLifeTimeManagerTests.cs

- I had noticed this when working on the cake build, this sometimes failed
I added a delay,hoping it would help, but it is intermittent. Running in Visual Studio
it passes 100% of the time.

Add Flakey Test Category for specific SignalR Test

---

appveyor.yml
build.cake
build/paths.cake
build/version.cake
src/Directory.Build.props
version.props

appveyor requires each build to have a unique number, so it must be
`version: X.X.X.{build}`

Update Version to read from Yml

---

src/MassTransit.QuartzIntegration/QuartzIntegrationExtensions.cs

Hi.
We need to configure the Quarts from within the C# code. Can we have a overload of UseInMemoryScheduler which takes the ISchedulerFactory as a parameter?

QuartzIntegrationExtensions.UseInMemoryScheduler with ISchedulerFactory

---

src/MassTransit/Events/FaultExceptionInfo.cs

Fixes #1348.
Exception.GetBaseException returns the deepest InnerException. I can't say why we need this behavior, so I removed it.
With this change [my simple tests ](https://github.com/GreenKn1ght/MT.FaultExceptionInfo.Tests) completed successfully.

Removed exception.GetBaseException() from FaultExceptionInfo.ctor

---

src/MassTransit.AmazonSqsTransport/Configuration/Builders/AmazonSqsReceiveEndpointBuilder.cs
src/MassTransit.AmazonSqsTransport/Configuration/Configuration/AmazonSqsReceiveEndpointConfiguration.cs
src/MassTransit.AmazonSqsTransport/Configuration/Configurators/AmazonSqsBusFactoryConfigurator.cs
src/MassTransit.AmazonSqsTransport/Configuration/IQueueConfigurator.cs
src/MassTransit.AmazonSqsTransport/Configuration/ITopicConfigurator.cs
src/MassTransit.AmazonSqsTransport/Contexts/AmazonSqsClientContext.cs
src/MassTransit.AmazonSqsTransport/Topology/Builders/BrokerTopologyBuilder.cs
src/MassTransit.AmazonSqsTransport/Topology/Builders/PublishEndpointBrokerTopologyBuilder.cs
src/MassTransit.AmazonSqsTransport/Topology/Configuration/Configurators/QueueConfigurator.cs
src/MassTransit.AmazonSqsTransport/Topology/Configuration/Configurators/TopicConfigurator.cs
src/MassTransit.AmazonSqsTransport/Topology/Entities/Queue.cs
src/MassTransit.AmazonSqsTransport/Topology/Entities/QueueEntity.cs
src/MassTransit.AmazonSqsTransport/Topology/Entities/Topic.cs
src/MassTransit.AmazonSqsTransport/Topology/Entities/TopicEntity.cs
src/MassTransit.AmazonSqsTransport/Topology/IBrokerTopologyBuilder.cs
src/MassTransit.AmazonSqsTransport/Topology/ReceiveSettings.cs
src/MassTransit.AmazonSqsTransport/Topology/Topologies/AmazonSqsMessagePublishTopology.cs

This PR adds ability to setup extra attributes in AWS infrastructure. As existing `.Attributes` haven't been published yet I think its rename to `.QueueAttributes` shouldn't be considered a BC?

Added support for Queue, Topic, QueueSubscription and TopicSubscription attributes for SQS/SNS

---

src/MassTransit.ApplicationInsights.Tests/ApplicationInsightsConsumeFilter_Specs.cs
src/MassTransit.ApplicationInsights.Tests/ApplicationInsightsPublishFilter_Specs.cs
src/MassTransit.ApplicationInsights.Tests/ApplicationInsightsSendFilter_Specs.cs
src/MassTransit.ApplicationInsights.Tests/CopyPropertiesTelemetryInitializer.cs
src/MassTransit.ApplicationInsights/Pipeline/ApplicationInsightsConsumeFilter.cs
src/MassTransit.ApplicationInsights/Pipeline/ApplicationInsightsPublishFilter.cs
src/MassTransit.ApplicationInsights/Pipeline/ApplicationInsightsSendFilter.cs

This PR aims to fix #1359 by ensuring MassTransit overwrites already set properties.
I believe this is a better situation than to fail logging, or to fail processing because of a logging process.

Appinsights property name collision

---

src/MassTransit.AutomatonymousIntegration/Activities/FaultedPublishActivity.cs
src/MassTransit.AutomatonymousIntegration/Activities/FaultedRequestActivity.cs
src/MassTransit.AutomatonymousIntegration/Activities/FaultedRespondActivity.cs
src/MassTransit.AutomatonymousIntegration/Activities/FaultedScheduleActivity.cs
src/MassTransit.AutomatonymousIntegration/Activities/FaultedSendActivity.cs
src/MassTransit.AutomatonymousIntegration/AsyncEventExceptionMessageFactory.cs
src/MassTransit.AutomatonymousIntegration/ConsumeExceptionEventContext.cs
src/MassTransit.AutomatonymousIntegration/ContextExtensions.cs
src/MassTransit.AutomatonymousIntegration/Contexts/AutomatonymousConsumeExceptionEventContext.cs
src/MassTransit.AutomatonymousIntegration/PublishExtensions.cs
src/MassTransit.AutomatonymousIntegration/RequestExtensions.cs
src/MassTransit.AutomatonymousIntegration/RespondExtensions.cs
src/MassTransit.AutomatonymousIntegration/ScheduleDateTimeExtensions.cs
src/MassTransit.AutomatonymousIntegration/ScheduleDelayExceptionProvider.cs
src/MassTransit.AutomatonymousIntegration/ScheduleDelayProvider.cs
src/MassTransit.AutomatonymousIntegration/ScheduleTimeExceptionProvider.cs
src/MassTransit.AutomatonymousIntegration/ScheduleTimeProvider.cs
src/MassTransit.AutomatonymousIntegration/ScheduleTimeSpanExtensions.cs
src/MassTransit.AutomatonymousIntegration/SendByConventionExtensions.cs
src/MassTransit.AutomatonymousIntegration/SendExtensions.cs
src/MassTransit.AutomatonymousIntegration/ServiceAddressExceptionProvider.cs
src/MassTransit.AutomatonymousIntegration/ServiceAddressProvider.cs

The API is currently allowing 
- `Send`/`SendAsync`
- `Schedule`/`Unschedule`
- `Respond`/`RespondAsync`
- `Request`
- `Publish`/`PublishAsync`
from
- `When(Event)`
- `When(Event).Catch<Exception>()`
- `WhenEnter(State)`
but not from
- `WhenEnter(State).Catch<Exception>().`
This PR aims to close this gap in the API.
-----
Some renaming had to occur to remove a collision between `<TInstance, TData>` and `<TInstance, TException>`
This is sort of a breaking change as projects referencing these types might need to adapt their code a little bit.

Support scheduling from WhenEnter/Catch blocks

---

src/MassTransit.AmazonSqsTransport/AmazonSqsSendContext.cs

Those properties have been added to `TransportAmazonSqsSendContext` but should also be defined in `AmazonSqsSendContext` interface.

Added missing GroupId and DeduplicationId in AmazonSqsSendContext

---

src/MassTransit/Clients/ClientRequestHandle.cs

When running under ASP.Net/SignalR (not dotnet core) the `AspNetSynchronisationContext` won't allow `async void` methods to be called.
Changing this to an `async Task` fixes the problem.

Fix exception when using MessageRequestClient from asp.net/signalr - Fixes #1395

---

src/Directory.Build.props

- Will help users identify official MassTransit Packages in Nuget package search

Add MassTransit Logo to Nuget Packages

---

src/MassTransit.Azure.ServiceBus.Core/Contexts/ServiceBusNamespaceContext.cs
src/MassTransit.AzureServiceBusTransport/Contexts/ServiceBusNamespaceContext.cs

We are having an issue with lost topic-subscription for ASB. In cases when ASB throws an exception while configuring the topology, the target forwardTo value contains the ASB uri. This fails the comparison with the current value and in effect the subscription is instead deleted.
I think other people is also having kind of this issue. Eg. here:
https://github.com/MassTransit/MassTransit/issues/1137
https://github.com/MassTransit/MassTransit/issues/1227

Strip 'address'-part when comparing topic subscription ForwardTo value

---

README.md

Fixes #1440 .
* Inform builders that they need a .NET Core 3.0 preview.
* Use correct build script name.
* Ask people to turn off `autocrlf` for just the repository, not globally.

Fix #1440 by improving build instructions

---

build.cake
src/Directory.Build.props

When installing VS2017 and VS2019 side by side, it will use MSBuild V16, and enforce C#8 rules, even though it's still in preview.
So we explicitly use MSBuild V15, and set the lang version to 7.3
Once .NET Core 3.0 is released, this will likely need to be modified again, once we want to support C#8

Use MSBuild V15.X on Windows

---

src/MassTransit.Azure.ServiceBus.Core/Transport/ServiceBusSendTransport.cs
src/MassTransit.AzureServiceBusTransport/Transport/ServiceBusSendTransport.cs

SessionId was being set to ConversationId when otherwise unspecified by the user. This has the potential (to be determined) to break the Azure Service Bus auto-forwarder feature when sending messages to non-partitioned topics that are forwarding to partitioned queues. At least according to Azure support.
@phatboyg Seems to think there isn't a good reason for this to be done.

Do not default SessionId to ConversationId.

---

src/MassTransit.RabbitMqTransport/Configuration/Builders/RabbitMqReceiveEndpointBuilder.cs
src/MassTransit.RabbitMqTransport/Configuration/Configuration/RabbitMqReceiveEndpointConfiguration.cs
src/MassTransit.RabbitMqTransport/Configuration/IRabbitMqReceiveEndpointConfigurator.cs
src/MassTransit.RabbitMqTransport/Topology/ReceiveSettings.cs
src/MassTransit.RabbitMqTransport/Topology/Settings/RabbitMqReceiveSettings.cs

When is used `DeployTopologyOnly=true` for creating RabbitMQ Bus very useful to have the ability to deploy the only exchange, without a queue.  It's helpful for cases when we have a topology with direct exchanges.  
For this purpose added property `CreateExchangeOnly` in IRabbitMqReceiveEndpointConfigurator.

Add the ability to create only exchange for RabbitMq ReceiveEndpoint

---

src/Containers/MassTransit.AspNetCoreIntegration/HealthChecks/HealthCheckOptions.cs
src/Containers/MassTransit.AspNetCoreIntegration/ServiceCollectionExtensions.cs

It's a small PR that lets you provide desired FailureStatus and Tags for MT health check.
Why is it needed? Let's take as an example an app that receives messages from rabbitMQ using MT, stores them to database and serves them via HTTP. If rabbitMQ is down - the app can still answer HTTP calls and return whatever it has in database. So the app is still working but not fully - hence it's degraded.
Without this PR the app would have Unhealthy status which if used together with k8s would stop k8s from connecting the app to load balancer rendering the app offline and inaccessible.
The PR is backwards compatible because it uses old values as default values in HealthCheckOptions

Make health check less opinionated and more configurable

---

src/Containers/MassTransit.AspNetCoreIntegration/HealthChecks/ReceiveEndpointHealthCheck.cs
src/Containers/MassTransit.AspNetCoreIntegration/HealthChecks/SimplifiedBusHealthCheck.cs

Last time I made a mistake - I created a PR and I didn't check that the code works because the change was so trivial that I didn't think anything could be wrong. Unfortunately I missed that there were two places where failure status for health checks was hardcoded so that my customization didn't work as intended.
I learned my lesson and now I really tested it in my real project
This PR removes hardcoded health check failure status and uses the status from health check registration that is initially comes from HealthCheckOptions.FailureStatus

Use FailureStatus from health check registration rather than hardcoded

---

src/MassTransit.QuartzIntegration.Tests/PastEvent_Specs.cs
src/MassTransit.QuartzIntegration/CancelScheduledMessageConsumer.cs
src/MassTransit.QuartzIntegration/MassTransitJobFactory.cs
src/MassTransit.QuartzIntegration/QuartzIntegrationExtensions.cs
src/MassTransit.QuartzIntegration/ScheduleMessageConsumer.cs
src/MassTransit.QuartzIntegration/ScheduledMessageJob.cs

When `TokenId` for schedule message is the same, Quartz should reschedule a message with new data, but now it uses old data and only change a trigger date.
Also other improvements:
- use `CancellationToken` from `ConsumeContext`
- use `CancellationToken` from `IJobExecutionContext`
- use `Environment.ProcessorCount` for partitioner

- fix reschedule message when quartz uses old jobDetails

---

src/MassTransit.Tests/Serialization/MoreSerialization_Specs.cs
src/MassTransit/Serialization/JsonConverters/ListJsonConverter.cs

The `ListJsonConverter` was recently changed to check for the existence of `IReadOnlyCollection`, but this breaks deserialization for `ISet<T>` and derivatives because the collection is then safe-casted to `IList<T>` which is not an interface implemented by sets, resulting in null and the below exception. I've changed the cast to `ICollection<T>`, which sets do implement. I've added two tests that make sure the change functions properly.
The error:
```
Parameter name: target
System.ArgumentNullException: Value cannot be null.
Parameter name: target
at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
at …
```

Fixed regression in deserializing ISet/HashSet

---

appveyor.yml
build.cake
tools/packages.config

Ubuntu test results stopped showing up. Started [thread here](https://help.appveyor.com/discussions/problems/24784-dotnet-test-from-ubuntu1804-started-failing-to-post-results-to-appveyor-api) to ask, they recommended using previous.
Also they fixed the dotnet build, so don't need to perform the check in cake anymore to run MSBuild versus DotNetCoreBuild

Fix ubuntu build test reporting and update cake

---

src/MassTransit.AmazonSqsTransport/Contexts/AmazonSqsClientContext.cs

Fixes #1525
Currently incorrectly generating TopicArnPattern seems to always be * should be `arn:aws:sns:[region]:[account number]:*`

Generate correct SourceArn pattern for sns-to-sqs SendMessage policy.

---

src/MassTransit.AmazonSqsTransport/Contexts/AmazonSqsReceiveContext.cs

TransportMessage.GetType() will lead to nullref in this case.

fix nullref with TransportMessage

---

src/Persistence/MassTransit.EntityFrameworkCoreIntegration/MsSqlLockStatements.cs

because it is created and used below

Removed useless creating SchemaTablePair

---

src/MassTransit.AmazonSqsTransport/Topology/AmazonSqsHostEqualityComparer.cs

Priority of '??' operator is lower than '^'. And without parentheses we always get hashCode=0 if obj.Region is null. With parentheses we get correct value.

Fix for ?? operator priority

---

docs/advanced/interoperability.md

In the _Interoperability_ documentation, added "DateTime? SentTime" to the properties of the message envelope.

Update interoperability.md in docs

---

src/MassTransit.RabbitMqTransport/Configuration/Configurators/RabbitMqHostConfigurator.cs
src/MassTransit.RabbitMqTransport/RabbitMqAddressExtensions.cs

I had the problem that the RabbitMQ connections all had an `undefined` connection name, both in the “Client-provided name” and the `connection_name` client property:
So I looked into this and found out that there is a [default value being set](https://github.com/MassTransit/MassTransit/blob/v5.5.6/src/MassTransit.RabbitMqTransport/Configuration/Configurators/ConfigurationHostSettings.cs#L36) but which is then overridden [in the constructors](https://github.com/MassTransit/MassTransit/blob/v5.5.6/src/MassTransit.RabbitMqTransport/Configuration/Configurators/RabbitMqHostConfigurator.cs#L48) of `RabbitMqHostConfigurator` even if there was no passed connection name:
https://github.com/MassTransit/MassTransit/blob/1f6a8f0509698705a8d892dd10e3cc2a96e14ed3/src/MassTransit.RabbitMqTransport/Config …

Fix default ClientProvidedName for RabbitMQ

---

src/Containers/MassTransit.AspNetCoreIntegration/ServiceCollectionExtensions.cs
src/MassTransit/Context/LogContext.cs

It should not be possible to register own diagnostic source.
regarding to DiagnosticSource practices:
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md#diagnosticlistener-names

- remove ability to register own diagnostic source

---

src/Persistence/MassTransit.EntityFrameworkCoreIntegration.Tests/ContextFactoryWithResilienceStrategy.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration.Tests/SimpleSagaDbContext.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration.Tests/SimpleSagaDbContextWithResilienceStrategy.cs

While working on some changes on the EFAudit feature to add a new column to the audit records I found a issue with adding migrations. When detecting implementations of IDesignTimeDbContextFactory the tool finds multiple implementations returning the same DBContext type. Please find below the command output:
```
PM> EntityFrameworkCore\Add-Migration -Name dummy -Context auditdbcontext -Verbose
Both Entity Framework Core and Entity Framework 6 are installed. The Entity Framework Core tools are running. Use 'EntityFramework\Add-Migration' for Entity Framework 6.
Using project 'Persistence\MassTransit.EntityFrameworkCoreIntegration.Tests'.
Using startup project 'Persistence\MassTransit.EntityFrameworkCoreIntegration.Tests'.
Build started...
Build succeeded.
C:\Program …
```

fixed Add-Migration item with same key exception

---

src/MassTransit/Configuration/RegistrationExtensions.cs

This is mostly because I use the generic overloads everywhere else so adding this makes it look tidier. Verified by temporarily changing the Autofac tests to use the generic overload, works fine.
I also noticed the doc comments had a copypasta error from the non-state machine saga registration methods, so it was changed slightly to be (hopefully) more correct.

Add generic AddSagaStateMachinesFromNamespaceContaining

---

docs/usage/transports/azure-sb.md
src/MassTransit.Azure.ServiceBus.Core/Configuration/Configuration/BrokeredMessageReceiverServiceBusEndpointConfiguration.cs

This allows exceptions within a consumer used in an Azure Service Bus brokered message receiver to bubble outside of the receiver. This is necessary for Azure Functions to properly handle exceptions. More details are logged in this issue: https://github.com/MassTransit/MassTransit/issues/1661
To test, I threw an exception within the consumer. Before code changes, the exception was logged yet the message was removed from the queue (completed). After these changes, the exception is caught by the Azure Function and moved to the dead letter queue after a configured number of retry attempts.

Azure Service Bus brokered message receiver exception handling

---

docs/advanced/middleware/transactions.md
src/Containers/MassTransit.AutoFacIntegration/AutofacTransactionOutboxExtensions.cs
src/Containers/MassTransit.ExtensionsDependencyInjectionIntegration/DependencyInjectionTransactionOutboxExtensions.cs
src/Containers/MassTransit.LamarIntegration/LamarTransactionOutboxExtensions.cs
src/Containers/MassTransit.SimpleInjectorIntegration/SimpleInjectorTransactionOutboxExtensions.cs
src/Containers/MassTransit.StructureMapIntegration/StructureMapTransactionOutboxExtensions.cs
src/Containers/MassTransit.WindsorIntegration/WindsorTransactionOutboxExtensions.cs
src/MassTransit.Tests/Transactions/TransactionOutbox_Specs.cs
src/MassTransit.sln
src/MassTransit/Transactions/TransactionOutbox.cs
src/MassTransit/Transactions/TransactionOutboxEnlistment.cs
src/MassTransit/Transactions/TransactionOutboxSendEndpoint.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration.Tests/LocalDbConnectionStringProvider.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration.Tests/MassTransit.EntityFrameworkCoreIntegration.Tests.csproj
src/Persistence/MassTransit.EntityFrameworkCoreIntegration.Tests/TransactionOutbox_Specs.cs
src/Samples/MassTransit.SignalR.SampleConsole/Program.cs

- for feature request #1627 
- Documentation added, used decorator on the Singleton (for IBusControl). If using IPublishEndpoint or ISendEndpointProvider from within a ConsumeContext, then use InMemoryOutbox.
- Instead of the cleanup happening in "Commit, InDoubt, or Rollback", I subscribed to the `+= TransactionCompleted` event, and perform clean up there.
- had to use TaskUtil.Await in Prepare method because publish/send are async, but the IEnlistmentNotification interface is not async. So this was the only option. 
- Added tests, also for good measure I added some tests with EFCore, to see how it behaves with DBContext and an ambient transaction.  These are in the EFCore Saga test project, but don't have anything to actually do with EFCore Saga. I just wanted the ease of using existing …

Add Transaction Outbox

---

docs/usage/configuration.md

Minor change to the documentation to fix the variable name being used 😃

Fix variable reference in docs

---

docs/usage/sagas/ef.md

I saw a little mistake in the docs related to the way we should set the retry interval.
`Interval` method is an extension on `IRetryConfigurator` and not on `IServiceCollectionConfigurator`.

Fixed Retry Interval code for EF Saga docs

---

docs/usage/sagas/ef.md

`AddDbContext` is not available for EF. It is available only for EF Core.
You can see that only the second link has `AddDbContext`:
[MassTransit.EntityFrameworkIntegration's IEntityFrameworkSagaRepositoryConfigurator](https://github.com/MassTransit/MassTransit/blob/master/src/Persistence/MassTransit.EntityFrameworkIntegration/Configuration/IEntityFrameworkSagaRepositoryConfigurator.cs)
[MassTransit.EntityFrameworkCoreIntegration's IEntityFrameworkSagaRepositoryConfigurator](https://github.com/MassTransit/MassTransit/blob/master/src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Configuration/IEntityFrameworkSagaRepositoryConfigurator.cs)

Fixed EF Saga Persistence example

---

src/MassTransit.SignalR.Tests/Utils/MassTransitHubLifetimeTestFixture.cs
src/MassTransit.SignalR/BaseMassTransitHubLifetimeManager.cs
src/MassTransit.SignalR/Configuration/HubLifetimeManagerOptions.cs
src/MassTransit.SignalR/Configuration/IHubLifetimeManagerOptions.cs
src/MassTransit.SignalR/Consumers/AllMessageDataConsumer.cs
src/MassTransit.SignalR/Consumers/ConnectionMessageDataConsumer.cs
src/MassTransit.SignalR/Consumers/GroupManagementConsumer.cs
src/MassTransit.SignalR/Consumers/GroupMessageDataConsumer.cs
src/MassTransit.SignalR/Consumers/UserMessageDataConsumer.cs
src/MassTransit.SignalR/Contracts/Connection.cs
src/MassTransit.SignalR/Contracts/Group.cs
src/MassTransit.SignalR/MassTransitDependencyInjectionExtensions.cs
src/MassTransit.SignalR/MassTransitHubLifetimeManager.cs
src/MassTransit.SignalR/MassTransitMessageDataHubLifetimeManager.cs
src/MassTransit.SignalR/MassTransitSignalRConfigurationExtensions.cs
src/MassTransit.SignalR/MassTransitSignalROptions.cs
src/MassTransit.SignalR/Utils/MassTransitSubscriptionManager.cs
src/MassTransit.SignalR/Utils/SerializedHubMessageExtensions.cs

This pull request provide few changes for SignalR:
- configure LifetimeManager as scoped per hub (which allows to use all advantages of MassTransit MSDI setup)
- applied code style a bit
- configure `UseMessageData` per hub
- request timeout per hub

Change SignalR Configuration Approach

---

docs/architecture/newid.md

In text it says 128-bits (16-bits), but instead of "16-bytes", it was "16-bits"

Fixed bit typo in NewId docs

---

docs/usage/sagas/marten.md

The connectionString example on the doc for Marten doesn't work for latest Marten 3.11.0, changed `server` to `host` and `user id` to `username` and got it working properly.

Update connectionString example for Marten 3.11.0

---

docs/usage/sagas/consumer-saga.md

I noticed this small error in the documentation regarding Consumer Sagas and `ICorrelatedBy<Guid>` that should be `CorrelatedBy<Guid>`

Use correct interface name for Correlation

---

src/MassTransit/Automatonymous/SendExtensions.cs

Hi Chris,
I fixed these overloads. They call FaultedSendActivity now.

Fix for exception binder overloads calling wrong activity

---

docs/usage/sagas/ef.md

Added section in which we are specifying that config file or static method call approach is mandatory when having multiple DbContexts.
In case the Saga's DbContext initializes before the application's DbContext, you will be unable to use the latter for the entire of the application's lifetime.
You will receive exceptions similar to:
```
System.InvalidOperationException: 
The default DbConfiguration instance was used by the Entity Framework before the 'XDbConfiguration' type was discovered. An instance of 'XDbConfiguration' must be set at application start before using any Entity Framework features or must be registered in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=260883 for more information.
```

Docs - Added details about custom DbConfiguration EF Saga Persistance

---

docs/architecture/interoperability.md

I've tested with a legacy producer and can confirm the minimal event format only needs a "message" object and a "messageType" property.

Updated Minimal required message for interop

---

src/Transports/MassTransit.EventHubIntegration/Configuration/Configurators/EventHubEndpointConfigurator.cs
src/Transports/MassTransit.EventHubIntegration/Contexts/ProcessorLockContext.cs

Chain `PartitionInitializingAsync` and `PartitionClosingAsync` to fix adding issue:
```csharp
add
{
Argument.AssertNotNull(value, nameof(PartitionInitializingAsync));
if (_partitionInitializingAsync != default)
{
throw new NotSupportedException(Resources.HandlerHasAlreadyBeenAssigned);
}
EnsureNotRunningAndInvoke(() => _partitionInitializingAsync = value);
}
```
https://github.com/MassTransit/MassTransit/issues/2112

Chain PartitionInitializingAsync and PartitionClosingAsync [#2112]

---

docs/advanced/middleware/custom.md

When the message type is used in the filter, the Send signature uses ConsumeContext<T> instead of T directly.

Fix error in Message Type Filters documentation

---

src/Transports/MassTransit.EventHubIntegration/Configuration/Configurators/EventHubEndpointConfigurator.cs

Fix Url creation for block container in EventHub Rider to address the issue: https://github.com/MassTransit/MassTransit/issues/2149

Fix BlobContainerClient Uri creation #2149

---

src/Transports/MassTransit.RabbitMqTransport/Transport/RabbitMqHost.cs

While experimenting with MassTransit 7.1.1, I ran into a NullReferenceException while trying to probe the bus.
To be completely honest, I did not test this code change. But, the following is a minimal reproduction of a NullReferenceException that occurs when calling GetProbeResult with the RabbitMQ transport.
```csharp
using System;
using GreenPipes;
using GreenPipes.Introspection;
using MassTransit;
namespace MTTest
{
class Program
{
static void Main()
{
var busControl = Bus.Factory.CreateUsingRabbitMq(cfg =>
{
cfg.Host("localhost", c =>
{
// uncommenting this avoids the NullReferenceException:
// c.Password("");
});
});
busControl.GetProbeResult();
}
}
}
```
This code results in the following NullReferenceException:
```csharp
An unhandled exception of type …
```

check for null passwords when probing RabbitMqHost

---

docs/code/usage/UsageConsumerTemporaryEndpoint.cs
docs/usage/consumers.md
docs/usage/transports/rabbitmq.md

Adds documentation about using the `TemporaryEndpointDefinition` class.
Since simply setting `AutoDelete = true, Durable = false` will leave behind an exchange, I also thought it made sense to edit the RabbitMQ best practices to suggest TemporaryEndpointDefinition instead of just setting those properties.

add documentation about TemporaryEndpointDefinition

---

src/MassTransit.Analyzers/Helpers/TypeConversionHelper.cs
src/MassTransit/Initializers/PropertyConverters/MessageDataPropertyConverter.cs
src/MassTransit/Initializers/PropertyProviders/PropertyProviderFactory.cs
src/MassTransit/MessageData/PropertyProviders/MessageDataConverter.cs
src/MassTransit/MessageData/PropertyProviders/MessageDataFactory.cs
src/MassTransit/MessageData/PropertyProviders/PutMessageDataPropertyProvider.cs
src/MassTransit/MessageData/PropertyProviders/StreamMessageDataConverter.cs
src/MassTransit/MessageData/Values/GetMessageData.cs
src/MassTransit/MessageDataExtensions.cs
src/MassTransit/Serialization/JsonConverters/MessageDataJsonConverter.cs
tests/MassTransit.Analyzers.Tests/MessageDataInitializer_Specs.cs
tests/MassTransit.Tests/MessageData/DataBus_Specs.cs
tests/MassTransit.Tests/MessageData/InitializerMessageData_Specs.cs

Added ability to use streams as message data
* Modified analyser and tests so it does not warn about using Stream in MessageData initializers
* Added unit tests for `MessageData<Stream>` initialisation
* Added unit tests for decoding stream message data
* Added unit tests for `FileSystemMessageDataRepository` and `InMemoryMessageDataRepository`
Briefly tested with `MongoDbMessageDataRepository` which passed data successfully but have not generated unit tests for this.

Streams can be added as message data

---

src/Transports/MassTransit.Azure.ServiceBus.Core/Pipeline/DeadLetterQueueExceptionFilter.cs

Simple fix: 
> Moves a faulted message to the dead-letter queue, rather than the ~_skipped~ _error queue

Fix DeadLetterQueueExceptionFilter summary comment referencing wrong queue

---

docs/advanced/topology/rabbitmq.md

To verify that the fix was applied correctly I built the VuePress project locally. I navigated to the fixed [rabbitmq.html#broker-topology](http://localhost:8080/advanced/topology/rabbitmq.html#broker-topology) page and I clicked on the link to confirm that it actually referred to the [topology](http://localhost:8080/advanced/topology/) page .

Fix broken relative reference

---

.github/workflows/docs.yml
docs/advanced/monitoring/prometheus.md

This PR adds a few more helpful comments around the prometheus docs, and it also prevents the doc build from running unless this is the MassTransit/MassTransit repo and its the `develop` branch.

Prometheus Docs Tweak

---

docs/advanced/middleware/scoped.md

The AddConsumer extension method doesn't exist for `IServiceCollection`.

Move AddConsumer call into AddMassTransit in scoped.md

---

docs/usage/exceptions.md

For a call to `e.UseMessageRetry(r => r.Immediate(5));` it requires GreenPipes to be included in the file

Include using statement for call to Immediate()

---

src/MassTransit/Courier/RoutingSlipRequestProxy.cs
src/MassTransit/Courier/RoutingSlipResponseProxy.cs

Allow Consume methods for RoutingSlipRequest/ResponseProxy to be virtual so that they may be overridden if necessary.
Original question/answer on [Stack Overflow](https://stackoverflow.com/questions/68385160/masstransit-cannot-override-the-consume-method-from-routingslipresponseproxy/68395420#68395420)
Ensured code worked by running unit tests with `dotnet test` and ensuring all unit tests passed!

Allow Consume methods for RoutingSlipRequest/ResponseProxy to be virtual

---

src/MassTransit/Configuration/Configuration/IHostConfiguration.cs
src/MassTransit/Configuration/Configurators/BaseHostConfiguration.cs
src/Transports/MassTransit.EventHubIntegration/Configuration/Configurators/EventHubFactoryConfigurator.cs
src/Transports/MassTransit.KafkaIntegration/Configuration/Configurators/KafkaFactoryConfigurator.cs
tests/MassTransit.EventHubIntegration.Tests/BatchProducer_Specs.cs
tests/MassTransit.EventHubIntegration.Tests/BatchReceive_Specs.cs
tests/MassTransit.EventHubIntegration.Tests/Contracts/BatchEventHubMessage.cs
tests/MassTransit.EventHubIntegration.Tests/Contracts/EventHubMessage.cs
tests/MassTransit.EventHubIntegration.Tests/EndpointConnector_Specs.cs
tests/MassTransit.EventHubIntegration.Tests/ProducerPipe_Specs.cs
tests/MassTransit.EventHubIntegration.Tests/Producer_Saga_Specs.cs
tests/MassTransit.EventHubIntegration.Tests/Producer_Specs.cs
tests/MassTransit.EventHubIntegration.Tests/Publish_Specs.cs
tests/MassTransit.EventHubIntegration.Tests/Receive_Specs.cs
tests/MassTransit.EventHubIntegration.Tests/Recycle_Specs.cs
tests/MassTransit.KafkaIntegration.Tests/Producer_Specs.cs
tests/MassTransit.KafkaIntegration.Tests/docker-compose.yml

Copy bus observers to Riders.
The only issue here, which we have for endpoints as well: during Send (Produce in case of Riders) we will `await` empty Task for Observers if they are empty. And @phatboyg you will live knowing that 🤣

Use Bus observers by default for Riders

---

tests/MassTransit.Azure.Cosmos.Tests/UsingCosmosConcurrencyNoRetry_Specs.cs

Fix #2702 
Use `CreateContainerIfNotExistsAsync` intead of `CreateContainerAsync` in the Setup method in `When_using_CosmosConcurrencyNoRetry`

Fixed #2702:  use CreateContainerIfNotExistsAsync in Setup method

---

src/Transports/MassTransit.EventHubIntegration/Transport/EventHubProducer.cs
src/Transports/MassTransit.KafkaIntegration/Configuration/KafkaTopicOptions.cs
src/Transports/MassTransit.KafkaIntegration/Contexts/KafkaProducerContext.cs
src/Transports/MassTransit.KafkaIntegration/Pipeline/ConfigureTopologyFilter.cs

- Do not create batch if there is no message for EventHub Producer
- Use `Debug` level for NonCritical errors for ConfigureTopology in Kafka 
- Make a short loop for kafka producer flush instead of constant timeout

Do not create batch when no more messages. Short loop for kafka producer instead of timeout

---

src/Transports/MassTransit.AmazonSqsTransport/Contexts/TopicCache.cs

AmazonSQS transport: trying to get the topic and if does not exists creating it.
With those changes we do want to prevent provisioning new topics in the application, actual environment is already created with CloudFormation before the application is deployed.

AmazonSQS transport: trying to get the topic and if does not exists creating it.

---

docs/usage/requests.md

Fixes an incorrect usage example of AddGenericRequestClient in the docs.
This extension method needs to be called on the `IServiceCollection`, not the `IServiceCollectionBusConfigurator`.

Docs: Fix example for AddGenericRequestClient

---

src/Persistence/MassTransit.EntityFrameworkCoreIntegration/SqlLockStatementProvider.cs

Public EntityFrameworkCore Api usage  instead of internal. Internal API was changed in v6. DbContext.Model usage works well with EntityFrameworkCore 3.1 & 5 & 6.

Fixed #2980 - remove internal EntityFrameworkCore api usage

---

src/Transports/MassTransit.Azure.ServiceBus.Core/Contexts/ServiceBusConnectionContext.cs

Sets the ```MaximumConcurrentCalls``` based on the configured value.
After this change, the consumer is processing multiple messages simultaneously (this example set ```e.MaxConcurrentCalls = 9;```. Prior to this change, a single message was processed at a time.
-->

Respect the MaxConcurrentCalls set in the configuration

---

src/MassTransit/Courier/Serialization/EnvelopeMessageSerializer.cs

Fixes #3048: 
Emitted Unicode BOM breaks redelivery, because `ForwardJsonMessageSerializer` converts to Json by doing `JObject.Parse(encoding.GetString(receiveContext.GetBody()))`
Tested using these tests:
https://gist.github.com/FroHenK/7fab89310405a96d482ae4b492c44833
Should a test like `Send_an_event_at_the_end_of_the_routing_slip_and_redeliver` be added to the repo?

Fixed #3048 - Removed UTF BOM emission in EnvelopeMessageSerializer

---

docs/advanced/middleware/killswitch.md

Changed 'with' to 'will' in the killswitch docs

Fixed typo in middleware/killswitch docs

---

src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/Checkpoints/BatchCheckpointer.cs
src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Checkpoints/BatchCheckpointer.cs
tests/MassTransit.EventHubIntegration.Tests/Long_Receive_Specs.cs
tests/MassTransit.KafkaIntegration.Tests/Long_Receive_Specs.cs

fix for the: https://github.com/MassTransit/MassTransit/issues/3360
Use ShutdownToken to wait for confirmation in the message.
Otherwise we'll be reading messages from channel but not putting back, when Consume time greater than CheckpointInternval

Fix checkpointer #3360

---

src/MassTransit.Abstractions/Exceptions/ExceptionInfoException.cs

Following my message on Discord : https://discord.com/channels/682238261753675864/682238261753675868/986725785299734668
The behavior is different between Consumer/JobConsumer about Data in ExceptionInfo
From a Consumer : 
From a JobConsumer : 
With a JobConsumer the Value contain the KeyValuePair when he should contains only the value
I applied the following fix that I propose to you

fix: ExceptionInfo Data should not be in Key

---

docs/usage/transports/README.md

I am adding the missing link to the new gRPC transport page.

Add missing link to the new gRPC transport page

---

docs/code/transports/GrpcMultiConsoleListener.cs

If **http://** is missing code throw UriFormatException: Invalid URI: The format of the URI could not be determined.

Add missing http:// when defining the Uri

---

src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Configuration/EntityFrameworkOutboxConfigurationExtensions.cs

Tweaking the index referenced in #3515 , so bus outbox delivery performance doesn't degrade as the outbox tables fill up
This swaps the order of the OutboxMessage unique index on (SequenceNumber,OutboxId) to (OutboxId,SequenceNumber), so query execution remains fast when filtering by OutboxId if OutboxMessage has many rows
Results of testing against ~1M rows in SQL Server. Query 1 old, Query 2 new:

Tune Unique Index on OutboxMessage: Swap Order of SequenceNumber and OutboxId

---

docs/quick-starts/in-memory.md

Update template installation snippet
Fixes:
Warning: use of 'dotnet new --install' is deprecated. Use 'dotnet new install' instead.

Update template installation snippet

---

src/MassTransit.Abstractions/Configuration/Consumers/BatchOptions.cs
src/MassTransit.Abstractions/Configuration/Consumers/BatchTimeLimitStart.cs
src/MassTransit.Abstractions/Configuration/Consumers/IBatchConfigurator.cs
src/MassTransit/Consumers/Batching/BatchCollector.cs
src/MassTransit/Consumers/Batching/BatchConsumer.cs
src/MassTransit/Consumers/Batching/BatchConsumerFactory.cs
src/MassTransit/Consumers/Configuration/BatchConfigurator.cs
src/MassTransit/Consumers/Configuration/BatchConsumerMessageConnector.cs

I'm proposing this change to resolve a scenario, where I have events that trigger some long-running or resource intensive jobs, which do not rely on any data from the actual events. This means that the more the execution is postponed, the better for the app. 
This would allow more dynamical waits until all the events come, before the aforementioned job is triggered. TimeLimit on its own is unfortunately too "constant" in its nature.
For example, there are events which could come in rapid succession, (let's suppose 2-5 seconds apart, in total about 10-20 events). If I wanted to wait until all of them come, I would need to set the TimeLimit to ~2 minutes. This would however mean, that any event that comes even a second after those two minutes would trigger another job, which is not …

Add BatchTimeLimitStart configuration option

---

docs/usage/sagas/guidance.md

This PR attempts to update the Saga Guidance section with an alternative example which shows how to configure the recommended settings with a SagaDefinition instead of configuring the receive endpoint directly. I thought this could be useful since a lot of folks use SagaDefinition.

Update guidance.md with saga definition example

---

docs/usage/sagas/guidance.md

This PR attempts to fix a broken link to the "definitions" page that was introduced in my last PR to improve the saga guidance page.

Fix broken link in guidance.md

---

docs/quick-starts/sqs.md
docs/usage/transports/amazonsqs.md

When creating an SQS queue and specifying tags to apply, the call to CreateQueue will fail with an AccessDenied error when using the original sample iam policy. Internally, CreateQueue is calling TagQueue, but as that was missing from the sample policy, an AccessDenied error is thrown. There's no indication in any of the logging from AWS as to why this is though.
Checking the code shows that the SQS transport can also call Purge & Delete Queue as well, so have added those to avoid similar problems.

Add extra sqs permissions to sample iam policy

---

README.md

👋 This is just a small documentation fix, so hopefully should be quick. GitHub no longer supports the `git://` protocol for cloning, this will fail. Instead, use the HTTPS protocol. See the [GitHub blog post](https://github.blog/2021-09-01-improving-git-protocol-security-github/) for more information.

Use https: protocol instead of deprecated git: protocol

---

docs/quick-starts/in-memory.md

Corrected the highlighted `dotnet` install command in the docs (In-Memory tutorial) which was missing dashes.  The command is correct in the preceding paragraph.

Template install command typo

---

src/MassTransit/Logging/DiagnosticHeaders.cs

Update attributes tags basaed on OpenTelemetry v1.15.0 attributes https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md#v1150-2022-11-09
How to test:
Enable Instrumentation for any MassTransit process.
`messaging.destination.kind` for now is not used so you cannot test it.

Update OpenTelemetry tags based on specification v1.15.0

---

src/MassTransit.Abstractions/NewId/INewIdGenerator.cs
src/MassTransit.Abstractions/NewId/NewId.cs
src/MassTransit.Abstractions/NewId/NewIdGenerator.cs
tests/MassTransit.Abstractions.Tests/NewId/Generator_Specs.cs
tests/MassTransit.Abstractions.Tests/NewId/NewId_Specs.cs

Mirroring changes
I've made some changes to `NextGuid` and `NextSequentialGuid` to improve their performance. These changes include vectorizing the functions, which has resulted in a speed improvement of 10-15%. As NextGuid is frequently called in MassTransit, this small improvement should add up.
Also added some simple assertion tests to ensure that the changes do not break any existing functionality. Additionally, I've made some minor code improvements.
See [original pr](https://github.com/phatboyg/NewId/pull/26) for more details.

Vectorize generate guid

---

src/MassTransit.Analyzers/MassTransit.Analyzers.csproj

By marking the MassTransit.Analyzers as a DevelopmentDependency it will not be included in the publish folder of application that uses it.
When installing the NuGet package the csproj should look like:
```xml
<PackageReference Include="MassTransit.Analyzers" Version="8.0.10">
<PrivateAssets>all</PrivateAssets>
<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```
Instead of:
```xml
<PackageReference Include="MassTransit.Analyzers" Version="8.0.10" />
```
More information on https://github.com/NuGet/Home/wiki/DevelopmentDependency-support-for-PackageReference

Mark the Analyzers assembly as a DevelopmentDependency

---

src/MassTransit.Abstractions/Util/ExceptionUtil.cs

Fixes weird exceptions (changing their StackTrace) leading to `ExceptionUtil` trying to '_cleanup' `null` `StackTrace`s.
We've got the following situation, that I can only explain by the above reason...
```
at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
at MassTransit.Util.ExceptionUtil.GetStackTrace(Exception exception) in /_/src/MassTransit.Abstractions/Util/ExceptionUtil.cs:line 38
at MassTransit.Events.FaultExceptionInfo..ctor(Exception exception) in /_/src/MassTransit/Events/FaultExceptionInfo.cs:line 44
at MassTransit.Events.FaultEvent`1.GetExceptions(Exception exception) in /_/src/MassTransit/Events/FaultEvent.cs:line 46
at …
```

Store, check and cleanup StackTrace

---

src/MassTransit/Transports/ReceiveTransport.cs
src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/TopicProducer.cs

Receive Transport should await Completed task which is receiver task to avoid potential race-conditions

await for Completed for ReceiveTransport

---

src/MassTransit.Abstractions/NewId/NewId.cs

Fix #4040.
I mistakenly checked if `Sse3.IsSupported` when using `Ssse3.Shuffle` this meant that devices supporting `Sse3` but not `Ssse3` would try to call `Ssse3.Shuffle` and get a `PlatformNotSupportedException`. 
I'm really sorry, kicking myself rn.

Use Ssse3.IsSupported

---

src/MassTransit.Abstractions/Configuration/Middleware/IReceiveEndpointConfigurator.cs
src/MassTransit.Abstractions/Configuration/Middleware/IReceiveEndpointDependencyConnector.cs
src/MassTransit.Abstractions/Configuration/Middleware/IReceiveEndpointDependentConnector.cs
src/MassTransit.Abstractions/Transports/IReceiveEndpointDependent.cs
src/MassTransit/Configuration/Configuration/IReceiveEndpointConfiguration.cs
src/MassTransit/Configuration/Configuration/ReceiveEndpointConfiguration.cs
src/MassTransit/Configuration/Configuration/ReceiverConfiguration.cs
src/MassTransit/InMemoryTransport/InMemoryTransport/InMemoryReceiveTransport.cs
src/MassTransit/Transports/BaseReceiveEndpointContext.cs
src/MassTransit/Transports/Contexts/ReceiveEndpointContext.cs
src/MassTransit/Transports/ReceiveEndpoint.cs
src/MassTransit/Transports/TransportStartExtensions.cs
src/Transports/MassTransit.GrpcTransport/GrpcTransport/GrpcReceiveTransport.cs

Adding Dependents when Dependency added.
Eg:
1. A is dependency of B
2. B is started only after A
3. A is stopped only after B
Added 2 sec delay for start/stop:
```
15:26:04.474-I Configured endpoint odd-job, Consumer: MassTransit.Tests.JobConsumerTests.OddJobConsumer
15:26:04.479-I Configured endpoint odd-job-completed, Consumer: MassTransit.Tests.JobConsumerTests.OddJobCompletedConsumer
15:26:04.549-D Starting bus instances: IBus
15:26:04.551-D Starting bus: loopback://localhost/
15:26:04.569-D Endpoint Ready: loopback://localhost/job-attempt
15:26:04.569-D Endpoint Ready: loopback://localhost/job-type
15:26:04.569-D Endpoint Ready: loopback://localhost/instance-rrtoyyg6ww5pdopcbdpofi1pbd
15:26:04.569-D Endpoint Ready: loopback://localhost/job
15:26:04.569-D Endpoint Ready: …
```

Add Dependent when dependency added

---

src/MassTransit/DependencyInjection/DependencyInjection/BusInstanceBuilder.cs

For the DI container I am using it has the ability to specify constructor arg values by name (name of the cstr arg). There seems to be some code that tries to read the parameter name in a unguarded way and throws a null ref if is null.
Its only going to be null in one of these weird code generation scenarios. When using multibus a type gets created and the constructor arg has no name.
I appreciate supporting every DI container isn't your problem but its a one line fix that simply defines a name for the generated constructor parameter name. 
I have tested this by changing my project that errored on startup while referencing MT 8.0.3 nuget libraries to instead reference the projects in source directly (with the fix). The multibus project now starts normally.

set cstr arg name on dynamic type

---

src/MassTransit.Abstractions/Attributes/ExcludeFromConfigureEndpointsAttribute.cs
src/MassTransit.Abstractions/Configuration/DependencyInjection/IActivityRegistrationConfigurator.cs
src/MassTransit.Abstractions/Configuration/DependencyInjection/IConsumerRegistrationConfigurator.cs
src/MassTransit.Abstractions/Configuration/DependencyInjection/IExecuteActivityRegistrationConfigurator.cs
src/MassTransit/Configuration/DependencyInjection/IFutureRegistrationConfigurator.cs
src/MassTransit/Configuration/DependencyInjection/ISagaRegistrationConfigurator.cs
src/MassTransit/Configuration/DependencyInjection/RegistrationConfiguratorExtensions.cs
src/MassTransit/DependencyInjection/Configuration/BusRegistrationContext.cs
src/MassTransit/DependencyInjection/Configuration/IRegistration.cs
src/MassTransit/DependencyInjection/Configuration/RegistrationConfigurator.cs
src/MassTransit/DependencyInjection/Configuration/RegistrationContext.cs
src/MassTransit/DependencyInjection/DependencyInjection/Registration/Activites/ActivityRegistration.cs
src/MassTransit/DependencyInjection/DependencyInjection/Registration/Activites/ActivityRegistrationConfigurator.cs
src/MassTransit/DependencyInjection/DependencyInjection/Registration/Activites/ExecuteActivityRegistration.cs
src/MassTransit/DependencyInjection/DependencyInjection/Registration/Activites/ExecuteActivityRegistrationConfigurator.cs
src/MassTransit/DependencyInjection/DependencyInjection/Registration/Consumers/ConsumerRegistration.cs
src/MassTransit/DependencyInjection/DependencyInjection/Registration/Consumers/ConsumerRegistrationConfigurator.cs
src/MassTransit/DependencyInjection/DependencyInjection/Registration/Endpoints/EndpointRegistration.cs
src/MassTransit/DependencyInjection/DependencyInjection/Registration/Futures/FutureRegistration.cs
src/MassTransit/DependencyInjection/DependencyInjection/Registration/Futures/FutureRegistrationConfigurator.cs
src/MassTransit/DependencyInjection/DependencyInjection/Registration/Sagas/SagaRegistration.cs
src/MassTransit/DependencyInjection/DependencyInjection/Registration/Sagas/SagaRegistrationConfigurator.cs
src/MassTransit/DependencyInjection/DependencyInjection/Registration/Sagas/SagaStateMachineRegistration.cs
src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaProducerRegistration.cs
tests/MassTransit.Containers.Tests/ExcludeFromConfigureEndpoints_Specs.cs

Exclude components either with `.ExcludeFromConfigureEndpoints()` or `[ExcludeFromConfigureEndpoints]` attribute

Add ability to exclude components from ConfigureEndpoints

---

src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/InboxCleanupService.cs

The logger definition for the InboxCleanupService was referring to BusOutboxDeliveryService

EF InboxCleanupService logger type fix

---

doc/content/3.documentation/5.configuration/integrations/1.signalr.md

Hey,
I added some additional documentation for the SignalR integration, especially things I wished were a bit clearer when I initially started using it:
- I added further explanation for the specific differences each SignalR message envelope has
- Added some information as to how exceptions or missing IDs are handled
- Added a rough outline of how the flow of the message looks like, from publisher to client
- Added a slightly more complex example to showcase how a Group message would look like
- Added a hint as to why it makes sense to add a marker interface

SignalR documentation improvements

---

src/MassTransit.SignalR/Consumers/AllConsumer.cs
src/MassTransit.SignalR/Consumers/GroupConsumer.cs
tests/MassTransit.SignalR.Tests/HubLifeTimeManagerTests.cs

- Changed excluded connection id comparisons in AllConsumer and GroupConsumer to Ordinal in order to be in line with the behaviour of a direct connection Consumer
- Added tests to verify that the casing behaves as expected

SignalR ExcludedConnection Casing

---

src/MassTransit/Configuration/DefaultEndpointNameFormatter.cs

This is a starting point for the proposal in https://github.com/MassTransit/MassTransit/discussions/4141
Idea is to make various members protected and virtual to allow better customizations as described in the discussions.

Open up extensibility of DefaultEndpointNameFormatter

---

src/MassTransit/Courier/RoutingSlipResponseProxy.cs

Very small change here creates an endpoint for `Fault<TRequest>` instead of `Fault<TResponse>`. I based similar code to handle compensation failures on this and my faults were never being handled. Just skipped. Changing to TRequest resolved it.

bug - response should be Fault<TRequest>

---

src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaTopicReceiveEndpointConfiguration.cs

- set the _offsetsCommittedHandler property with the parameter value instead of itself.
Calling the SetOffsetsCommittedHandler on (IKafkaFactoryConfigurator.)TopicEndpoint with any handler results to an ArgumentNullException.
Same call doesn't trigger the exception anymore.

Fix ArgumentNullException when using SetOffsetsCommittedHandler

---

.devcontainer/devcontainer.json

Create a dev container spec. This allows users to create Codespaces directly on GitHub, or to use VS Code and the Dev Containers plug-in to have a pre-configured container automatically created that is ready to develop in.

Create Dev Container

---

src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/PostgresLockStatementFormatter.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/PostgresLockStatementProvider.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/SqlLockStatementProvider.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/SqlServerLockStatementFormatter.cs
src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/SqlServerLockStatementProvider.cs

Fixed #4222
Entity Framework generates an SQL script without the schema if it has not been explicitly specified. The behavior of LockStatementFormatter when generating SQL instructions should be the same. Therefore, it is not necessary to explicitly pass the schema to the SqlLockStatementProvider:
- If the schema is not specified (empty or null), then LockStatementFormatter will not add it to the SQL and the default schema in the database will be used or the schema specified in the connection string.
- If the schema has been explicitly specified in the modelBuilder, it will be obtained from the EntityType and passed to LockStatementFormatter.
However, I left the DefaultSchema parameter in SqlLockStatementProvider to avoid breaking the existing API.

Fix default schema in SqlLockStatementProvider

---

doc/content/3.documentation/1.concepts/1.messages.md
doc/content/3.documentation/5.configuration/5.topology/1.message.md
src/MassTransit.Abstractions/Attributes/MessageUrnAttribute.cs
src/MassTransit.Abstractions/MessageUrn.cs
tests/MassTransit.Tests/MessageUrnSpecs.cs

MassTransit provides an opinionated `MessageUrn` class which is used to identify the types for a message during serialization/deserialization. 80% of the time or more I am certain this is sufficient for most users of Mass Transit.
In our scenario we have many services publishing and subscribing to messages, some are dotnet implementations using MassTransit, others are consumers operating in different contexts.  We'd like to uniformly apply a naming convention that is not bound to a specific toolchain implementation.  By restricting the `MessageUrn` to be derived from a namespace, this feels like a leaking of an implementation detail of the message producer, while the consumer should only be held to the contract of the message.
This PR adds a `MessageUrnAttribute` that may be added to a …

feat: add MessageUrnAttribute to support customization of message urn resolution

---

src/MassTransit.Abstractions/Configuration/Middleware/IReceiveEndpointConfigurator.cs
src/MassTransit.Abstractions/Configuration/Middleware/IReceiveEndpointDependencyConnector.cs
src/MassTransit.Abstractions/Configuration/Middleware/IReceiveEndpointDependentConnector.cs
src/MassTransit.Abstractions/Configuration/Middleware/ReceiveEndpointConfiguratorDependencyExtensions.cs
src/MassTransit/Configuration/Configuration/IReceiveEndpointConfiguration.cs
src/MassTransit/Configuration/Configuration/ReceiveEndpointConfiguration.cs
src/MassTransit/Configuration/Configuration/ReceiverConfiguration.cs
src/MassTransit/Middleware/ReceiveEndpointDependencyFilter.cs
src/MassTransit/Transports/ReceiveTransport.cs
src/MassTransit/Transports/TransportStartExtensions.cs
src/Transports/MassTransit.ActiveMqTransport/ActiveMqTransport/Configuration/ActiveMqReceiveEndpointConfiguration.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/Configuration/AmazonSqsReceiveEndpointConfiguration.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/Configuration/ServiceBusEntityReceiveEndpointConfiguration.cs
src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/Configuration/EventHubReceiveEndpointConfigurator.cs
src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaTopicReceiveEndpointConfiguration.cs
src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/Configuration/RabbitMqReceiveEndpointConfiguration.cs
tests/MassTransit.Containers.Tests/ReceiveEndpointDependency_Specs.cs

Stopping log with 5sec delay for Stop Completed (to make it visible in logs) for: https://github.com/MassTransit/MassTransit/blob/252aa619a381f778b9f1a55952c5958639a80d8d/tests/MassTransit.Tests/JobConsumer_Specs.cs#L49
```bash
13:16:17.163-D Job Service Instance Stopped: loopback://localhost/instance-pywoyyg6ww5pdhu6bdpudap3f9
13:16:17.163-D RECEIVE loopback://localhost/job-type 68290000-dea5-36d1-cad2-08db31e1baa1 MassTransit.Contracts.JobService.SetConcurrentJobLimit MassTransit.JobTypeSaga(00:00:00.0002460)
13:16:17.164-D Stopping bus: loopback://localhost/
13:16:17.167-D Endpoint Stopping: loopback://localhost/odd-job
13:16:17.167-D Consumer Stopping: loopback://localhost/odd-job (Stop Receive Transport)
13:16:17.170-D Endpoint Stopping: loopback://localhost/odd-job-completed …
```

Use ReceiveEndpointDependencyFilter to manage dependencies

---

doc/content/3.documentation/1.concepts/5.requests.md

Strings in C# should be in **double** quotes.

Fix typo in request documentaiton

---

src/MassTransit.Abstractions/Contexts/TimeSpanContextScheduleExtensions.cs
src/MassTransit.Abstractions/Contexts/TimeSpanScheduleExtensions.cs
src/MassTransit.Abstractions/Contexts/TimeSpanSchedulePublishExtensions.cs

This pull request introduces new `ScheduleSend` and `SchedulePublish` extension methods for `MessageSchedulerContext`, `IMessageScheduler`, and `IMessageScheduler` constructs. This update ensures uniformity between scheduled and [unscheduled](https://github.com/MassTransit/MassTransit/blob/develop/src/MassTransit.Abstractions/Contexts/SendExecuteExtensions.cs) message sending methods.
It also aligns the scheduled senders with the Message Correlation configuration documentation for consistency.

Added `Action` and `Func` SendContext overloads for ScheduleSend and SchedulePublish

---

src/Persistence/MassTransit.Azure.Cosmos/AzureCosmos/NewtonsoftJsonCosmosClientFactory.cs
src/Persistence/MassTransit.Azure.Cosmos/AzureCosmos/SystemTextJsonCosmosClientFactory.cs
src/Persistence/MassTransit.Azure.Cosmos/Configuration/Configuration/CosmosSagaRepositoryConfigurator.cs
src/Persistence/MassTransit.Azure.Cosmos/Configuration/CosmosRepositoryConfigurationExtensions.cs

I added the possibility to set the `CosmosClientOptions` while configuring Cosmos as a repository. Many properties were not exposed until now and we were not able to configure them (https://learn.microsoft.com/fr-fr/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions?view=azure-dotnet#properties).

Allow to set the CosmosClientOptions

---

Directory.Packages.props
tests/MassTransit.BenchmarkConsole/MassTransit.BenchmarkConsole.csproj
tests/MassTransit.BenchmarkConsole/MediatorBenchmark.cs

still working:
|      Method |         Mean |        Error |       StdDev |    Gen0 |   Gen1 | Allocated |
|------------ |-------------:|-------------:|-------------:|--------:|-------:|----------:|
|      Direct |     12.81 ns |     0.147 ns |     0.130 ns |  0.0153 | 0.0000 |      32 B |
|     MediatR |    237.40 ns |     3.216 ns |     2.851 ns |  0.1297 | 0.0005 |     272 B |
| MassTransit |  1,697.75 ns |    20.726 ns |    19.387 ns |  1.4763 |      - |    3088 B |
| InMemoryBus | 78,391.04 ns | 1,406.559 ns | 1,174.541 ns | 17.5781 |      - |   36462 B |

Upgrading MediatR for benchmark

---

src/Persistence/MassTransit.MongoDbIntegration/Configuration/MongoDbOutboxConfigurationExtensions.cs

I kept noticing this error in summary documentation so decided to just fix it.
Thanks for a phenomenal framework.

chore: fix incorrect entity framework reference in mongo db summary documentation

---

src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaBaseReceiveContext.cs

Hi All!
This PR simply adds `MessageBody` on ReceiveContext for Kafka Transport instead of throw a `NotSupportedMessageBody`.
With this change we will be able to retrieve the message that come from topic that can be useful in some cases. 
Currently, the only way that I found was use Reflection to extract the message from `_result` property and with this PR I will be able to remove this ugly part of code from my project (rs).

feat: support MessageBody on ReceiveContext for Kafka Transport

---

src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Configuration/EntityFrameworkOutboxConfigurationExtensions.cs

This allows setting up the entities from IEntityTypeConfiguration<> implementations for those who don't want to define them in the db context itself

Extract ef core outbox entity configs to separate extension methods

---

src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/Batcher.cs
src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/Checkpoints/BatchCheckpointer.cs
src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Checkpoints/BatchCheckpointer.cs
src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/BatchPublisher.cs
tests/MassTransit.RabbitMqTransport.Tests/Publish_Specs.cs

Batch publishers should gather as many messages as possible before waiting for new messages.
This should make it slightly more likely for batch limits to be filled.
* Only waits for new messages if there are none available
* Always checks batch limits (count/size) before waiting for new messages (allows for 0ms timeouts)

Update batch publishing to collect messages before waiting

---

src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/RabbitMqBasicConsumer.cs
tests/MassTransit.RabbitMqTransport.Tests/ConcurrencyFilter_Specs.cs

This is an implementation proposal to support for RabbitMQ consumer to process messages sequentially when PrefetchCount is set to 0 or 2+ and `RabbitMqReceiveEndpointContext.ConcurrentMessageLimit` is set to 1 to avoid concurrent message processing.
In some scenario, such capability can be useful. 
See the integration test `Using_a_consumer_concurrency_limit_set_to_1.Should_limit_the_consumer_and_consume_messages_sequentially()` method for a concrete example.
Here is a visual summary of the change:

RabbitMQ Basic Consumer support for sequential processing with ConcurrentMessageLimit = 1

---

src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/ConnectionContextFactory.cs

For Azure Service Bus transport,  MassTransit allows the Retry setting of ServiceBusClientOptions to be customized via host settings, However, in Azure Service Bus SDK, ServiceBusAdministrationClient also has its own ServiceBusAdministrationClientOptions and retry settings and MassTransit does not set those options.
On the other hand, MassTransit is using  ServiceBusAdministrationClient  for send and publish, as it checks if the queue does not exist to be created. 
So, when sending or publishing a message and there is a connection problem, Azure Service Bus always uses the default retry setting not what is set by MassTransit in host settings.
This this was discussed here:
https://github.com/MassTransit/MassTransit/discussions/4480

Setting Azure ServiceBusAdministrationClientOptions

---

src/MassTransit/Logging/Diagnostics/LogContextActivityExtensions.cs
tests/MassTransit.HangfireIntegration.Tests/HangfirePublish_Specs.cs

Adds parent activity context checks to `send` and `outbox send` activities. This fixed an issue where scheduled messages (experienced this through Hangfire) do not inherit the original trace ID.
This shows what happens when a message is scheduled in develop:
Scheduled send is shown as a different trace.
After fix: scheduled send is included in parent trace after the delay:

Get parent activity context for send and outbox send activities

---

doc/content/3.documentation/3.patterns/8.claim-check.md

The comment is a bit confusing
Default value for AlwaysWriteToRepository is true
https://github.com/MassTransit/MassTransit/blob/develop/src/MassTransit.Abstractions/MessageData/MessageDataDefaults.cs

Default value for AlwaysWriteToRepository correction in doc

---

src/Transports/MassTransit.RabbitMqTransport/Configuration/RabbitMqSslOptions.cs
src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/Configuration/ConfigurationHostSettings.cs
src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/Configuration/RabbitMqHostConfigurator.cs
src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/Configuration/RabbitMqRegistrationBusFactory.cs

Related to #4522, this commit exposes an option from the existing `RabbitMqSslOptions` to allow users to explicitly set a specific `SslProtocols` value per multi-bus instance (e.g. for cases where multi-bus instances point to different clusters with differing security requirements).
See: #4522
___
> **Note**
> _I'd very much like to contribute some tests for this, but I'm not quite sure where to start, so opening this for consideration/discussion before I go much further._

Expose `RabbitMqSslOptions.Protocol` option

---

src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/RabbitMqAddressExtensions.cs

Fix #4568 by avoiding calling Clear() on the AuthMechanisms for RabbitMq transport

Fix #4568 by avoiding calling Clear() on the AuthMechanisms for RabbitMq transport

---

Directory.Packages.props
src/Persistence/MassTransit.MartenIntegration/Configuration/MartenSagaRepositoryRegistrationExtensions.cs
src/Persistence/MassTransit.MartenIntegration/MartenIntegration/Saga/MartenSagaRepositoryContextFactory.cs
src/Persistence/MassTransit.MartenIntegration/MassTransit.MartenIntegration.csproj
tests/MassTransit.MartenIntegration.Tests/MassTransit.MartenIntegration.Tests.csproj
tests/MassTransit.MartenIntegration.Tests/SagaPersistenceTests.cs
tests/MassTransit.MartenIntegration.Tests/TwoSaga_Specs.cs

This PR updates Marten to the latest major and minor version. (6.0.5)
- OpenSession was deprecated in favour of using a named session type, LightSession being the prefered.
- Schema was removed on document session with methods being moved to storage.
=======================================================
- Marten dropped support for legacy .NET framework, as well as .net standard, so the change unfortunately means MT would also have to drop support for them, meaning MassTransit.Marten would have TargetFrameworks net6 and net7 only.
- Fixes the ability to add MassTransit.Marten to a solution which references NpgSql 7.
5.11.0 had a dependency on Weasel which in turn had a package version constraint of '< 7.0' so would throw an error without explicitly referencing assemblies yourself, …

Update to latest version of Marten [Breaking]

---

doc/content/3.documentation/5.configuration/0.index.md

As per:
https://masstransit.io/documentation/configuration#endpoint-name-formatters
But the class has a bool param:
https://github.com/MassTransit/MassTransit/blob/9a6916d681b3601a3ff8b4830027d34a6a05fb93/src/MassTransit/Configuration/KebabCaseEndpointNameFormatter.cs#L28
I did a copy and past to my code and it didn't compile. 
Fix the doc to prevent that happened to next person googling the issue.

Update configure documentation for Kebab formater

---

src/MassTransit/Logging/Diagnostics/LogContextActivityExtensions.cs

Currently, MassTransit's activity source does not include its version, so OTel traces will not show the `otel.library.version` tag:
After this change, the `Version` tag will be filled:

Add MT version to ActivitySource

---

src/MassTransit/Logging/Diagnostics/DiagnosticHeaders.cs

While going through some opentelemetry config with MassTransit, noticed the BodyLength diagnostics property has a typo compared to the default spec at https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/messaging/#messaging-attributes

Correct body length message attribute name

---

src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaMessageConsumer.cs

Wrap consumer close/dispose into try/catch as they might result in unhandled exception
related to: https://github.com/MassTransit/MassTransit/issues/4699#issuecomment-1774042735

Wrap consumer close into try/catch

---

src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/AmazonSqsClientContext.cs

Currently, the AWS SQS transport creates queue access policies that are overly permissive and allow for any topic within the AWS owner account to send messages to a created queue. This PR removes wild-card conditions within a created queue's access policy and instead uses the complete ARN information available about the appropriate SNS topic.
These changes should also be backward compatible for queues that have already been created with wild-carded `aws:SourceArn`s as it takes that into account when determining if existing queues already permit the topic to send messages to the queue.
```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Principal": {
"AWS": "*"
},
"Action": "sqs:SendMessage",
"Resource": "arn:aws:sqs:<region>:<account id>:<queue name>",
"Condition": { …
```

Updated AWS SQS queue access policy to be less permissive

---

doc/content/3.documentation/1.concepts/2.consumers.md

Fixed a link on the Concepts -> Consumers page that pointed to `/documentation/configuration/bus/consumers` instead of `/documentation/configuration/consumers`

Fix "AddConsumer" link in concepts documentation

---

doc/content/3.documentation/2.configuration/0.index.md
src/MassTransit/Configuration/DependencyInjection/IHealthCheckOptionsConfigurator.cs
src/MassTransit/DependencyInjection/Configuration/IHealthCheckOptions.cs
src/MassTransit/DependencyInjection/Configuration/MassTransitHealthCheckOptions.cs
src/MassTransit/Monitoring/BusHealthCheck.cs
src/MassTransit/Monitoring/ConfigureBusHealthCheckServiceOptions.cs

This PR adds a new property to options, `MinimalFailureStatus`. This property affects minimal level that will be reported by MassTransit health check.
Also some additional information about configuring health checks was added to documentation.
Closes #4787.
`FailureStatus` property is now deprecated. It didn't affect anything earlier because it wasn't used, so migrating to a new property should be simple.
- Deprecated `FailureStatus` property
- Added `MinimalFailureStatus` property
- Modified `BusHealthCheck.CheckHealthAsync`. Now it uses `HealthCheckContext.Registration.FailureStatus` as minimal reported health level
- Updated  `Configuration/Health Checks` documentation.
I used my project from issue to test the new behaviour of health checks. If I don't set `MinimalFailureStatus`, then …

Fix: MassTransit ignores IHealthCheckOptionsConfigurator.FailureStatus value despite allowing it to be set

---

src/MassTransit/Serialization/SystemTextJsonMessageSerializer.cs
src/MassTransit/Serialization/SystemTextJsonSerializationContext.cs

Use System.Text.Json source generator to improve performance. This also allows applications that use MT to disable serialization via reflection (https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-8#disabling-reflection-defaults) by configuring the `JsonSerializerOptions` to add their own `JsonSerializerContext` (for their own messages) like:
```cs
services.AddMassTransit(cfg =>
{
cfg.Using[Broker](broker => 
{
broker.ConfigureJsonSerializerOptions(options =>
{
options.TypeInfoResolverChain.Insert(0, AppJsonSerializerContext.Default);
return options;
});
})
})
[JsonSerializable(typeof(CreateTodoCommand))]
[JsonSerializable(typeof(OrderPublishedEvent))]
internal partial class AppJsonSerializerContext : JsonSerializerContext
{
}
```
This PR depends on #4791.

Enable System.Text.Json source generator

---

src/Transports/MassTransit.RabbitMqTransport/Configuration/IRabbitMqHostConfigurator.cs
src/Transports/MassTransit.RabbitMqTransport/Configuration/RabbitMqTransportOptions.cs
src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/Configuration/RabbitMqHostConfigurator.cs
src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/Configuration/RabbitMqRegistrationBusFactory.cs

MassTransit allows setting a custom connection name for RabbitMQ connections, using the constructors in `RabbitMqHostConfigurator`:
https://github.com/MassTransit/MassTransit/blob/7f8220b9b5d805b301941b06805f06e37e43c447/src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/Configuration/RabbitMqHostConfigurator.cs#L12
Or one of the overloads in `RabbitMqHostConfigurationExtensions`:
https://github.com/MassTransit/MassTransit/blob/7f8220b9b5d805b301941b06805f06e37e43c447/src/Transports/MassTransit.RabbitMqTransport/Configuration/RabbitMqHostConfigurationExtensions.cs#L43-L45
However there is no way to access this setting using either the configuration methods, or using the options pattern. There is no method to set it in …

Add missing configuration for RabbitMQ connection name

---

src/Persistence/MassTransit.RedisIntegration/Configuration/Configuration/RedisSagaRepositoryConfigurator.cs
src/Persistence/MassTransit.RedisIntegration/Configuration/IRedisSagaRepositoryConfigurator.cs
src/Persistence/MassTransit.RedisIntegration/Configuration/RedisSagaRepositoryOptions.cs
src/Persistence/MassTransit.RedisIntegration/RedisIntegration/Saga/RedisSagaRepository.cs

Hello Chris,
I get struck with 918 millisecs when redis get locked. I found that retry policy was hard coded with Retry.Exponential(10, TimeSpan.FromMilliseconds(100), TimeSpan.FromSeconds(10), TimeSpan.FromMilliseconds(918)) 
I would like to override this retry policy when call RedisSagaRepository.  Is it possible to do this?

Add function to overide retry policy when adding redis saga repository

---

src/MassTransit.TestFramework/MassTransit.TestFramework.csproj
tests/MassTransit.DapperIntegration.Tests/Container_Specs.cs
tests/MassTransit.DapperIntegration.Tests/DapperSagaRepositoryTests.cs
tests/MassTransit.EntityFrameworkCoreIntegration.Tests/FutureSagaDbContextFactory.cs
tests/MassTransit.EntityFrameworkCoreIntegration.Tests/ReliableMessaging/Outbox_Specs.cs
tests/MassTransit.EntityFrameworkCoreIntegration.Tests/ReliableMessaging/ReliableDbContextFactory.cs
tests/MassTransit.EntityFrameworkCoreIntegration.Tests/Shared/SqlServerResiliencyTestDbParameters.cs
tests/MassTransit.EntityFrameworkCoreIntegration.Tests/Shared/SqlServerTestDbParameters.cs
tests/MassTransit.EntityFrameworkCoreIntegration.Tests/TransactionalBusOutbox_Specs.cs
tests/MassTransit.EntityFrameworkIntegration.Tests/AuditStore_Specs.cs
tests/MassTransit.EntityFrameworkIntegration.Tests/Container_Specs.cs
tests/MassTransit.EntityFrameworkIntegration.Tests/DiscardEvent_Specs.cs
tests/MassTransit.EntityFrameworkIntegration.Tests/PreInsert_Specs.cs
tests/MassTransit.EntityFrameworkIntegration.Tests/SagaLocator_Specs.cs
tests/MassTransit.EntityFrameworkIntegration.Tests/UsingEntityFrameworkConcurrencyFail_Specs.cs
tests/MassTransit.EntityFrameworkIntegration.Tests/UsingEntityFrameworkConcurrencyOptimistic_Specs.cs
tests/MassTransit.EntityFrameworkIntegration.Tests/UsingEntityFrameworkConcurrencyPessimistic_Specs.cs
tests/MassTransit.EntityFrameworkIntegration.Tests/UsingEntityFramework_Specs.cs
tests/MassTransit.SqlTransport.Tests/MassTransit.SqlTransport.Tests.csproj
tests/MassTransit.SqlTransport.Tests/SqlServerDatabaseTestConfiguration.cs
tests/MassTransit.Tests/LocalDbConnectionStringProvider.cs
tests/MassTransit.Tests/MassTransit.Tests.csproj

`Microsoft.Data.SqlClient`  probably shouldn't be a core dependency for testing MassTransit solutions. It also has [a funny transitive license](https://github.com/dotnet/SqlClient/issues/790) via `Microsoft.Data.SqlClient.SNI.runtime` that can make alarm bells go off with some dependency scanners which check licenses. 
There's only `LocalDbConnectionStringProvider` which causes the dependency so I'm suggesting moving it to `MassTransit.Tests` as it's only needed by MassTransit's own tests, I'm open for better ideas of course.

Remove Microsoft.Data.SqlClient dependency from TestFramework

---

doc/content/3.documentation/1.concepts/1.messages.md

- An anchor link had a double hash symbol leading to a disconnect in reading when clicking the link, since the user doesn't land on the intended spot on the page.

Fix anchor link typo in 1.concepts/1.messages.md

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/nightly-transports.yml

Becaues GitHub actions will stop supporting node 16 based actions, the actions will need to be upgraded to node 20 based ones. This commit upgrades setup-dotnet@v3 to setup-dotnet@v4 and checkout@v3 to checkout@v4 in the workflow files.

upgrades actions in build workflow

---

src/MassTransit/MassTransit.csproj

Reflection.Emit is inbox in all frameworks other than .NET Standard 2.0.

Reduce dependencies on non-.NET Standard 2.0.

---

src/MassTransit.Abstractions/JobService/Contracts/JobService/JobStarted.cs
src/MassTransit/JobService/JobService/StartJobConsumer.cs
tests/MassTransit.ActiveMqTransport.Tests/JobConsumer_Specs.cs
tests/MassTransit.Azure.Cosmos.Tests/JobConsumer_Specs.cs
tests/MassTransit.Azure.Table.Tests/JobConsumer_Specs.cs
tests/MassTransit.EntityFrameworkCoreIntegration.Tests/JobConsumer_Specs.cs
tests/MassTransit.MongoDbIntegration.Tests/JobConsumer_Specs.cs
tests/MassTransit.RabbitMqTransport.Tests/JobConsumer_Specs.cs
tests/MassTransit.SqlTransport.Tests/JobConsumer_Specs.cs
tests/MassTransit.Tests/JobConsumer_Specs.cs

adds a `JobStarted<T>` contract, similar to `JobCompleted<T>` which is published after a job starts, it'll be useful in state machines where multiple jobs start events need to be tracked. Specifically so that the generic `JobStarted<T>` can be tracked without needing to create custom message contracts that would need to be published in each individual job consumer.

feat: add JobStarted<T> which is published after the job starts

---

doc/content/3.documentation/1.concepts/4.exceptions.md

First doc change:
(maybe this should be in a danger alert component?
Second:

Add extra docs for  UseMessageRetry, UseDelayedRedelivery, UseScheduledRedelivery

---

src/MassTransit/Configuration/JobOptions.cs
src/MassTransit/JobService/JobService/ConsumerJobHandle.cs
src/MassTransit/JobService/JobService/IJobService.cs
src/MassTransit/JobService/JobService/JobService.cs
src/MassTransit/JobService/JobService/StartJobConsumer.cs

Add a possibility to configure the timeout within which the long-running job consumer can be fully cancelled or the current work finished. Previously it was hard coded as 30 seconds.

Configure the cancellation timeout for the IJobConsumer

---

src/Transports/MassTransit.SqlTransport.SqlServer/SqlTransport/SqlServer/SqlServerDatabaseMigrator.cs

In [SqlServerDatabaseMigrator.CreateDatabaseIfNotExist](https://github.com/MassTransit/MassTransit/blob/2ac69e8c877c9f255cc4eb047c4830898f78711b/src/Transports/MassTransit.SqlTransport.SqlServer/SqlTransport/SqlServer/SqlServerDatabaseMigrator.cs#L1354) the SQL connection is made by connecting to the `master` database with [SqlServerSqlTransportConnection.GetSystemDatabaseConnection](https://github.com/MassTransit/MassTransit/blob/2ac69e8c877c9f255cc4eb047c4830898f78711b/src/Transports/MassTransit.SqlTransport.SqlServer/SqlTransport/SqlServer/SqlServerSqlTransportConnection.cs#L49).
When then checking for the existence of the database with [SqlServerDatabaseMigrator.DbExistsSql](https://github.com/MassTransit/MassTransit/blob/2ac69e8c877c9f255cc4eb047c4830898f78711b/src/Transports/MassTran …

SQL Transport DbExists, support Azure SQL

---

src/MassTransit/SqlTransport/Configuration/SqlTransportMigrationOptions.cs
src/MassTransit/SqlTransport/SqlTransport/ISqlTransportDatabaseMigrator.cs
src/MassTransit/SqlTransport/SqlTransport/SqlTransportMigrationHostedService.cs
src/Transports/MassTransit.SqlTransport.PostgreSql/Configuration/PostgresSqlTransportConfigurationExtensions.cs
src/Transports/MassTransit.SqlTransport.PostgreSql/SqlTransport/PostgreSql/PostgresDatabaseMigrator.cs
src/Transports/MassTransit.SqlTransport.SqlServer/Configuration/SqlServerDbTransportConfigurationExtensions.cs
src/Transports/MassTransit.SqlTransport.SqlServer/SqlTransport/SqlServer/SqlServerDatabaseMigrator.cs

This pull request adds an option of only running the infrastructure migrations when utilizing `AddSqlServerMigrationHostedService` or `AddPostgresMigrationHostedService`.
This will support the scenario where the application using MassTransit and the SQL transport does not have system or admin level access to the database.
Concretely we have a production setup where we have created a dedicated database for MassTransit and also created the login, user, schema and role by hand. While all of this is simple for us to do ourselves, we would like to let MassTransit handle the creation of the infrastructure as this a lot more complex.
**Possible backwards compatibility issue**
If anyone has used
```
services.AddSqlServerMigrationHostedService(false, false);
```
they will now experience that the …

Make it possible to run only the infrastructure migrations for the SQL Transport

---

src/Transports/MassTransit.SqlTransport.SqlServer/SqlTransport/SqlServer/SqlServerDatabaseMigrator.cs

Added a surrounding brackets on database name, otherwise if you have a database containing for instance '-', then you will get the following error message: `Incorrect syntax near '-'`

Encapsulate database name with brackets

---

src/MassTransit.Abstractions/Contexts/TimeSpanContextScheduleExtensions.cs
src/MassTransit.Abstractions/Contexts/TimeSpanScheduleExtensions.cs
src/MassTransit.Abstractions/Contexts/TimeSpanSchedulePublishExtensions.cs
src/MassTransit.Abstractions/IPublishEndpoint.cs
src/MassTransit.Abstractions/ISendEndpoint.cs
src/MassTransit.Abstractions/SchedulePublishExtensions.cs
src/MassTransit.Abstractions/Scheduling/ConsumeContextSchedulerExtensions.cs
src/MassTransit.Abstractions/Scheduling/ConsumeContextSelfSchedulerExtensions.cs
src/MassTransit.Abstractions/Scheduling/IMessageScheduler.cs
src/MassTransit.Abstractions/Scheduling/IRecurringMessageScheduler.cs
src/MassTransit.Abstractions/Scheduling/MessageSchedulerContext.cs

I just noticed that several methods that refer to a specified message type in the summary (warning about an exception being thrown if the message could not be casted to the message type) actually didn't have a message type parameter.
I updated the summaries for those cases. I removed the mention of casting, assuming that there isn't a concern for that for these methods.

Fix summaries of methods referring to message type while no messageType parameter is available

---

doc/content/3.documentation/2.configuration/0.index.md

Resolves startup error:
> System.InvalidOperationException: 'EndpointRoutingMiddleware matches endpoints setup by EndpointMiddleware and so must be added to the request execution pipeline before EndpointMiddleware. Please add EndpointRoutingMiddleware by calling 'IApplicationBuilder.UseRouting' inside the call to 'Configure(...)' in the application startup code.'
Not sure about the behavior. I don't get the documented json output on those urls but the endpoints to return `Healthy`.
This is with:
<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.6" />

Fixes `EndpointRoutingMiddleware matches endpoints setup by EndpointMiddleware...`

---

src/Transports/MassTransit.SqlTransport.PostgreSql/SqlTransport/PostgreSql/Helpers/NotifyChannel.cs
src/Transports/MassTransit.SqlTransport.PostgreSql/SqlTransport/PostgreSql/PostgresDatabaseMigrator.cs
src/Transports/MassTransit.SqlTransport.PostgreSql/SqlTransport/PostgreSql/PostgresDbConnectionContext.cs
tests/MassTransit.SqlTransport.Tests/PgSql/ChannelName_Specs.cs

Hi @phatboyg 
I found an issue with the Listen (postgres) notifications part where the schema is hardcoded to be "transport"
Since it is allowed to have a different schema that is passed via options and the PostgresDatabaseMigrator uses it for creating the trigger script, we should have it aligned in the C# code.
PostgresDatabaseMigrator:
https://github.com/MassTransit/MassTransit/blob/41ea46fcb5421e892b81d38e9629e3ed39d8ad53/src/Transports/MassTransit.SqlTransport.PostgreSql/SqlTransport/PostgreSql/PostgresDatabaseMigrator.cs#L848
vs PostgresDbConnectionContext:
https://github.com/MassTransit/MassTransit/blob/41ea46fcb5421e892b81d38e9629e3ed39d8ad53/src/Transports/MassTransit.SqlTransport.PostgreSql/SqlTransport/PostgreSql/PostgresDbConnectionContext.cs#L203

SqlTransport -> Use configured schema when listening to notifications

---

src/MassTransit/Util/ChannelExecutor.cs
src/MassTransit/Util/TaskExecutor.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/Batcher.cs

- Adding prefetch option for TaskExecutor
- Replace usage of ChannelExecutor completely

Migrate to TaskExecutor

---

Directory.Build.props
Directory.Packages.props
src/MassTransit.Abstractions/Contexts/RespondAsyncExecuteExtensions.cs
src/Scheduling/MassTransit.QuartzIntegration/MassTransit.QuartzIntegration.csproj
src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/Configuration/RabbitMqSslConfigurator.cs
tests/MassTransit.EntityFrameworkCoreIntegration.Tests/ReliableMessaging/QuartzOutbox_Specs.cs
tests/MassTransit.QuartzIntegration.Tests/Container_Specs.cs

https://github.com/quartznet/quartznet/releases/tag/v3.12.0
* remove promotion of Quartz's Newtonsoft based `Quartz.Serialization.Json`, users ideally could add  `Quartz.Serialization.SystemTextJson` themselves if they want to use JSON serializer
* remove unused `Quartz.Plugins.TimeZoneConverter`, users can add if they need it
* fix XML doc comments
* remove unnecessary compiler warnings suppression
* remove usage of obsolete `UseMicrosoftDependencyInjectionJobFactory`

Upgrade Quartz to version 3.12.0

---

.github/workflows/build.yml
Directory.Packages.props

I'm proposing to use [GitHubActionsTestLogger](https://github.com/Tyrrrz/GitHubActionsTestLogger), which will create[ nice summaries](https://github.com/MassTransit/MassTransit/actions/runs/10229746155?pr=5384) and easier to find test failures instead of the need to browse trough build's console logs.

Use GitHubActionsTestLogger

---

src/Persistence/MassTransit.RedisIntegration/Configuration/Configuration/ConnectionMultiplexerFactory.cs
src/Persistence/MassTransit.RedisIntegration/Configuration/Configuration/RedisSagaRepositoryConfigurator.cs
src/Persistence/MassTransit.RedisIntegration/Configuration/IConnectionMultiplexerFactory.cs

Azure provides an SDK Extension method to support Managed Identity Credentials authentication when using the Azure Redis instances: [Microsoft.Azure.StackExchangeRedis](https://github.com/Azure/Microsoft.Azure.StackExchangeRedis)
This is not possible to use with the MassTransit.RedisIntegration - due to the fact that Redis ConfigurationOptions is parsed to a string before connecting with the ConnectionMultiplexerFactory.
Use of Azure Redis credentials with MassTransit StateMachine
```
x.AddSagaStateMachine<TestStateMachineSaga, TestInstance>()
.RedisRepository(configurator =>
{
var configurationOptions = ConfigurationOptions.Parse("RedisUrl");
configurationOptions.ConfigureForAzureAsync(new AzureCacheOptions { TokenCredential = new DefaultAzureCredential()}).Wait(); …
```

Support Azure Redis with Credentials

---

tests/MassTransit.Benchmark/Dockerfile

This changes are so simple as the title: Updating Dockerfiles from .NET 6 to .NET 8!

fix: MassTransit.Benchmark => Updating from .NET 6 to .NET 8

---

src/Transports/MassTransit.SqlTransport.PostgreSql/SqlTransport/PostgreSql/PostgresDatabaseMigrator.cs

Hi @phatboyg 
With this fix I want to address a permission denied issue that happens when you run the migration script with a PG user that has limited permissions and is not superadmin. This is usually the case for cloud environments such as Azure Database for Postgres - Flexible Server.
Given the script (PostgresDatabaseMigrator.cs)
```
GRANT USAGE ON SCHEMA "{1}" TO "{0}";
ALTER SCHEMA "{1}" OWNER TO "{0}";
GRANT "{0}" TO "{2}";
```
the alter schema command fails with this error: [42501] ERROR: must be able to SET ROLE "transport".
This happens because PG tries to verify if the current user has the permission to set that role but we are giving this permission in the next line.
When the 2 lines are inverted, the permissions are granted correctly and the script succeeds.
Steps to …

Fix order of commands in Postgres migration script to prevent permission denied

---

src/Transports/MassTransit.SqlTransport.SqlServer/SqlTransport/SqlServer/SqlServerDatabaseMigrator.cs

Pull Request for issue: #5413 
"Create user" script throws an error when username contains special characters
Adding square brackets solves the issue:

Fix exception for username with special characters

---

src/Transports/MassTransit.SqlTransport.SqlServer/SqlTransport/SqlServer/SqlServerDatabaseMigrator.cs

When running `CreateDatabase` option in migration, I've encountered an issue in SQL Server in Azure, that object: `sys.syslogins` does not exists.
The workaround is just to set `CreateDatabase` to `false`, but a fix is to use a new name of `syslogins` which is `sql_logins` as per:
URL do doc: https://learn.microsoft.com/en-us/sql/relational-databases/system-tables/mapping-system-tables-to-system-views-transact-sql?view=sql-server-ver16
and important information:
_This SQL Server 2000 system table is included as a view for backward compatibility. We recommend that you use the current SQL Server system views instead. To find the equivalent system view or views, see [Mapping System Tables to System Views (Transact-SQL)](https://learn.microsoft.com/en-us/sql/relational-databases/system-tables/ …

using sql_logins as a replecament for syslogins

---

src/MassTransit/Testing/Implementations/AsyncElementList.cs
src/MassTransit/Transports/Fabric/MessageQueue.cs
src/MassTransit/Util/ChannelExecutor.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/Batcher.cs
src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/Checkpoints/BatchCheckpointer.cs
src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Checkpoints/BatchCheckpointer.cs
src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/BatchPublisher.cs

We are seeing dispose problems sometimes in our integration test suite utilizing test harness and in-memory setup. As the [`Complete` just calls `TryComplete`](https://github.com/dotnet/runtime/blob/5535e31a712343a63f5d7d796cd874e563e5ac14/src/libraries/System.Threading.Channels/src/System/Threading/Channels/ChannelWriter.cs#L70-L76) and throws exception if unsuccessful it feels that having the `Try` version in dispose makes more sense to ensure proper cleanup.
```
TearDown : System.Threading.Channels.ChannelClosedException : The channel has been closed.
StackTrace: --TearDown
at System.Threading.Channels.ChannelWriter`1.Complete(Exception error)
at MassTransit.Util.ChannelExecutor.DisposeAsync() in /_/src/MassTransit/Util/ChannelExecutor.cs:line 63
at …
```

Use ChannelWriter's TryComplete instead of Complete

---

src/MassTransit/Logging/Monitoring/LogContextInstrumentationExtensions.cs

The destination label is missing for `messaging.masstransit.consume.*` metrics.
I added it to all methods that have `DestinationAddress` available.

add missing destination label

---

doc/content/3.documentation/2.configuration/2.transports/3.azure-service-bus.md

Fixed typo in code on the Azure Service Bus configuration page

Fixed typo in code on the Azure Service Bus configuration page

---

src/Transports/MassTransit.SqlTransport.PostgreSql/SqlTransport/PostgreSql/PostgresDbConnectionContext.cs

I noticed that in some of my tests, some queues were not listened correctly.
This happened usually with services that register multiple queues at once and was caused by a foreach loop being interrupted when a queue was already being listened. The loop should continue to the next queue instead of breaking completely.

Fix skipping some queue notification registrations

---

src/Transports/MassTransit.SqlTransport.PostgreSql/SqlTransport/PostgreSql/PostgresSqlHostSettings.cs

@phatboyg 
Currently when `dataSource` is injected into the `BusConfigurator`, the application fails to start with this error, given the `host` is required in the base class `ConfigurationSqlHostSettings`.. 
```
Unhandled exception. MassTransit.ConfigurationException: Host cannot be empty
at MassTransit.SqlTransport.Configuration.ConfigurationSqlHostSettings.FormatHostAddress() in /_/src/MassTransit/SqlTransport/SqlTransport/Configuration/ConfigurationSqlHostSettings.cs:line 107
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
at System.Lazy`1.CreateValue()
at System.Lazy`1.get_Value()
at MassTransit.SqlTransport.Configuration.ConfigurationSqlHostSettings.get_HostAddress() in …
```

Fix: Add Required Base Class props with NpgSqlDataSource Injection 

---

doc/content/3.documentation/3.patterns/10.in-memory-outbox.md

fixes the configuration link redirecting to a 404 page

docs: in-memory outbox configuration link redirecting to 404

---

.gitattributes

Removed `diff=astextplain` as that causes issues in some environments with `git diff` and seems to be a relic from the past.

Removed `diff=astextplain`

---

.github/workflows/build.yml
doc/content/3.documentation/2.configuration/4.persistence/redis.md
tests/MassTransit.RedisIntegration.Tests/docker-compose.yml

Now that the Valkey fork of Redis is getting some good [support from AWS](https://aws.amazon.com/about-aws/whats-new/2024/10/amazon-elasticache-valkey/) I wanted to see if all of our tests passed. 
They do locally! Let's see about on CI!

Verify Valkey support

---

doc/content/3.documentation/2.configuration/2.transports/3.azure-service-bus.md
src/MassTransit.Abstractions/Configuration/Consumers/BatchOptions.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/ClientSettings.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/Configuration/ServiceBusEndpointEntityConfigurator.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/Configuration/ServiceBusEntityReceiveEndpointConfiguration.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/Configuration/ServiceBusQueueConfigurator.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/Contexts/ServiceBusConnectionContext.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/Defaults.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/Topology/BaseClientSettings.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/Topology/ReceiveEndpointSettings.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/Topology/SubscriptionEndpointSettings.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/Batching/ServiceBusBatchingExtensions.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/Batching/ServiceBusSessionBatchOptions.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/Batching/SessionBatchOptions.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/Configuration/Configuration/ServiceBusBusFactoryConfigurator.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/Configuration/IServiceBusEndpointConfigurator.cs
src/Transports/MassTransit.Azure.ServiceBus.Core/Configuration/IServiceBusEndpointEntityConfigurator.cs

The aim is for batch-based in-order processing of messages within an ASB session.
* Our use case is we want to have:
*  X sessions processing concurrently (we scale out competing consumers as needed)
*  each session is processing batches of up to Y messages within a time limit Z
We had 2 issues:
1. `MaxConcurrentSessions` is currently derived from the batch options (ConcurrencyLimit * MessageLimit) 
-  Used with `MaxConcurrentCallsPerSession` it is quite difficult to control the max concurrency of the [ServiceBusSessionProcessor](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussessionprocessor?view=azure-dotnet).
-  Seemingly reasonable batch options can easily suffer thread exhaustion
- MessageLimit: 500, ConcurrencyLimit: 5, GroupBy: SessionId(), …

Convenience extension for session based batching in ASB and explicit control of MaxConcurrentSessions

---

src/MassTransit/Logging/Diagnostics/DiagnosticHeaders.cs
src/MassTransit/Logging/Diagnostics/LogContextActivityExtensions.cs

Add header MT-Activity-Propagation that configures how remote activity is treated. Either:
1. Link the remote activity
2. Use as parent activity (default)
3. Create new activity without reference to remote activity

feat: configure activity propagation

---

src/Transports/MassTransit.ActiveMqTransport/ActiveMqTransport/Configuration/ConfigurationHostSettings.cs
tests/MassTransit.ActiveMqTransport.Tests/Configure_Specs.cs

Hello.
I encountered the fact that the failover transport parameters, such as randomize and backup, are not applied.
The bug is in the implementation of the Apache.NMS.ActiveMQ client.
When creating the transport, I need to add the prefix `"transport."` which is absent in the instruction https://activemq.apache.org/components/classic/documentation/failover-transport-reference
Here is the line where FailoverTransport is created and the prefix `"transport."` is specified: https://github.com/apache/activemq-nms-openwire/blob/main/src/Transport/Failover/FailoverTransportFactory.cs#L72
In the project activemq-nms-openwire the Issues section is off. This project is developing poorly.
As these parameters are currently not working and cannot be set using MassTransit, I suggest fixing this in …

Fixing failover parameters and adding priorityBackup and priorityURIs parameters

---

doc/content/3.documentation/6.transports/sql.md

There was an extra `s` in the example.

Typo in AddSqlServerMigrationHostedService in docs

---

src/MassTransit.MessagePack/Serialization/MassTransitMessagePackFormatterResolver.cs

Hi.
In my previous PR (#5550), a change was suggestion regarding using a dictionary for mapping types, rather than enumerating through all until a match is found. [See comment.](https://github.com/MassTransit/MassTransit/pull/5550#discussion_r1798654302)
I thought the idea was too good to pass up, so this PR introduces said optimization.

Follow up PR: Optimization of MassTransitMessagePackFormatterResolver

---

doc/content/3.documentation/2.configuration/integrations/nsb.md

This PR links the NServiceBus integration sample to the corresponding sample on the NServiceBus docs.
This is a corresponding PR to https://github.com/Particular/docs.particular.net/pull/6869 to make sure that both sides of the integration angle are connected to each other.

Link integration docs to NServiceBus docs

---

src/Transports/MassTransit.ActiveMqTransport/ActiveMqTransport/Configuration/ConsumerConsumeTopicTopologySpecification.cs
src/Transports/MassTransit.ActiveMqTransport/ActiveMqTransport/Middleware/ActiveMqConsumerFilter.cs
src/Transports/MassTransit.ActiveMqTransport/ActiveMqTransport/Topology/ActiveMqConsumeTopology.cs
src/Transports/MassTransit.ActiveMqTransport/ActiveMqTransport/Topology/BrokerTopologyBuilder.cs
src/Transports/MassTransit.ActiveMqTransport/ActiveMqTransport/Topology/Entities/ConsumerEntity.cs
tests/MassTransit.ActiveMqTransport.Tests/ConsumerEntity_Specs.cs
tests/MassTransit.ActiveMqTransport.Tests/VirtualTopicEndpoint_Specs.cs

Hello,
this PR allows to subscribe to a non-Virtual Topic on ActiveMQ broker. I tried to use as most existing code as possible.
I enhanced Bind method and in case when a topic name isn't start with the virtual topic name prefix it uses new specification class where is set only Topic and Queue is left null. Then I have to change code that uses Queue property to not throw exception in case of setting only Topic.
Also added tests to check new code.

[ActiveMQ] Allow direct topic subscription

---

src/MassTransit/SqlTransport/Configuration/SqlTransportMigrationOptions.cs
src/MassTransit/SqlTransport/SqlTransport/ISqlTransportDatabaseMigrator.cs
src/MassTransit/SqlTransport/SqlTransport/SqlTransportMigrationHostedService.cs
src/Transports/MassTransit.SqlTransport.PostgreSql/Configuration/PostgresSqlTransportConfigurationExtensions.cs
src/Transports/MassTransit.SqlTransport.PostgreSql/SqlTransport/PostgreSql/PostgresDatabaseMigrator.cs
src/Transports/MassTransit.SqlTransport.SqlServer/Configuration/SqlServerDbTransportConfigurationExtensions.cs
src/Transports/MassTransit.SqlTransport.SqlServer/SqlTransport/SqlServer/SqlServerDatabaseMigrator.cs

Used with integrated authentication, e.g. MS Entra, when a migrator cannot properly extract a user name from a connection string.
I've tested this in Azure Web App using Azure SQL server transport authenticating with a managed identity.
fixes https://github.com/MassTransit/MassTransit/issues/5665

Allow skipping SQL transport schema creation

---

src/MassTransit/JobService/JobServiceExtensions.cs

As the title suggests, this change introduces an additional extension to simplify cases where `setJobProperties` isn't required. This avoids having to pass `null` or a named parameter unnecessarily. 
For example, instead of writing:
```csharp
await context.SubmitJob(new FileSystemProbe.Job { Path = entry.PathInfo.FullName }, cancellationToken: context.CancellationToken);
```
or 
```csharp
await context.SubmitJob(new FileSystemProbe.Job { Path = entry.PathInfo.FullName }, null, context.CancellationToken);
```
you can now simply write:
```csharp
await context.SubmitJob(new FileSystemProbe.Job { Path = entry.PathInfo.FullName }, context.CancellationToken);
```

feat: add job service extension that accepts the job + cancellation token

---

src/MassTransit/Configuration/DependencyInjection/DependencyInjectionRegistrationExtensions.cs
tests/MassTransit.Tests/ContainerTests/EmptyBodyConfiguration_Specs.cs

I have just wasted an hour trying to figure out why I got the following exception:
```
Unhandled exception. System.AggregateException: Some services are not able to be constructed
(Error while validating the service descriptor 'ServiceType: MassTransit.DependencyInjection.IScopedBusContextProvider`1[MassTransit.IBus] Lifetime: Scoped ImplementationType:
MassTransit.DependencyInjection.ScopedBusContextProvider`1[MassTransit.IBus]':
Unable to resolve service for type 'MassTransit.IBus' while attempting to activate 'MassTransit.DependencyInjection.ScopedBusContextProvider`1[MassTransit.IBus]'.)
```
Turns out I had a switch statement to configure different providers based on configuration, but after merging another branch the configuration added a new value, causing the `AddMassTransit` call …

Throw configuration exception if bus was not added

---

doc/content/3.documentation/3.patterns/8.claim-check.md
src/Persistence/MassTransit.Azure.Storage/AzureStorage/MessageData/AzureStorageMessageDataRepository.cs
src/Persistence/MassTransit.Azure.Storage/Configuration/AzureStorageConfigurationExtensions.cs
src/Persistence/MassTransit.Azure.Storage/Configuration/MessageDataRepositorySelectorExtensions.cs
tests/MassTransit.Azure.ServiceBus.Core.Tests/Configuration.cs
tests/MassTransit.Azure.ServiceBus.Core.Tests/MessageData_Specs.cs

This update enables compression when using AzureStorageMessageDataRepository for claim check. 
Files will be compressed before being written to blob storage and saved as `.gz` files.
On the consumer side, there is no need to manually set the flag, as the system will automatically detect if the file in blob storage is a .gz file and decompress it accordingly.
Added a compression option to the AzureStorageMessageDataRepository class.
Updated relevant methods to support compression.
Modified configuration extensions to handle the new compression feature.
Additionally, the documentation has been updated to reflect the new flag when initializing the AzureStorageMessageDataRepository:

Add Configuration for Compression in AzureStorageMessageDataRepository for Claim Check

---

src/MassTransit/SqlTransport/SqlTransport/Middleware/SqlMessageReceiver.cs

Changes in [SqlMessageReceiver.ReceiveMessages](https://github.com/MassTransit/MassTransit/blob/develop/src/MassTransit/SqlTransport/SqlTransport/Middleware/SqlMessageReceiver.cs#L124) to when the `DeadLetterQueue` and `TouchQueue` get executed. After upgrading to `v8.3.5` we noticed that the number of executed queries per second increased when our services are idling. Looking at the code we noticed that the conditions for running `TouchQueue` and `DeadLetterQueue` are always true.
With this PR I've changed the conditions so that the methods get called based on the configured interval.
Queries per second before and after the update:

Change DeadLetterQueue and TouchQueue run conditions in SqlMessageReceiver

---

src/MassTransit/Internals/Reflection/DynamicImplementationBuilder.cs
tests/MassTransit.Tests/Serialization/Interface_Specs.cs

This PR fixes #5818 by conditionally applying the `IsExternalInit` modifier to dynamically generated interface implementations of properties where:
- the published concrete implementation contains it
- the consuming assembly is on .NET 5 or greater (as `IsExternalInit` was only added in .NET 5).
- Tested by modifying a unit test to specify an `init` property and a `set` property (and verifying they fail without this fix).
- Tested on the repository of the original reported issue in the `after-fix` branch which I published this branch's NuGet packages in as a local repository source: https://github.com/lsymds/repro-mass-transit-interface-property-inits/tree/after-fix 
- Tested on a version of the repository of the original reported issue configured to run .NET Core 3.1 in a Docker …

Generate interfaces using init properties correctly

---

src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/AmazonSqsReceiveLockContext.cs

Issues:
We have encounter MT throws the below exception when it tries to delete the message from AWS SQS. 
```c#
System.AggregateException: ReceiveLock.Faulted threw an exception (The CancellationTokenSource has been disposed.) (Send failed: ReceiptHandleIsInvalid-The receipt handle has expired)
---> System.ObjectDisposedException: The CancellationTokenSource has been disposed.
at MassTransit.AmazonSqsTransport.AmazonSqsReceiveLockContext.Faulted(Exception exception) in /codebuild/output/src1082/src/s3/00/src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/AmazonSqsReceiveLockContext.cs:line 57
at MassTransit.Transports.PendingReceiveLockContext.Execute(Func`2 action) in /codebuild/output/src1082/src/s3/00/src/MassTransit/Transports/PendingReceiveLockContext.cs:line 80
at …
```

Update AmazonSqsReceiveLockContexts to check if the cancellation has been requested

---

doc/content/3.documentation/1.concepts/6.requests.md
doc/content/3.documentation/2.configuration/4.persistence/dynamodb.md

This PR improves the documentation by:
- Updating two sample code snippets in the Requests section to use primary constructors, making the examples more concise.
- Adding an example for configuring DynamoDB as a SagaRepository, replacing a previously empty page.
The updated snippets were tested in a sample project and should work as intended.

Use Primary Constructors where applicable & Add docs for DynamoDB

---

src/MassTransit/Sagas/Saga/PropertyExpressionSagaQueryFactory.cs

Generating saga queries with embedded constants is not great for the EF Core query cache.

Avoid generating saga queries with embedded constants

---

doc/content/3.documentation/1.concepts/4.exceptions.md

Updated documentation to explicitly tell that we need to include default filters in error pipe if we want to define custom filter on top of default behaviour.
Related to https://github.com/MassTransit/MassTransit/discussions/2945 and https://github.com/MassTransit/MassTransit/discussions/5352

Updated documentation on configureError method in Error pipe

---

Directory.Packages.props
src/Persistence/MassTransit.DynamoDbIntegration/DynamoDbIntegration/Saga/DynamoDbDatabaseContext.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/AmazonSqsClientContext.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/AmazonSqsHeaderProvider.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/AmazonSqsReceiveContext.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/Configuration/AmazonSqsRegistrationBusFactory.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/Middleware/AmazonSqsMessageReceiver.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/PublishBatcher.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/QueueCache.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/QueueInfo.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/QueueSendTransportContext.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/SqsMoveTransport.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/TopicCache.cs
src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/TopicSendTransportContext.cs
src/Transports/MassTransit.AmazonSqsTransport/Configuration/AmazonSqsBusFactoryConfiguratorExtensions.cs

We GA V4 of the AWS SDK for .NET: https://aws.amazon.com/blogs/developer/general-availability-of-aws-sdk-for-net-v4-0/
The PR updates the SDK dependencies to V4 and address any compilation and obsolete warnings triggered by the update. V4 does have a runtime behavior change where collection properties for types used to make requests like `MessageAttributes` on `Message` default to `null` unlike V3 which defaulted to empty string. I Looked through the usage of the SDK calls and added null checks.
I wasn't sure how I should run the tests locally. I see it uses Localstack which I'm not very familiar with. Hoping maybe a GitHub workflow will kick them off but otherwise are there steps I should follow to run the tests?

Update the AWS packages to use AWS .NET SDK V4

---

doc/content/3.documentation/2.configuration/5.scheduling.md
doc/content/3.documentation/3.patterns/13.job-consumers.md
doc/content/4.support/3.samples.md

This PR updates the MassTransit job consumer documentation for clarity and correctness:
- Fixed grammar in job scheduling section
- Standardized use of “routing slip” (removed unnecessary hyphen)
- Clarified job type saga state list to resolve contradiction in listed states
- Updated `AddQuartz()` usage by removing deprecated `UseMicrosoftDependencyInjectionJobFactory()`
- Added guidance around full Quartz configuration (clustering, serializer, etc.)
- Included required `quartz.serializer.type` appsettings example for persistent store scenarios
The minimal example is preserved for simplicity, with notes pointing to the full sample repo for advanced use cases.

docs: improve config guidance and clarify documentation

---

src/Transports/MassTransit.RabbitMqTransport/Configuration/IRabbitMqStreamConfigurator.cs
src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/Configuration/RabbitMqStreamConfigurator.cs

Introduced `Reference` property on `IRabbitMqStreamConfigurator` to allow specifying a consumer reference name used for server-side offset tracking. This value is applied to the "name" argument of the stream consumer.
1. I made the code change to the MassTransit project
1. I ran this to get a new package
```sh
dotnet pack src/Transports/MassTransit.RabbitMqTransport/MassTransit.RabbitMqTransport.csproj -c Release -p:Version=8.0.1-nmummau
```
1. I created a local nuget feed at `C:\LocalFeed`, and copied over the `MassTransit.RabbitMQ.8.0.0-nmummau.nupkg` file to this directory
1.  I installed this pre-release package `MassTransit.RabbitMQ.8.0.0-nmummau` into a worker project that I'm building
1. I set the Reference in the StreamConfigurator
1. At startup of my worker project, the consumer …

feat(rabbitmq-stream): add support for consumer reference name

---

src/Transports/MassTransit.ActiveMqTransport/ActiveMqTransport/Configuration/ConfigurationHostSettings.cs
tests/MassTransit.ActiveMqTransport.Tests/Configure_Specs.cs

Hello,
When I tested failover with completely local Artemis cluster running on same host but on different ports, I figured out that there is no way how to configure it in MT. I add possibility to do it. If there is no port defined in a failover host the default will be used. 
Thank you.

Allow port in failover host configuration

---

doc/content/3.documentation/2.configuration/2.transports/2.rabbitmq.md

The new text is less complex and distinguishes publishers and listeners.

Improved clarity of warning on message loss
