- doc/source/configuration/quickstart.rst
Moved MSMQ section into UseMsmq and updated body text to reflect changes - fixes issue #297
> Fix for MSMQ quickstart documentation

- src/Persistence/MassTransit.EntityFrameworkIntegration/Saga/EntityFrameworkSagaRepository.cs
Awesome, I'm glad to see the EF Integration polished up! I also took a bit more time checking out the MissingPipe, and the policy (NewOrExistingSagaPolicy and AnyExistingSagaPolicy) and understand why the transaction is needed.
One code cleanup I thought we could add was using the CreateWithTransaction(...) method.
If you take a quick gander [here](https://github.com/mehdime/DbContextScope/blob/master/Mehdime.Entity/Implementations/DbContextScope.cs#L70) you'll see that the transaction is committed on our call to `await dbContextScope.SaveChangesAsync();`, but if any exception occurs within, the [dispose](https://github.com/mehdime/DbContextScope/blob/master/Mehdime.Entity/Implementations/DbContextScope.cs#L238) handles the rollback.
So this just cleans up the code a bit :+1: 
Thanks for …
> Use the scope factory CreateWithTransaction(...)

- doc/source/installation/prerequisites.rst
> Change 'guid' to 'guide'

- README.md
Additionally there should be mention that you should create class MyMessage for sample code to work.
> Fixed not working sample

- src/MassTransit.RabbitMqTransport/Contexts/RabbitMqModelContext.cs
Less awaits and less `ConfigureAwait(false)`
> Reduced await statements in RabbitMqModelContext

- host/MassTransit.Host.log4net.config
- host/install.ps1
- src/MassTransit.Host/AssemblyScanner.cs
- src/MassTransit.Host/MassTransitHostService.cs
Added the masstransit host log4net configuration so console output is enabled by default and changed the logging level of assembly scanner load errors.
Also set the project startup to launch MassTransit.Host.exe
> Mass transit host updates

- doc/source/usage/containers/autofac.rst
Code should now compile and adds mention of the needed nugets. :+1:
> Correct docs based on issue #454

- src/MassTransit/Configuration/BusObserverExtensions.cs
Well, this has bothered me a lot more than it should have.
Changed the BusObserverExtensions methods to actual extensions :)
> BusObserverExtensions changed to extension methods

- src/MassTransit.QuartzIntegration.Tests/Recurring_Specs.cs
- src/MassTransit.QuartzIntegration/CancelScheduledMessageConsumer.cs
- src/MassTransit.QuartzIntegration/ScheduleMessageConsumer.cs
- src/MassTransit/Scheduling/DefaultRecurringSchedule.cs
- src/MassTransit/Scheduling/RecurringSchedule.cs
Added schedule description, mapped to trigger description
This is rebased & squashed from #538, re: @ushenkodmitry.
> Schedule description

- src/MassTransit.Tests/LazyMemoryCache_Specs.cs
- src/MassTransit/Util/Caching/LazyMemoryCache.cs
Added logic to avoid awaiting faulted task and throwing on a thread pool thread.
> LazyMemoryCache Faulted Task Handling

- src/Persistence/MassTransit.EntityFrameworkIntegration/Saga/EntityFrameworkSagaRepository.cs
Changed manual locking to only use row locks. Switched IsolationLevel for the transactions to default (Read Commited). This will remove all range locks and deadlocks without the need for a table lock.
> Improve locks for EntityFrameworkSagaRepository

- src/Persistence/MassTransit.EntityFrameworkIntegration/Saga/EntityFrameworkSagaRepository.cs
This also fixes a potential null ref.
> Refactored SendQuerys handling of missing Sagas

- .gitignore
- build.fsx
- src/MassTransit.sln
- src/Persistence/MassTransit.MartenIntegration.Tests/MassTransit.MartenIntegration.Tests.csproj
- src/Persistence/MassTransit.MartenIntegration.Tests/Messages.cs
- src/Persistence/MassTransit.MartenIntegration.Tests/SagaPersistenceTests.cs
- src/Persistence/MassTransit.MartenIntegration.Tests/SimpleSaga.cs
- src/Persistence/MassTransit.MartenIntegration.Tests/TestSaga.cs
- src/Persistence/MassTransit.MartenIntegration.Tests/packages.config
- src/Persistence/MassTransit.MartenIntegration/IRetrieveSagaFromRepository.cs
- src/Persistence/MassTransit.MartenIntegration/MartenSagaConsumeContext.cs
- src/Persistence/MassTransit.MartenIntegration/MartenSagaRepository.cs
- src/Persistence/MassTransit.MartenIntegration/MassTransit.MartenIntegration.csproj
- src/Persistence/MassTransit.MartenIntegration/packages.config
> Added Marten saga persistence

- doc/source/usage/containers/autofac.rst
> Added docs about Autofac and Automatonymous sagas

- docs/SUMMARY.md
- docs/advanced/sagas/persistence.md
- docs/contributing/README.md
Azure SB persistence needs work.
> Added Marten persistence, persistence page ToC and contribution guide

- docs/advanced/sagas/persistence.md
> Add Optimistic and Pessimistic Concurrency docs for EF

- docs/usage/exceptions.md
- docs/usage/retries.md
- src/MassTransit/BusControlExtensions.cs
This is docs only. Should read "Retry fix"
> Retry (docs) fix for the Exceptions page and #815

- docs/usage/configuration.md
Adding the configuration documents to reference how to do registration for asp.net core.
> Adding docs for asp.net core

- docs/advanced/sagas/automatonymous.md
Small paragraph on egnoring events. Originates from https://groups.google.com/forum/#!topic/masstransit-discuss/P8ulb5n5wjo
> Docs on ignoring events in saga

- src/MassTransit/RequestClient.cs
Someone forgot to add the default value.
> Implementing the IRequestClient interface properly

- src/Persistence/MassTransit.MongoDbIntegration/Saga/Context/MongoDbSagaConsumeContext.cs
I've faced with a problem in case of high concurrency environment. If saga instance receives message that should transfer saga in some state in the same time with another message that should finalize the instance it's possible to get saga instance finalized from incorrect state.
The issue may be fixed by the same approach as in MongoDbSagaRepository.UpdateMongoDbSaga method.
> Fix concurrency issue in case of simultaneous saga update and delete operations

- src/Loggers/MassTransit.ExtensionsLoggingIntegration/MassTransit.ExtensionsLoggingIntegration.csproj
I would like to use Microsoft.Extensions.Logging with my net452 application and Masstransit.
> Support MassTransit.ExtensionsLoggingIntegration with net452

- docs/README.md
- docs/SUMMARY.md
- docs/introduction/getting-help.md
> Pointing to SO and mailing list a bit more

- src/MassTransit.AzureServiceBusTransport/ServiceBusHost.cs
- src/MassTransit.HttpTransport/Transport/HttpHost.cs
- src/MassTransit.RabbitMqTransport/Transport/RabbitMqHost.cs
- src/MassTransit/IHost.cs
- src/MassTransit/MassTransitBus.cs
- src/MassTransit/Transports/IReceiveEndpointCollection.cs
- src/MassTransit/Transports/InMemory/InMemoryHost.cs
- src/MassTransit/Transports/ReceiveEndpointCollection.cs
Fixing publish observer binding.
> Fixing #856 #956

- src/MassTransit.AzureServiceBusTransport/Configuration/Configurators/ServiceBusEndpointSpecification.cs
- src/MassTransit.AzureServiceBusTransport/ServiceBusHost.cs
- src/MassTransit.AzureServiceBusTransport/Transport/ReceiveTransport.cs
- src/MassTransit.HttpTransport/Transport/HttpHost.cs
- src/MassTransit.HttpTransport/Transport/HttpReceiveTransport.cs
- src/MassTransit.RabbitMqTransport/Transport/RabbitMqHost.cs
- src/MassTransit.RabbitMqTransport/Transport/RabbitMqReceiveTransport.cs
- src/MassTransit.Tests/Audit/Audit_Specs.cs
- src/MassTransit/IHost.cs
- src/MassTransit/IReceiveEndpoint.cs
- src/MassTransit/MassTransitBus.cs
- src/MassTransit/Transports/IReceiveEndpointCollection.cs
- src/MassTransit/Transports/IReceiveTransport.cs
- src/MassTransit/Transports/InMemory/InMemoryHost.cs
- src/MassTransit/Transports/InMemory/InMemoryReceiveTransport.cs
- src/MassTransit/Transports/ReceiveEndpoint.cs
- src/MassTransit/Transports/ReceiveEndpointCollection.cs
Fixing SendObserver binding #856
> Fixing SendObserver binding #856

- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Saga/EntityFrameworkSagaRepository.cs
As discussed in #972 , this pr adds cancellation token passing from context to all ef core database calls.
> Pass cancellation token to ef core database calls

- docs/usage/scheduling/scheduling-api.md
Fixed every minute cron expression. 
Last line changed by GitHub.
> Fix cron expression

- docs/usage/README.md
> added logging and testing links in usage/README.md

- appveyor.yml
- build.bat
- build.fsx
Gitlink has changed the directory structure and our build started to fail. This PR fixes it.
> Fixing gitlink path

- docs/usage/containers/castlewindsor.md
> Rename StructureMap to Castle Windsor

- src/MassTransit/Audit/MessageAuditMetadata.cs
- src/MassTransit/Audit/MetadataFactories/DefaultConsumeMetadataFactory.cs
- src/MassTransit/Audit/MetadataFactories/DefaultSendMetadataFactory.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Audit/AuditDbContext.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Audit/AuditMapping.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Audit/AuditRecord.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Audit/EntityFrameworkAuditStore.cs
- src/Persistence/MassTransit.EntityFrameworkIntegration/Audit/AuditMapping.cs
- src/Persistence/MassTransit.EntityFrameworkIntegration/Audit/AuditRecord.cs
#1017 Added InputAddress to audit records and EF/EF.Core audit stores
> #1017 Added InputAddress to audit records

- docs/understand/additions-to-transport.md
> Fixed link in add-to-transport

- src/MassTransit.AzureServiceBusTransport/Configuration/Configurators/ServiceBusBusFactoryConfigurator.cs
- src/MassTransit.AzureServiceBusTransport/Topology/Configuration/Configurators/MessageEntityConfigurator.cs
I run integration tests in local and now default queue endpoint properties have the right value. 
If we want to add unit tests on this part we have to expose _settings field to public or pass it via constructor.
> fixed bug #1045

- appveyor.yml
- src/MassTransit.AutomatonymousIntegration.Tests/MassTransit.AutomatonymousIntegration.Tests.csproj
- src/Persistence/MassTransit.DocumentDbIntegration.Tests/MassTransit.DocumentDbIntegration.Tests.csproj
- src/Persistence/MassTransit.DocumentDbIntegration/MassTransit.DocumentDbIntegration.csproj
- Update to 1.19.1
- Also update Cosmos Db Emulator in AppVeyor.yml
> Update Azure DocDb Nuget Package for Net452

- doc/source/usage/containers/autofac.rst
- docs/usage/containers/autofac.md
> Remove tiny extra '<' charecter in autofac usage's doc

- src/Loggers/MassTransit.NLogIntegration/MassTransit.NLogIntegration.csproj
Another nail in the coffin #909
> NLog with NetStandard support

- src/MassTransit.AutomatonymousIntegration.Tests/MassTransit.AutomatonymousIntegration.Tests.csproj
- src/MassTransit/Saga/ISaga.cs
- src/Persistence/MassTransit.DocumentDbIntegration.Tests/MassTransit.DocumentDbIntegration.Tests.csproj
- src/Persistence/MassTransit.DocumentDbIntegration.Tests/Saga/Data/SimpleSaga.cs
- src/Persistence/MassTransit.DocumentDbIntegration.Tests/Saga/DocumentDbSagaConsumeContextTestsForPopContext.cs
- src/Persistence/MassTransit.DocumentDbIntegration.Tests/Saga/MissingPipeTestsForProbing.cs
- src/Persistence/MassTransit.DocumentDbIntegration.Tests/Saga/MissingPipeTestsForSendingWhenProxyCompleted.cs
- src/Persistence/MassTransit.DocumentDbIntegration.Tests/Saga/MissingPipeTestsForSendingWhenProxyIncomplete.cs
- src/Persistence/MassTransit.DocumentDbIntegration/MassTransit.DocumentDbIntegration.csproj
- src/Persistence/MassTransit.DocumentDbIntegration/PropertyRenameSerializerContractResolver.cs
- src/Persistence/MassTransit.DocumentDbIntegration/Saga/Context/DocumentDbSagaConsumeContext.cs
- src/Persistence/MassTransit.DocumentDbIntegration/Saga/Context/DocumentDbSagaConsumeContextFactory.cs
- src/Persistence/MassTransit.DocumentDbIntegration/Saga/Context/IDocumentDbSagaConsumeContextFactory.cs
- src/Persistence/MassTransit.DocumentDbIntegration/Saga/DocumentDbSagaRepository.cs
- src/Persistence/MassTransit.DocumentDbIntegration/Saga/Pipeline/MissingPipe.cs
I am not sure if this will pass tests because I don't have the emulator. Let me check if it will build.
> Removing serialisation attribute from ISaga, resolves #1131

- docs/advanced/sagas/persistence.md
> Added docs for Dapper persistence.

- src/Containers/MassTransit.Automatonymous.LamarIntegration/LamarSagaStateMachineFactory.cs
- src/Containers/MassTransit.Automatonymous.LamarIntegration/LamarStateMachineActivityFactory.cs
- src/Containers/MassTransit.Automatonymous.LamarIntegration/LamarStateMachineLoadSagaExtensions.cs
- src/Containers/MassTransit.Automatonymous.LamarIntegration/LamarStateMachineSagaRepositoryFactory.cs
- src/Containers/MassTransit.Automatonymous.LamarIntegration/LamarStateMachineSubscriptionExtensions.cs
- src/Containers/MassTransit.Automatonymous.LamarIntegration/MassTransit.Automatonymous.LamarIntegration.csproj
- src/Containers/MassTransit.Containers.Tests/LamarStateMachineSaga_Specs.cs
- src/Containers/MassTransit.Containers.Tests/Lamar_Idiomatic.cs
- src/Containers/MassTransit.Containers.Tests/Lamar_Specs.cs
- src/Containers/MassTransit.Containers.Tests/MassTransit.Containers.Tests.csproj
- src/Containers/MassTransit.LamarIntegration/LamarActivityFactory.cs
- src/Containers/MassTransit.LamarIntegration/LamarCompensateActivityScopeProvider.cs
- src/Containers/MassTransit.LamarIntegration/LamarConsumerFactory.cs
- src/Containers/MassTransit.LamarIntegration/LamarConsumerScopeProvider.cs
- src/Containers/MassTransit.LamarIntegration/LamarExecuteActivityScopeProvider.cs
- src/Containers/MassTransit.LamarIntegration/LamarExtensions.cs
- src/Containers/MassTransit.LamarIntegration/LamarSagaRepository.cs
- src/Containers/MassTransit.LamarIntegration/LamarSagaRepositoryFactory.cs
- src/Containers/MassTransit.LamarIntegration/LamarSagaScopeProvider.cs
- src/Containers/MassTransit.LamarIntegration/MassTransit.LamarIntegration.csproj
- src/MassTransit.sln
Hi guys,
I have added Lamar tests in the MassTransit.Containers.Tests project. Hopefully that verifies it works as much as any of the other Containers!
Please see https://github.com/MassTransit/MassTransit/issues/1145 for comments around the motivation and a couple of issues I had when developing - plus an outstanding issue in Lamar. Once that issue is resolved, I'll fix these up and make another PR for you.
This is a replacement for PR https://github.com/MassTransit/MassTransit/pull/1146 - hopefully the whitespace issues are all resolved now!
> Use the StructureMap integration as a base and implement as Lamar.

- docs/usage/exceptions.md
> Fix tag closure around "UseRetry"

- docs/advanced/topology/rabbitmq/routingkey.md
Added extra configuration showcare options. With comments about why and when you want to use them.
> Provide more details for RoutingKey Example

- docs/usage/configuration.md
To get less code in startup.cs and separate the concerns of handling starting and stopping the bus, it is easier to use IHostedService to automatically handle start and stop of the bus .
> Update docs for ASP.NET CORE to use IHostedService

- docs/usage/producing-messages.md
> Endpoint conventions docs

- src/MassTransit.Azure.ServiceBus.Core/Topology/Builders/BrokerTopologyBuilder.cs
- src/MassTransit.AzureServiceBusTransport/Topology/Builders/BrokerTopologyBuilder.cs
fixing https://github.com/MassTransit/MassTransit/issues/763 , missing subscription rules/filters, 
This PR fixes the issue
> fixing missing rules and filters on subscription 

- appveyor.yml
- src/MassTransit.AutomatonymousIntegration.Tests/MassTransit.AutomatonymousIntegration.Tests.csproj
- src/MassTransit.AutomatonymousIntegration.Tests/UsingDocumentDbConcurrencyOptimistic_Specs.cs
- src/Persistence/MassTransit.DocumentDbIntegration.Tests/MassTransit.DocumentDbIntegration.Tests.csproj
- src/Persistence/MassTransit.DocumentDbIntegration.Tests/Saga/DocumentDbSagaRepositoryTestsForSendQuery.cs
- src/Persistence/MassTransit.DocumentDbIntegration.Tests/Saga/DocumentDbSagaRepositoryTestsForSendingWhenInstanceNotReturnedFromPolicy.cs
- src/Persistence/MassTransit.DocumentDbIntegration.Tests/Saga/DocumentDbSagaRepositoryTestsForSendingWhenPolicyReturnsCompletedInstance.cs
- src/Persistence/MassTransit.DocumentDbIntegration.Tests/Saga/DocumentDbSagaRepositoryTestsForSendingWhenPolicyReturnsInstance.cs
- src/Persistence/MassTransit.DocumentDbIntegration/MassTransit.DocumentDbIntegration.csproj
- src/Persistence/MassTransit.DocumentDbIntegration/Saga/Context/DocumentDbSagaConsumeContext.cs
- src/Persistence/MassTransit.DocumentDbIntegration/Saga/Context/DocumentDbSagaConsumeContextFactory.cs
- src/Persistence/MassTransit.DocumentDbIntegration/Saga/Context/IDocumentDbSagaConsumeContextFactory.cs
- src/Persistence/MassTransit.DocumentDbIntegration/Saga/DocumentDbSagaRepository.cs
- src/Persistence/MassTransit.DocumentDbIntegration/Saga/Pipeline/MissingPipe.cs
> Add Request/Feed Options to DocDb Repository

- docs/usage/logging.md
> Add Microsoft Extensions Logger to documentation

- docs/SUMMARY.md
- docs/advanced/README.md
- docs/advanced/interoperability.md
- docs/advanced/interoperability/encrypted-messages.md
- docs/learn/videos.md
I've been asked how the encrypted messages worked, so seeing as I changed the code... thought I'd take time to update the docs too.
I've also added a link to a lightning talk I did on MassTransit a while back - hope you don't mind.
> Updating docs for Encrypted Messages

- README.md
Updated the `Simplest possible thing` in README.md, to be more relevant to the current code base.
> fix(readme): Updated the `simplest possible thing` in readme.md

- src/MassTransit.AmazonSqsTransport/Contexts/AmazonSqsClientContext.cs
Fixes #1218 found it checking the cached topic arn's dictionary.
> AmazonSqs auto-delete is being ignored.

- src/MassTransit.ActiveMqTransport.Tests/test.log4net.xml
- src/MassTransit.ActiveMqTransport/Configuration/ActiveMqHostConfigurationExtensions.cs
- src/MassTransit.AmazonSqsTransport.Tests/test.log4net.xml
- src/MassTransit.AmazonSqsTransport/Configuration/AmazonSqsHostConfigurationExtensions.cs
- src/MassTransit.Azure.ServiceBus.Core/Topology/Conventions/PartitionKey/SetPartitionKeyMessageSendTopology.cs
- src/MassTransit.Azure.ServiceBus.Core/Topology/Entities/Queue.cs
- src/MassTransit.Azure.ServiceBus.Core/Topology/Entities/Topic.cs
- src/MassTransit.Azure.ServiceBus.Core/Topology/Topologies/ServiceBusMessagePublishTopology.cs
- src/MassTransit.AzureServiceBusTransport/Topology/Conventions/PartitionKey/SetPartitionKeyMessageSendTopology.cs
- src/MassTransit.AzureServiceBusTransport/Topology/Entities/Queue.cs
- src/MassTransit.AzureServiceBusTransport/Topology/Entities/Topic.cs
- src/MassTransit.AzureServiceBusTransport/Topology/Topologies/ServiceBusMessagePublishTopology.cs
- src/MassTransit.HttpTransport.Tests/test.log4net.xml
- src/MassTransit.HttpTransport/Configuration/HttpBusFactory.cs
Removed references of RabbitMQ in comments outside of the RabbitMQ Transport.
> Updated a few comments

- .github/ISSUE_TEMPLATE.md
> Fixed spelling mistake in ISSUE_TEMPLATE.md

- src/Containers/MassTransit.AspNetCoreIntegration/MassTransit.AspNetCoreIntegration.csproj
- src/Containers/MassTransit.AspNetCoreIntegration/MassTransitHostedService.cs
- src/Containers/MassTransit.AspNetCoreIntegration/ServiceCollectionExtensions.cs
Adding logging extensions integration to the ASP.NET Core integration library
> Adding logging extensions integration

- src/Containers/MassTransit.AspNetCoreIntegration/ServiceCollectionExtensions.cs
The previous version only added extensions logging when using the bus instance.
This version configures logging for all cases.
> Adding logging also when using the delegate

- src/Persistence/MassTransit.DapperIntegration/DapperSagaRepository.cs
Changed SendQuery to lock the same way as the EntityFramework version does. Problem was casued by locking on two different indices in db.
> Deadlocks from locking on different indices with SendQuery and Send in DapperIntegration.

- src/Containers/MassTransit.ExtensionsDependencyInjectionIntegration/ConsumerCacheService.cs
> fix ConsumerCacheService bug

- src/Containers/MassTransit.Containers.Tests/Autofact_ScopeSpecs.cs
Test for Autofac Scope configuration, could be used as a sample
> - add more test/sample how to use scope registration with autofac

- src/MassTransit.Azure.ServiceBus.Core.Tests/Publish_Specs.cs
- src/MassTransit.Azure.ServiceBus.Core/Configuration/Configuration/ServiceBusEntityReceiveEndpointConfiguration.cs
- src/MassTransit.Azure.ServiceBus.Core/Configuration/Configuration/ServiceBusReceiveEndpointConfiguration.cs
- src/MassTransit.Azure.ServiceBus.Core/Configuration/Configuration/ServiceBusSubscriptionEndpointConfiguration.cs
- src/MassTransit.Azure.ServiceBus.Core/Pipeline/ConfigureTopologyFilter.cs
- src/MassTransit.Azure.ServiceBus.Core/Transport/PublishTransportProvider.cs
- src/MassTransit.Azure.ServiceBus.Core/Transport/SendEndpointSendTransportProvider.cs
- src/MassTransit.AzureServiceBusTransport.Tests/Publish_Specs.cs
- src/MassTransit.AzureServiceBusTransport/Configuration/Configuration/ServiceBusEntityReceiveEndpointConfiguration.cs
- src/MassTransit.AzureServiceBusTransport/Configuration/Configuration/ServiceBusReceiveEndpointConfiguration.cs
- src/MassTransit.AzureServiceBusTransport/Configuration/Configuration/ServiceBusSubscriptionEndpointConfiguration.cs
- src/MassTransit.AzureServiceBusTransport/Pipeline/ConfigureTopologyFilter.cs
- src/MassTransit.AzureServiceBusTransport/Transport/PublishTransportProvider.cs
- src/MassTransit.AzureServiceBusTransport/Transport/SendEndpointSendTransportProvider.cs
fix for issue https://github.com/MassTransit/MassTransit/issues/1230
> - fix remove subscriptions ASB bug

- src/Containers/MassTransit.Automatonymous.WindsorIntegration/MassTransit.Automatonymous.WindsorIntegration.csproj
- src/Containers/MassTransit.Automatonymous.WindsorIntegration/WindsorSagaScopeProvider.cs
- src/Containers/MassTransit.Automatonymous.WindsorIntegration/WindsorSagaStateMachineFactory.cs
- src/Containers/MassTransit.Automatonymous.WindsorIntegration/WindsorStateMachineActivityFactory.cs
- src/Containers/MassTransit.Automatonymous.WindsorIntegration/WindsorStateMachineLoadSagaExtensions.cs
- src/Containers/MassTransit.Automatonymous.WindsorIntegration/WindsorStateMachineRegisterSagaExtensions.cs
- src/Containers/MassTransit.Automatonymous.WindsorIntegration/WindsorStateMachineSagaRepositoryFactory.cs
- src/Containers/MassTransit.Containers.Tests/CastleWindsorStateMachineSaga_Specs.cs
- src/Containers/MassTransit.Containers.Tests/MassTransit.Containers.Tests.csproj
- src/MassTransit.sln
There was no way to DI Inject Automatonymous StateMachineSagas with Castle Windsor, manual way was too tedious, so i wrote an extension library for it, following the project conventions, unit test added to Container.tests project.
**Any Feedback will be much appreciated.**
Thanks.
Regards,
Hannan
> Added Automatonymous StateMachineSagas integration for Castle Windsor.

- docs/README.md
> Fixed cosmetic errors

- docs/understand/key-ideas.md
> Cosmetic fixes in the documentation

- src/MassTransit/TransactionContextExtensions.cs
CreateTransactionScope method overload with async flow options parameter.
> Async flow options for transaction scope

- src/MassTransit.ApplicationInsights.Tests/Configure_Specs.cs
- src/MassTransit.ApplicationInsights/ApplicationInsightsFilter.cs
- src/MassTransit.ApplicationInsights/ApplicationInsightsMiddlewareConfiguratorExtensions.cs
- src/MassTransit.ApplicationInsights/ApplicationInsightsSpecification.cs
Ability to configure operation, could be used to provide additional headers
> application insights configuration

- appveyor.yml
- waitforport.ps1
Removing unnecessary uninstall and install code.
Also moved test for port into powershell as done here: https://github.com/appveyor-tests/CosmosDb
> AppVeyor Update on Dec 13th 2018 fixed CosmoDb Emulator Startup Issue

- docs/SUMMARY.md
> Fix Summary Doc Paths

- docs/usage/monitoring/diagnostic-source.md
Was trying out the System.Diagnostics.DiagnosticSource and noticed the typo!
> DiagnosticSourceListener -> DiagnosticListener

- src/Containers/MassTransit.AspNetCoreIntegration/HealthChecks/BusHealthCheck.cs
- src/Containers/MassTransit.AspNetCoreIntegration/HealthChecks/Health.cs
- src/Containers/MassTransit.AspNetCoreIntegration/HealthChecks/ReceiveEndpointHealthCheck.cs
- src/Containers/MassTransit.AspNetCoreIntegration/HealthChecks/SimplifiedBusHealthCheck.cs
- src/Containers/MassTransit.AspNetCoreIntegration/MassTransit.AspNetCoreIntegration.csproj
- src/Containers/MassTransit.AspNetCoreIntegration/MassTransitHostedService.cs
- src/Containers/MassTransit.AspNetCoreIntegration/ServiceCollectionExtensions.cs
Packages are updated to 2.2 since that's the first version where health checks are available
> Added health check to the ASP.NET Core integration

- src/MassTransit.Azure.ServiceBus.Core/ServiceBusBusFactoryConfiguratorExtensions.cs
> Add Remove Subscriptions =true to Temporary Receive Endpoint

- build/version.cake
- Forgot to trim the git sha down to 7 chars
- Rename preview to develop for prerelease packages
> Fix Nupkg Version

- appveyor.yml
- src/MassTransit.AutomatonymousIntegration/MassTransit.AutomatonymousIntegration.csproj
- src/Persistence/MassTransit.DapperIntegration/MassTransit.DapperIntegration.csproj
> v5.2.3 Updated version, fixed misnamed package

- docs/usage/configuration.md
- docs/usage/containers/msdi.md
* Added the docs for the new ASP.NET Core integration package
* Removed Autofac from the old sample
* Removed `LoadFrom` for both samples
> Updating the docs for ASP.NET Core integration

- docs/advanced/signalr/quickstart.md
- src/MassTransit.SignalR.Tests/Utils/MassTransitHubLifetimeTestFixture.cs
- src/MassTransit.SignalR/MassTransitDependencyInjectionExtensions.cs
- src/MassTransit.SignalR/MassTransitHubLifetimeManager.cs
- src/MassTransit.SignalR/MassTransitSignalRConfigurationExtensions.cs
- src/MassTransit.SignalR/Utils/HubConsumersCache.cs
- src/Samples/MassTransit.SignalR.Sample/Startup.cs
So the registration is way better now with the new container work. Helped me rework the SignalR Registration. The only thing I had to do was for AddRequestClient, I had to add a .AddSingleton as well, because I call the request client from a Singleton. Hope that's okay for me to add.
> Use SignalR New Container Registration for Better Setup Experience

- docs/README.md
- docs/quickstart.md
- docs/usage/retries.md
- src/Directory.Build.props
- src/MassTransit.AzureServiceBusTransport/Transport/ServiceBusSendTransport.cs
> Updating documentation

- src/MassTransit.AmazonSqsTransport.Tests/Configure_Specs.cs
- src/MassTransit.AmazonSqsTransport/Configuration/Configurators/AmazonSqsHostConfigurator.cs
- src/MassTransit.AmazonSqsTransport/Configuration/Configurators/ConfigurationHostSettings.cs
- src/MassTransit.AmazonSqsTransport/Configuration/IAmazonSqsHostConfigurator.cs
- src/MassTransit.AmazonSqsTransport/Transport/Connection.cs
Please see https://github.com/MassTransit/MassTransit/issues/1311#issuecomment-466956641
> Resolves #1311 Add the option to configure SQS transport with AWSCredentials

- src/Persistence/MassTransit.DapperIntegration/DapperSagaRepository.cs
> Replaced lock in Find with nolock hint, added nolock hint in SendQuery.

- src/MassTransit.AmazonSqsTransport/MassTransit.AmazonSqsTransport.csproj
Build succeeds and nuget restore succeeds
> Migrated AmazonSqsTransport to netstandard

- src/MassTransit.Azure.ServiceBus.Core/Contexts/ServiceBusNamespaceContext.cs
Method CreateTopicSubscription was different between MassTransit.Azure.ServiceBus.Core.Contexts and MassTransit.AzureServiceBusTransport.Contexts
> Fix bug due to code duplication on ServiceBusNamespaceContext

- src/Containers/MassTransit.ExtensionsDependencyInjectionIntegration/Configuration/Registration/ServiceCollectionConfigurator.cs
> Changed bus to use TryAddSingleton

- docs/usage/configuration.md
due to error with already declared host variable
> updpate configuration.md

- docs/usage/README.md
- Commit from a few weeks ago forgot to add the markdown
to the index page.
> Forgot to Reference New Doc Section

- docs/usage/configuration.md
> Configuration lambda name typo fix, Uri param in Host

- docs/advanced/sagas/persistence.md
> Incorrect constructor naming

- appveyor.yml
- src/MassTransit.AutomatonymousIntegration.Tests/MissingInstance_Specs.cs
- src/MassTransit.AutomatonymousIntegration/Configuration/CorrelationConfigurators/EventMissingInstanceConfigurator.cs
- src/MassTransit.AutomatonymousIntegration/Configuration/CorrelationConfigurators/MassTransitEventCorrelationConfigurator.cs
- src/MassTransit.AutomatonymousIntegration/Configuration/CorrelationConfigurators/MissingInstanceRedeliveryConfigurator.cs
- src/MassTransit.AutomatonymousIntegration/Configuration/IEventCorrelationConfigurator.cs
- src/MassTransit.AutomatonymousIntegration/Configuration/IMissingInstanceConfigurator.cs
- src/MassTransit.AutomatonymousIntegration/Configuration/IMissingInstanceRedeliveryConfigurator.cs
- src/MassTransit.AutomatonymousIntegration/MissingInstanceRedeliveryExtensions.cs
- src/MassTransit.AutomatonymousIntegration/Pipeline/MissingInstanceRedeliveryPipe.cs
- src/MassTransit/Context/BaseConsumeContext.cs
- src/MassTransit/Pipeline/Pipes/ResponsePipe.cs
My work before merging into develop.
> Latest Updates in Progress

- src/MassTransit/Pipeline/Pipes/ResponsePipe.cs
Set Response `TimeToLive` based on `RequestTimeout`
> - copy TTL to response from RequestTimeout

- src/MassTransit.AzureServiceBusTransport.Tests/MassTransit.AzureServiceBusTransport.Tests.csproj
- src/MassTransit.AzureServiceBusTransport/MassTransit.AzureServiceBusTransport.csproj
> Updated windowsAzure.ServiceBus to v5.2.0

- src/MassTransit.Azure.ServiceBus.Core/Contexts/NamespaceManager.cs
- src/MassTransit.Azure.ServiceBus.Core/Contexts/ServiceBusNamespaceContext.cs
This updates the Azure Service Bus rule if the rule already exists.
> Update rules azure service bus

- docs/advanced/sagas/automatonymous.md
> Fix ambiguity in SagaStateMachineInstance naming

- src/Persistence/MassTransit.EntityFrameworkCoreIntegration.Tests/ContextFactoryWithResilienceStrategy.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration.Tests/Using_ef_connection_resiliency.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Saga/EntityFrameworkSagaRepository.cs
- src/Persistence/MassTransit.EntityFrameworkIntegration/Saga/EntityFrameworkSagaRepository.cs
> Add Support for EFCore Resilience

- docs/advanced/topology/servicebus/topicsub.md
Thanks for your help around this last week @phatboyg.  Hope this helps repay some of my debt :)
> More info around Service Bus Topic Subscriptions

- src/MassTransit.RabbitMqTransport/RabbitMqAddressExtensions.cs
> Removed excessive condition

- src/MassTransit.ActiveMqTransport/MassTransit.ActiveMqTransport.csproj
> ActiveMqTransport has a strong name

- appveyor.yml
https://github.com/appveyor/ci/issues/3061
> Issue With Ubuntu Test Results Was Fixed

- src/MassTransit.ActiveMqTransport/MassTransit.ActiveMqTransport.csproj
> Fixed #1557, changed library to use NetStd fork

- src/MassTransit/Configuration/SerializerConfigurationExtensions.cs
- src/MassTransit/Serialization/BsonMessageSerializer.cs
> Ädd configurator for BsonMessageSerializer

- src/Persistence/MassTransit.RedisIntegration.Tests/SagaPersistenceTests.cs
- src/Persistence/MassTransit.RedisIntegration/DatabaseExtensions.cs
- src/Persistence/MassTransit.RedisIntegration/RedisSagaRepository.cs
- src/Persistence/MassTransit.RedisIntegration/TypedDatabase.cs
This code will make it possible to add a prefix to the keys of the redis, I believe this is very useful for those who want to keep the organization of their keys in the redis. Only SagaId makes it difficult to tell which saga that SagaId belongs to.
Please, give me some feedback about it.
> Adding Prefix to Redis Keys.

- docs/advanced/sagas/persistence.md
Adding a doc to use Redis Key Prefix.
> Adding Redis Key Prefix Doc

- docs/usage/exceptions.md
Prevents the misunderstanding from #1575
> Mention importance of call order

- docs/introduction/README.md
Correcting text on a navigation link.
> Correcting word from Html to Help.

- src/MassTransit.SignalR.Tests/HubLifeTimeManagerTests.cs
- src/MassTransit.SignalR/MassTransitHubLifetimeManager.cs
- src/MassTransit.SignalR/MassTransitMessageDataHubLifetimeManager.cs
- src/MassTransit.SignalR/Utils/ConcurrentHashSet.cs
> Fix Bug for removing Group Connection on Disconnect

- docs/advanced/scheduling/rabbitmq-delayed.md
- docs/advanced/scheduling/redeliver.md
- docs/usage/producers.md
Going through the docs, finding some dead links.
> Fix some dead links in docs

- docs/usage/sagas/persistence.md
> fix ef docs

- docs/usage/containers/autofac.md
- docs/usage/sagas/persistence.md
> Doc updates

- docs/usage/producers.md
> Fix spelling in docs

- docs/advanced/signalr/quickstart.md
> Add Missing Docs Code Line for SignalR

- docs/advanced/middleware/transactions.md
> Added missing `new` to `TransactionScope`

- docs/learn/samples.md
Add a link to a base implementation of MassTransit to consume IOT data from RabbitMQ
> Add MQTT example implementation

- docs/usage/testing.md
> fix incorrect code statements

- docs/usage/testing.md
Added a sample for testing consumer exceptions
cc: @phatboyg
> Add Fault<T> sample to guide

- docs/advanced/audit.md
> Updating Audit persistence links

- docs/advanced/monitoring/diagnostic-source.md
- Added the list of diagnostic source names
- More text about OpenTracing to manage expectations
> Adding clarify for diagnostics

- docs/troubleshooting/common-gotchas.md
Per Udi's response:
> I’m sorry but I don’t have a backup of that one.
> Removed link to podcast which no longer exists

- src/MassTransit.ActiveMqTransport.Tests/TopicEndpoint_Specs.cs
- src/MassTransit.ActiveMqTransport/ActiveMqEndpointAddress.cs
- src/MassTransit.ActiveMqTransport/Configuration/IActiveMqReceiveEndpointConfigurator.cs
- src/MassTransit.ActiveMqTransport/Topology/Configuration/Configurators/EntityConfigurator.cs
- src/MassTransit.ActiveMqTransport/Topology/Configuration/Configurators/QueueConfigurator.cs
- src/MassTransit.ActiveMqTransport/Topology/Configuration/Configurators/TopicConfigurator.cs
- src/MassTransit.ActiveMqTransport/Topology/Topologies/ActiveMqConsumeTopology.cs
- src/MassTransit.ActiveMqTransport/Transport/ActiveMqHost.cs
- src/MassTransit.AmazonSqsTransport.Tests/TopicEndpoint_Specs.cs
- src/MassTransit.AmazonSqsTransport/AmazonSqsEndpointAddress.cs
- src/MassTransit.AmazonSqsTransport/Configuration/IAmazonSqsReceiveEndpointConfigurator.cs
- src/MassTransit.AmazonSqsTransport/Topology/Configuration/Configurators/EntityConfigurator.cs
- src/MassTransit.AmazonSqsTransport/Topology/Configuration/Configurators/QueueConfigurator.cs
- src/MassTransit.AmazonSqsTransport/Topology/Configuration/Configurators/TopicConfigurator.cs
- src/MassTransit.AmazonSqsTransport/Topology/Settings/QueueReceiveSettings.cs
- src/MassTransit.AmazonSqsTransport/Transport/AmazonSqsHost.cs
- src/MassTransit.Azure.ServiceBus.Core.Tests/TopicEndpoint_Specs.cs
- src/MassTransit.Azure.ServiceBus.Core/ServiceBusEndpointAddress.cs
- src/MassTransit.Azure.ServiceBus.Core/Topology/Topologies/ServiceBusSendTopology.cs
> Completed #1582 - missing topic address providers

- docs/usage/configuration.md
there is no serviceProvider, should be "provider"
> update configuration.md - ASP.NET Core sample

- docs/advanced/monitoring/applications-insights.md
> Updating typo on App Logger setup for App Insights

- docs/advanced/monitoring/diagnostic-source.md
> Updating the links to Activity and DiagSource guides

- src/Containers/MassTransit.AutofacIntegration/Registration/AutofacContainerRegistrar.cs
- src/Containers/MassTransit.Containers.Tests/Autofac_Tests/Autofac_ScopeRequestClient.cs
- src/Containers/MassTransit.Containers.Tests/Common_Tests/Common_ScopeRequestClient.cs
- src/Containers/MassTransit.Containers.Tests/DependencyInjection_Tests/DependencyInjection_ScopeRequestClient.cs
- src/Containers/MassTransit.Containers.Tests/Lamar_Tests/Lamar_ScopeRequestClient.cs
- src/Containers/MassTransit.Containers.Tests/SimpleInjector_Tests/SimpleInjector_ScopeRequestClient.cs
- src/Containers/MassTransit.Containers.Tests/StructureMap_Tests/StructureMap_ScopeRequestClient.cs
- src/Containers/MassTransit.Containers.Tests/Windsor_Tests/Windsor_ScopeRequestClient.cs
- src/Containers/MassTransit.ExtensionsDependencyInjectionIntegration/Registration/DependencyInjectionContainerRegistrar.cs
- src/Containers/MassTransit.LamarIntegration/Registration/LamarContainerRegistrar.cs
- src/Containers/MassTransit.SimpleInjectorIntegration/Registration/SimpleInjectorContainerRegistrar.cs
- src/Containers/MassTransit.StructureMapIntegration/Registration/StructureMapContainerRegistrar.cs
- src/Containers/MassTransit.WindsorIntegration/Registration/WindsorContainerRegistrar.cs
- src/Containers/MassTransit.WindsorIntegration/Registration/WindsorContainerRegistrationConfigurator.cs
- src/MassTransit/Scoping/ScopedClientFactoryContext.cs
- src/MassTransit/Scoping/ScopedRequestSendEndpoint.cs
- src/MassTransit/Scoping/ScopedSendEndpoint.cs
Use scoped request client by default for Containers.
> Scoped RequestClient

- docs/usage/containers/autofac.md
> Remove StructureMap related code

- src/MassTransit.HangfireIntegration/Configuration/SchedulerBusObserver.cs
- src/MassTransit.HangfireIntegration/HangfireMessageHeaders.cs
- src/MassTransit.HangfireIntegration/MassTransit.HangfireIntegration.csproj
- src/MassTransit.HangfireIntegration/ScheduleJob.cs
- src/MassTransit.HangfireIntegration/SchedulerJobDataAttribute.cs
- src/MassTransit.QuartzIntegration/ScheduledMessageJob.cs
Add Job details headers for Hangfire
> Add additional headers for Hangfire

- src/Containers/MassTransit.AutofacIntegration/MassTransit.AutofacIntegration.csproj
- src/Containers/MassTransit.LamarIntegration/MassTransit.LamarIntegration.csproj
- src/Containers/MassTransit.SimpleInjectorIntegration/MassTransit.SimpleInjectorIntegration.csproj
- src/Containers/MassTransit.UnityIntegration/MassTransit.UnityIntegration.csproj
- src/MassTransit.AmazonSqsTransport/MassTransit.AmazonSqsTransport.csproj
- src/MassTransit.ApplicationInsights.Tests/MassTransit.ApplicationInsights.Tests.csproj
- src/MassTransit.Azure.ServiceBus.Core/MassTransit.Azure.ServiceBus.Core.csproj
- src/MassTransit.Host/MassTransit.Host.csproj
- src/MassTransit.RabbitMqTransport/Configuration/Configurators/ConfigurationHostSettings.cs
- src/MassTransit.RabbitMqTransport/MassTransit.RabbitMqTransport.csproj
- src/MassTransit.WebJobs.ServiceBusIntegration/MassTransit.WebJobs.ServiceBusIntegration.csproj
- src/Persistence/MassTransit.DapperIntegration/MassTransit.DapperIntegration.csproj
- src/Persistence/MassTransit.MongoDbIntegration/MassTransit.MongoDbIntegration.csproj
- src/Samples/MassTransit.Host.Quartz/MassTransit.Host.Quartz.csproj
> Package Reference Updates

- docs/advanced/signalr/hub_endpoints.md
- docs/advanced/signalr/quickstart.md
- src/MassTransit.SignalR/Configuration/HubLifetimeManagerOptions.cs
- src/MassTransit.SignalR/MassTransitSignalRConfigurationExtensions.cs
> SignalR configuration docs

- src/MassTransit.SignalR.Tests/Utils/MassTransitHubLifetimeTestFixture.cs
- src/MassTransit.SignalR/MassTransitHubLifetimeManager.cs
- src/MassTransit.SignalR/MassTransitMessageDataHubLifetimeManager.cs
- src/MassTransit.SignalR/MassTransitSignalRConfigurationExtensions.cs
tbh, I do not like this approach because we lost anything cool from DI.
~We could try to inject `IHttpContextAccessor` to get scoped service provider, but I do not think if it is good idea either~
> Use singleton for SignalR

- docs/usage/containers/msdi.md
- docs/usage/containers/multibus.md
- docs/usage/containers/simpleinjector.md
Use context instead of providers/containers
> Update DI docs

- src/Transports/MassTransit.EventHubIntegration/Configuration/Configurators/EventHubConfigurator.cs
- src/Transports/MassTransit.EventHubIntegration/Configuration/IEventHubConfigurator.cs
- src/Transports/MassTransit.EventHubIntegration/Contexts/IProcessorLockContext.cs
- src/Transports/MassTransit.EventHubIntegration/Contexts/ProcessorLockContext.cs
- src/Transports/MassTransit.EventHubIntegration/Transport/EventHubReceiveTransport.cs
- tests/MassTransit.EventHubIntegration.Tests/HealthCheck_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Publish_Specs.cs
Use batch update for checkpoints, ensure checkpoint is updated on stop,
> EventHub batch checkpoint update

- src/MassTransit/Util/SingleThreadedDictionary.cs
- src/Transports/MassTransit.EventHubIntegration/Configuration/Configurators/EventHubConfigurator.cs
- src/Transports/MassTransit.EventHubIntegration/Configuration/IEventHubConfigurator.cs
- src/Transports/MassTransit.EventHubIntegration/Contexts/IProcessorLockContext.cs
- src/Transports/MassTransit.EventHubIntegration/Contexts/ProcessorLockContext.cs
- src/Transports/MassTransit.EventHubIntegration/Transport/EventHubReceiveEndpoint.cs
- src/Transports/MassTransit.KafkaIntegration/Configuration/Configurators/KafkaFactoryConfigurator.cs
- src/Transports/MassTransit.KafkaIntegration/Configuration/Configurators/KafkaTopicConfigurator.cs
- src/Transports/MassTransit.KafkaIntegration/Configuration/IKafkaTopicConfigurator.cs
- src/Transports/MassTransit.KafkaIntegration/Contexts/ConsumerLockContext.cs
- src/Transports/MassTransit.KafkaIntegration/Transport/KafkaReceiveEndpoint.cs
- tests/MassTransit.KafkaIntegration.Tests/Publish_Specs.cs
- tests/MassTransit.KafkaIntegration.Tests/Receive_Specs.cs
Use prefetching for Kafka, EventHub.
Use custom checkpoint mechanism for Kafka
> Prefetch for streams. Use own mechanism for commits (Kafka, EventHub)

- src/Containers/MassTransit.ExtensionsDependencyInjectionIntegration/MultiBus/ServiceCollectionRiderConfigurator.cs
- src/Containers/MassTransit.ExtensionsDependencyInjectionIntegration/Registration/ServiceCollectionRiderConfigurator.cs
- src/MassTransit/Configuration/Registration/IRiderRegistrationConfigurator.cs
- src/MassTransit/Configuration/Registration/IRiderRegistrationContext.cs
- src/MassTransit/Configuration/Registration/RiderRegistrationContext.cs
- src/Transports/MassTransit.EventHubIntegration/MassTransit.EventHubIntegration.csproj
- src/Transports/MassTransit.KafkaIntegration/Configuration/Configurators/KafkaFactoryConfigurator.cs
- src/Transports/MassTransit.KafkaIntegration/Configuration/KafkaProducerRegistrationExtensions.cs
- src/Transports/MassTransit.KafkaIntegration/Configuration/Registration/KafkaRegistrationRiderFactory.cs
- src/Transports/MassTransit.KafkaIntegration/MassTransit.KafkaIntegration.csproj
Do not store Kafka registrations inside container
> Use RegistrationCache to store rider registrations

- docs/usage/sagas/cosmos.md
- src/MassTransit/Saga/LoadedSagaRepositoryQueryContext.cs
- src/Persistence/MassTransit.Azure.Cosmos/Configuration/Configuration/CosmosSagaRepositoryConfigurator.cs
- src/Persistence/MassTransit.Azure.Cosmos/Configuration/Configuration/EmulatorConstants.cs
- src/Persistence/MassTransit.Azure.Cosmos/Configuration/ICosmosSagaRepositoryConfigurator.cs
- src/Persistence/MassTransit.Azure.Cosmos/CosmosJsonDotNetSerializer.cs
- src/Persistence/MassTransit.Azure.Cosmos/JsonSerializerSettingsExtensions.cs
- src/Persistence/MassTransit.Azure.Cosmos/Saga/CollectionIdFormatters/DefaultCollectionIdFormatter.cs
- src/Persistence/MassTransit.Azure.Cosmos/Saga/CollectionIdFormatters/ICollectionIdFormatter.cs
- src/Persistence/MassTransit.Azure.Cosmos/Saga/CollectionIdFormatters/KebabCaseCollectionIdFormatter.cs
- src/Persistence/MassTransit.Azure.Cosmos/Saga/Context/CosmosDatabaseContext.cs
- src/Persistence/MassTransit.Azure.Cosmos/Saga/Context/CosmosSagaRepositoryContext.cs
- src/Persistence/MassTransit.Azure.Cosmos/Saga/Context/CosmosSagaRepositoryContextFactory.cs
- src/Persistence/MassTransit.Azure.Cosmos/Saga/Context/DatabaseContext.cs
- src/Persistence/MassTransit.Azure.Cosmos/Saga/CosmosSagaRepository.cs
- src/Persistence/MassTransit.Azure.Cosmos/Saga/QueryableExtensions.cs
- src/Persistence/MassTransit.DapperIntegration/Context/DapperSagaRepositoryContext.cs
- src/Persistence/MassTransit.DapperIntegration/Context/DapperSagaRepositoryContextFactory.cs
- src/Persistence/MassTransit.MartenIntegration/Saga/Context/MartenSagaRepositoryContext.cs
- src/Persistence/MassTransit.MartenIntegration/Saga/Context/MartenSagaRepositoryContextFactory.cs
- tests/MassTransit.Azure.Cosmos.Tests/Configuration.cs
- tests/MassTransit.Azure.Cosmos.Tests/Saga/CosmosQuerySagaRepositoryTests.cs
- tests/MassTransit.Azure.Cosmos.Tests/Saga/Data/SagaRepository.cs
- tests/MassTransit.Azure.Cosmos.Tests/UsingCosmosConcurrencyNoRetry_Specs.cs
- tests/MassTransit.Azure.Cosmos.Tests/UsingCosmosConcurrencyOptimistic_Specs.cs
- tests/MassTransit.Azure.Cosmos.Tests/UsingCosmos_Specs.cs
Hi @phatboyg, @maldworth I've cleaned up cosmos a bit. I've added CollectionIdFormatter to generate saga collection name based on saga type. Also, I've remove partionKey resolver, it could cause an issue: when you create/update/delete you are using it, and for get correlationId has been always used.
> Cosmos cleanup.

- docs/usage/testing.md
> Fix NUnit NuGet link

- src/Containers/MassTransit.AutofacIntegration/ScopeProviders/AutofacFilterContextScopeProvider.cs
- src/Containers/MassTransit.ExtensionsDependencyInjectionIntegration/ScopeProviders/DependencyInjectionFilterContextScopeProvider.cs
- src/MassTransit.TestFramework/AsyncTestFixture.cs
- src/MassTransit/JobService/Configuration/IJobServiceConfigurator.cs
- src/MassTransit/JobService/Configuration/JobServiceConfigurator.cs
- src/MassTransit/JobService/JobServiceOptions.cs
- tests/MassTransit.Azure.Table.Tests/AzureTableInMemoryTestFixture.cs
- tests/MassTransit.Azure.Table.Tests/MassTransit.Azure.Table.Tests.csproj
- tests/MassTransit.Azure.Table.Tests/SlowConcurrentSaga/DataAccess/SlowConcurrentSaga.cs
- tests/MassTransit.Azure.Table.Tests/SlowConcurrentSaga/Events/Begin.cs
- tests/MassTransit.Azure.Table.Tests/SlowConcurrentSaga/Events/IncrementCounterSlowly.cs
- tests/MassTransit.Azure.Table.Tests/SlowConcurrentSaga/SlowConcurrentSagaStateMachine.cs
- tests/MassTransit.Azure.Table.Tests/SlowConcurrentSaga/SlowConcurrentSaga_Specs.cs
- tests/MassTransit.Azure.Table.Tests/Turnout/Submitting_a_bunch_of_jobs.cs
- tests/MassTransit.Containers.Tests/Autofac_Tests/Autofac_Consumer.cs
- tests/MassTransit.Containers.Tests/Common_Tests/Common_Consumer.cs
- tests/MassTransit.Containers.Tests/DependencyInjection_Tests/DependencyInjection_Consumer.cs
> Daily Updates

- src/MassTransit/JobService/Components/StateMachines/JobStateMachine.cs
> Populate Reason when faults occur due to cancellation or exceptions

- docs/usage/correlation.md
Change CorrelateBy to CorrelatedBy
> Change CorrelateBy to CorrelatedBy

- src/Containers/MassTransit.SimpleInjectorIntegration/MassTransit.SimpleInjectorIntegration.csproj
- src/MassTransit/Configuration/RegistrationExtensions.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/PostgresLockStatementProvider.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/SqlLockStatementProvider.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/SqlServerLockStatementProvider.cs
- src/Transports/MassTransit.Azure.ServiceBus.Core/Configuration/Configurators/ServiceBusHostConfigurator.cs
- src/Transports/MassTransit.WebJobs.ServiceBusIntegration/AzureFunctionsBusConfigurationExtensions.cs
- tests/MassTransit.Azure.ServiceBus.Core.Tests/ServiceBusHostConfigurator_Specs.cs
- tests/MassTransit.EntityFrameworkCoreIntegration.Tests/TransactionalBusOutbox_Specs.cs
> merged PRs

- appveyor.yml
- docs/.vuepress/config.js
- docs/releases/v7.0.6.md
- src/Containers/MassTransit.SimpleInjectorIntegration/MassTransit.SimpleInjectorIntegration.csproj
- src/MassTransit/MassTransit.csproj
- src/Scheduling/MassTransit.HangfireIntegration/MassTransit.HangfireIntegration.csproj
- src/Transports/MassTransit.KafkaIntegration/MassTransit.KafkaIntegration.csproj
> Updated to v7.0.6, package references fixed, release notes added.

- docs/usage/sagas/azure-table.md
> Clean-up on doc redundancies on Table Storage

- src/MassTransit/Clients/ClientFactory.cs
- src/MassTransit/Clients/ClientRequestHandle.cs
- src/MassTransit/Clients/MessageResponse.cs
- src/MassTransit/Clients/RequestClient.cs
- src/MassTransit/Conductor/Client/ServiceClientFactory.cs
- src/MassTransit/IClientFactory.cs
- src/MassTransit/IRequestClient.cs
- src/MassTransit/Mediator/MassTransitMediator.cs
- src/MassTransit/MessageHeaders.cs
- src/MassTransit/Response.cs
- src/MassTransit/ResponseExtensions.cs
- tests/MassTransit.HangfireIntegration.Tests/MissingInstanceRedelivery_Specs.cs
- tests/MassTransit.QuartzIntegration.Tests/MissingInstanceRedelivery_Specs.cs
- tests/MassTransit.Tests/Batch_Specs.cs
- tests/MassTransit.Tests/MessageContext_Specs.cs
- tests/MassTransit.Tests/ResponsePatternMatching_Specs.cs
> Request Client changes

- src/MassTransit/Configuration/MessageSchedulerExtensions.cs
- src/MassTransit/MessageSchedulerBusExtensions.cs
- src/Transports/MassTransit.ActiveMqTransport/ActiveMqMessageSchedulerExtensions.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsMessageSchedulerBusExtensions.cs
- src/Transports/MassTransit.Azure.ServiceBus.Core/ServiceBusMessageSchedulerBusExtensions.cs
- src/Transports/MassTransit.RabbitMqTransport/RabbitMqMessageSchedulerExtensions.cs
Resolve `ISendEndpointProvider` or `IPublushEndpoint` for message scheduler, it will resolve scoped providers which will contains scope inside, so scheduler could be used with scoped filters
> Resolve SendEndpointProvider/PublishEndpoint for Scheduler

- src/Transports/MassTransit.KafkaIntegration/Configuration/Configurators/KafkaFactoryConfigurator.cs
- src/Transports/MassTransit.KafkaIntegration/Configuration/Configurators/KafkaTopicReceiveEndpointConfiguration.cs
- src/Transports/MassTransit.KafkaIntegration/Configuration/IKafkaHostConfiguration.cs
- src/Transports/MassTransit.KafkaIntegration/Configuration/Specifications/KafkaConsumerSpecification.cs
- src/Transports/MassTransit.KafkaIntegration/Configuration/Specifications/KafkaProducerSpecification.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaConfigurationExtensions.cs
We need to create separate config for each consumer / producer. But host configuration in clientConfig, so we need to merge them at the end
> Create Config per Consumer/Producer

- src/MassTransit.Analyzers/MessageContractAnalyzer.cs
- src/MassTransit.Analyzers/MessageContractCodeFixProvider.cs
- tests/MassTransit.Analyzers.Tests/MessageContractAnalyzerUnitTests.cs
- tests/MassTransit.Analyzers.Tests/Verifiers/CodeFixVerifier.cs
MassTransit.Analyzer Missing Properties allow recursion in message contract #2054
> analyzer missing properties recursion

- docs/advanced/topology/servicebus.md
As discussed here:
https://discordapp.com/channels/682238261753675864/682238261753675868/793840339903447061
Actual api: https://github.com/MassTransit/MassTransit/blob/15733c236d8f5b79977d8a787a3d2b23ff495b8a/src/Transports/MassTransit.Azure.ServiceBus.Core/Topology/Conventions/SessionIdConventionExtensions.cs#L41
> Fix code sample using session id formatter.

- src/MassTransit.TestFramework/BusTestFixture.cs
- src/MassTransit/Automatonymous/MassTransitStateMachine.cs
- src/MassTransit/Transports/ReceiveTransport.cs
- tests/MassTransit.ActiveMqTransport.Tests/Configure_Specs.cs
- tests/MassTransit.ActiveMqTransport.Tests/Reconnecting_Specs.cs
- tests/MassTransit.AmazonSqsTransport.Tests/Configure_Specs.cs
- tests/MassTransit.Azure.Table.Tests/Turnout/Submitting_a_bunch_of_jobs.cs
- tests/MassTransit.QuartzIntegration.Tests/Turnout/Complete_Specs.cs
- tests/MassTransit.RabbitMqTransport.Tests/ConcurrencyFilter_Specs.cs
- tests/MassTransit.RabbitMqTransport.Tests/DelayRetry_Specs.cs
- tests/MassTransit.RabbitMqTransport.Tests/HammerTime_Specs.cs
- tests/MassTransit.RabbitMqTransport.Tests/Insufficient_Specs.cs
- tests/MassTransit.RabbitMqTransport.Tests/PublishFaultObserver_Specs.cs
- tests/MassTransit.RabbitMqTransport.Tests/Publish_Specs.cs
- tests/MassTransit.RabbitMqTransport.Tests/Reconnecting_Specs.cs
- tests/MassTransit.RabbitMqTransport.Tests/SetPrefetchCount_Specs.cs
- tests/MassTransit.RabbitMqTransport.Tests/Turnout/Complete_Specs.cs
- tests/MassTransit.Tests/Serialization/JsonSerialization_Specs.cs
> Disable diagnostic logging on unit test execution

- docs/.vuepress/config.js
- docs/usage/logging.md
While pursuing the documentation I noticed that we didn't have anything on logging. Now that MT has fully baked in the new logging abstractions, I took a moment to bang out a simple page that points people in the right direction.
> Logging Docs

- docs/usage/sagas/automatonymous.md
Verified by looking in the unit tests and by Intellisense
> Fixed Request() parameter order

- docs/learn/README.md
> Remove gitter references

- src/MassTransit.TestFramework/MediatorTestFixture.cs
- src/MassTransit/ResponseExtensions.cs
- src/MassTransit/Testing/MediatorTestHarness.cs
- src/MassTransit/Util/ObjectTypeDeserializer.cs
- tests/MassTransit.Tests/ResponsePatternMatching_Specs.cs
> Fixed #2447 - header serialization issue with mediator

- docs/usage/sagas/README.md
https://arnon.me/soa-patterns/saga/
> Fixed path to Saga PDF file

- docs/usage/message-data.md
Hello!
This pr intends to update the Azure Storage repository configuration to include the latest changes included in MassTransit 7.1.8.
I think it will be useful because I could not find anything related to it in the docs but the deprecated way to do it and had to find the new correct object to create the repository myself in some pr.
I also left the old way to do it just in case.
Thanks in advance! Glad to contribute in any way.
> Update Message Data Azure Storage Documentation

- docs/learn/README.md
Put small section in about the partnership along with link to Improving website and a contact email address.
> Added section for MassTransit partnership

- docs/advanced/courier/activities.md
I'm using version 7.1.8 of the NuGet package. The types that I see are IActivity, ExecuteContext, CompensateContext, ExecutionResult, and CompensationResult. I also see Completed as non-Task-returning.
> Changed type names to match current package

- src/Containers/MassTransit.ExtensionsDependencyInjectionIntegration/MultiBus/ServiceCollectionBusConfigurator.cs
- tests/MassTransit.Containers.Tests/Common_Tests/Common_MultiBus.cs
Fixing MultiBus dependency resolution. Related to: https://github.com/MassTransit/MassTransit/issues/2549
> Fix MultiBus dependency resolution

- docs/learn/training.md
> fixing link

- README.md
- docs/usage/message-data.md
Cause it took me way too long to figure out exactly where the Azure package lived.
> Adding / Updating NuGet links

- docs/usage/riders/kafka.md
> Update doc re. multiple Kafka events on same topic

- src/Transports/MassTransit.RabbitMqTransport/Configuration/Configurators/RabbitMqHostConfigurator.cs
- tests/MassTransit.RabbitMqTransport.Tests/HostConfigurator_Specs.cs
Fix incorrect handle of vhosts
> Fixed MassTransit#2766 - Fix handle  virtualhost with escape chars

- src/Transports/MassTransit.EventHubIntegration/Transport/EventHubProducer.cs
- src/Transports/MassTransit.EventHubIntegration/Transport/EventHubProducerProvider.cs
- src/Transports/MassTransit.EventHubIntegration/Transport/EventHubSendTransportContext.cs
- src/Transports/MassTransit.KafkaIntegration/Contexts/KafkaSendTransportContext.cs
- src/Transports/MassTransit.KafkaIntegration/Contexts/ProducerContextSupervisor.cs
- src/Transports/MassTransit.KafkaIntegration/Transport/TopicProducer.cs
Add default Retry strategy for Riders
> Use HostConfiguration retry strategy for riders

- src/Containers/MassTransit.AutofacIntegration/Registration/ContainerBuilderRiderConfigurator.cs
- src/Containers/MassTransit.ExtensionsDependencyInjectionIntegration/Registration/ServiceCollectionRiderConfigurator.cs
Fix IoC resolution for Riders in case of default bus
> Fix Rider resolution for default bus

- docs/usage/sagas/automatonymous.md
This change adds a "wait" example to the `Respond` section regarding. It stores the required data to the instance to be able to callback to the original request once all (sub)requests and action in the state machine are finished.
> Add "wait" example in the `Respond` section

- docs/usage/transports/rabbitmq.md
> Update doc on default RabbitMQ batching timeout

- docs/advanced/scheduling/README.md
- docs/code/scheduling/SchedulingInternalInstance.cs
Expanding documentation on how to connect MassTransit to an internal Quartz.NET instance.
As suggested here:
https://github.com/MassTransit/MassTransit/discussions/2873
> Adding additional Quartz.NET integration docs

- docs/usage/exceptions.md
Added information about how to configure redelivery when using delayed scheduler
Please, include the information about redelivery configuration when using delayed scheduler. I spent a lot of time trying to `UseScheduledRedelivery` with delayed scheduler.
> DelayedRedelivery

- docs/usage/transports/azure-sb.md
Update code sample for 7.3 (TokenCredential rather than TokenProivider)
> Update ASB MSI Docs

- src/Scheduling/MassTransit.HangfireIntegration/HangfireHashableScheduledMessageData.cs
- src/Scheduling/MassTransit.HangfireIntegration/HangfireScheduledMessageData.cs
- src/Scheduling/MassTransit.HangfireIntegration/HashCleanupAttribute.cs
- src/Scheduling/MassTransit.HangfireIntegration/ScheduleJob.cs
- src/Scheduling/MassTransit.HangfireIntegration/ScheduleMessageConsumer.cs
- tests/MassTransit.HangfireIntegration.Tests/Cleanup_Specs.cs
- tests/MassTransit.HangfireIntegration.Tests/HangfireInMemoryTestFixture.cs
Supposed to address: https://github.com/MassTransit/MassTransit/discussions/3070
We need to cleanup hashes after job executed or manually cancelled
> Cleanup hash when job executed or cancelled #3070

- docs/code/transports/AmazonSqsConsoleListener.cs
- docs/code/transports/AmazonSqsScopedConsoleListener.cs
- docs/usage/templates.md
- docs/usage/transports/amazonsqs.md
- package-lock.json
- package.json
This PR does a bit of house cleaning by updating the npm packages
Then adds some missing dotnet template docs. 
I've also worked on the SQS docs, and added some update permissions with an example IAM Policy
> Updating Template Docs and adding some SQS doc updates

- src/Scheduling/MassTransit.HangfireIntegration/Configuration/Configuration/HangfireEndpointDefinition.cs
- src/Scheduling/MassTransit.HangfireIntegration/Configuration/Configuration/ScheduleMessageConsumerDefinition.cs
- src/Scheduling/MassTransit.HangfireIntegration/Configuration/Configuration/ScheduleRecurringMessageConsumerDefinition.cs
- src/Scheduling/MassTransit.HangfireIntegration/Configuration/HangfireEndpointOptions.cs
- src/Scheduling/MassTransit.HangfireIntegration/Configuration/HangfireIntegrationExtensions.cs
- src/Scheduling/MassTransit.HangfireIntegration/Configuration/HangfireRegistrationExtensions.cs
- src/Scheduling/MassTransit.HangfireIntegration/HangfireIntegration/HangfireBusObserver.cs
- src/Scheduling/MassTransit.HangfireIntegration/HangfireIntegration/ScheduleJob.cs
- src/Scheduling/MassTransit.HangfireIntegration/HangfireIntegration/ScheduleMessageConsumer.cs
- src/Scheduling/MassTransit.HangfireIntegration/HangfireIntegration/ScheduleRecurringMessageConsumer.cs
- src/Scheduling/MassTransit.HangfireIntegration/HangfireIntegration/SchedulerBusObserver.cs
- tests/MassTransit.HangfireIntegration.Tests/Container_Specs.cs
- tests/MassTransit.HangfireIntegration.Tests/MassTransit.HangfireIntegration.Tests.csproj
Using built-in container registration for Hangfire.
> Use Container for Hangfire registration

- docs/usage/sagas/automatonymous.md
`context.Instance` and `context.Data` are deprecated and `Saga` and `Message` respectively should be used instead.
> Update `automatonymous.md` to use non-deprecated properties

- docs/quick-starts/README.md
I missed the home page for the quick starts. This will put something that's better than 'yo yo yo'. :) 
Thank you @gertjvr
> Quick Start Index Page

- src/MassTransit/Transports/Fabric/MessageQueue.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/Middleware/AmazonSqsMessageReceiver.cs
> Last minute 8.0.6 change

- src/Transports/MassTransit.KafkaIntegration/MassTransit.KafkaIntegration.csproj
Simple update of the Confluent Kafka nuget package to fix issue described [here](https://github.com/confluentinc/confluent-kafka-dotnet/issues/1865).
I verified my change by running the provided unit tests before & after (see screenshots).
Before:
After:
> Updating Confluent Kafka client (issue with Apple Silicon)

- docs/usage/message-data.md
In the case of retries, the Stream has likely already been read on previous attempts. The consumer doesn't put a message back on the queue if it is being retried and is held in memory by the consumer for retries so you will need to 'rewind' the stream to the beginning so it is ready to be read again on subsequent attempts
MT may not dispose of the stream for you, due to this you also may need to manually dispose of the stream to avoid memory leaks
> Added Note tip on Stream rewind and disposal

- docs/troubleshooting/common-gotchas.md
> Fixed reading link.

- src/Transports/MassTransit.KafkaIntegration/KafkaConsumeContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaConsumerSpecification.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaTopicReceiveEndpointConfiguration.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/ConsumerContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaBaseReceiveContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaReceiveEndpointBuilder.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaReceiveEndpointContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/TopicKafkaReceiveEndpointContext.cs
- tests/MassTransit.KafkaIntegration.Tests/Receive_Specs.cs
Include ConsumerGroup into endpoint name.
> Add Consumer Group to EndpointName

- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/Checkpoints/BatchCheckpointer.cs
- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/Checkpoints/IPendingConfirmation.cs
- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/Checkpoints/PendingConfirmation.cs
- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/EventHubDataReceiver.cs
- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/EventHubProcessorContext.cs
- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/EventHubProducer.cs
- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/ProcessorContext.cs
- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/SharedProcessorContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Checkpoints/BatchCheckpointer.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/ConsumerContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaBaseReceiveContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaConsumerContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaMessageConsumer.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Middleware/KafkaConsumerFilter.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/SharedConsumerContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/TopicProducer.cs
- Handle Stop correctly for Kafka
- Handle Exceptions correctly for Riders
- Ignore all errors when we have at least something in the batch for Rider
> Handle exceptions/stops correctly for Riders. Ignore exceptions when at least something in the checkpoint batch

- src/MassTransit.Abstractions/Mediator/IMediator.cs
- src/MassTransit.Abstractions/Mediator/IScopedMediator.cs
- src/MassTransit/DependencyInjection/Configuration/ServiceCollectionMediatorConfigurator.cs
- src/MassTransit/DependencyInjection/DependencyInjection/ScopedMediator.cs
- src/MassTransit/Mediator/Contexts/MediatorPublishSendEndpoint.cs
- src/MassTransit/Mediator/MassTransitMediator.cs
- tests/MassTransit.Containers.Tests/Common_Tests/Common_ScopePublish.cs
- tests/MassTransit.Containers.Tests/Common_Tests/Common_ScopeRequestClient.cs
- tests/MassTransit.Containers.Tests/Common_Tests/Common_ScopeSend.cs
Adding ScopedMediator:
https://masstransit-project.com/usage/mediator.html#http-context-scope
> Scoped mediator

- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/Configuration/EventHubReceiveEndpointConfigurator.cs
- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/Configuration/EventHubReceiveEndpointSpecification.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaConsumerSpecification.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaTopicReceiveEndpointConfiguration.cs
- tests/MassTransit.EventHubIntegration.Tests/Publish_Specs.cs
Replace incorrect inherited type for Rider endpoints configuration
> Replace ReceiverConfiguration with ReceiveEndpointConfiguration 

- src/MassTransit/DependencyInjection/Configuration/ServiceCollectionMediatorConfigurator.cs
- src/MassTransit/DependencyInjection/DependencyInjection/BaseConsumeScopeProvider.cs
- src/MassTransit/DependencyInjection/DependencyInjection/CompensateActivityScopeProvider.cs
- src/MassTransit/DependencyInjection/DependencyInjection/ConsumeScopeProvider.cs
- src/MassTransit/DependencyInjection/DependencyInjection/CreatedCompensateActivityScopeContext.cs
- src/MassTransit/DependencyInjection/DependencyInjection/CreatedCompensateScopeContext.cs
- src/MassTransit/DependencyInjection/DependencyInjection/CreatedConsumeScopeContext.cs
- src/MassTransit/DependencyInjection/DependencyInjection/CreatedConsumerConsumeScopeContext.cs
- src/MassTransit/DependencyInjection/DependencyInjection/CreatedExecuteActivityScopeContext.cs
- src/MassTransit/DependencyInjection/DependencyInjection/CreatedExecuteScopeContext.cs
- src/MassTransit/DependencyInjection/DependencyInjection/DependencyInjectionSagaRepositoryContextFactory.cs
- src/MassTransit/DependencyInjection/DependencyInjection/ExecuteActivityScopeProvider.cs
- src/MassTransit/DependencyInjection/DependencyInjection/ExistingCompensateActivityScopeContext.cs
- src/MassTransit/DependencyInjection/DependencyInjection/ExistingCompensateScopeContext.cs
- src/MassTransit/DependencyInjection/DependencyInjection/ExistingConsumeScopeContext.cs
- src/MassTransit/DependencyInjection/DependencyInjection/ExistingConsumerConsumeScopeContext.cs
- src/MassTransit/DependencyInjection/DependencyInjection/ExistingExecuteActivityScopeContext.cs
- src/MassTransit/DependencyInjection/DependencyInjection/ExistingExecuteScopeContext.cs
- src/MassTransit/DependencyInjection/DependencyInjection/InternalScopeExtensions.cs
- src/MassTransit/DependencyInjection/DependencyInjection/ScopedConsumeContextProvider.cs
- src/MassTransit/Mediator/Contexts/MediatorReceiveContext.cs
- src/MassTransit/Mediator/Contexts/MediatorSendEndpoint.cs
- src/MassTransit/Middleware/InMemoryOutboxFilter.cs
- tests/MassTransit.Containers.Tests/Common_Tests/Common_ScopedMediator.cs
Use Payloads from SendContext in Mediator ReceiveContext
> Get Payload from SendContext in mediator

- src/MassTransit.Abstractions/Internals/Extensions/TaskExtensions.cs
Add few small tweaks to `Task.OrCancelled` to avoid unnecessary resources allocation
> Tweak OrCancelled

- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaFactoryConfigurator.cs
- tests/MassTransit.KafkaIntegration.Tests/Producer_Specs.cs
https://github.com/MassTransit/MassTransit/issues/4054
> Fix a silly #4054

- doc/content/3.documentation/1.concepts/mediator.md
Replacing old doc with new IScopedMediator interface :)
> Replace HttpContext filter with ScopedMediator

- src/MassTransit.Abstractions/MediatorRequestExtensions.cs
This is a simple extension of the SendRequest method
> Add supporting 'CancellationToken' parameter for SendRequest method

- src/MassTransit.Analyzers/AnalyzerReleases.Shipped.md
- src/MassTransit.Analyzers/CancellationTokenOverloadMethodAnalyzer.cs
- src/MassTransit.Analyzers/Helpers/OperationExtensions.cs
- tests/MassTransit.Analyzers.Tests/CancellationToken_Specs.cs
- tests/MassTransit.Analyzers.Tests/MassTransit.Analyzers.Tests.csproj
Suggest using MT CancellationToken
> Suggest Using PipeContext.CancellationToken

- doc/content/3.documentation/5.configuration/integrations/roslyn-analyzer.md
> Update analyzer doc

- doc/content/2.quick-starts/2.rabbitmq.md
- doc/content/2.quick-starts/3.azure-service-bus.md
- doc/content/2.quick-starts/4.amazon-sqs.md
- doc/content/3.documentation/2.transports/2.rabbitmq.md
- doc/content/3.documentation/2.transports/3.azure-service-bus.md
- doc/content/3.documentation/2.transports/4.amazon-sqs.md
- doc/content/3.documentation/2.transports/5.activemq.md
- doc/content/3.documentation/2.transports/kafka.md
- doc/content/3.documentation/5.configuration/1.transports/10.kafka.md
- doc/content/3.documentation/5.configuration/1.transports/11.azure-event-hub.md
- doc/content/3.documentation/5.configuration/1.transports/2.rabbitmq.md
- doc/content/3.documentation/5.configuration/1.transports/21.azure-functions.md
- doc/content/3.documentation/5.configuration/1.transports/3.azure-service-bus.md
- doc/content/3.documentation/5.configuration/1.transports/4.amazon-sqs.md
- doc/content/3.documentation/5.configuration/1.transports/5.activemq.md
- doc/content/3.documentation/5.configuration/2.persistence/azure-service-bus.md
- doc/yarn.lock
> Updated Docus and related packages

- doc/app.config.ts
- doc/components/global/IconMassTransit.vue
- doc/server/middleware/redirects.ts
> Added Icon, updated more redirects

- src/MassTransit/Middleware/Outbox/BusOutboxNotification.cs
- src/MassTransit/Middleware/Outbox/IBusOutboxNotification.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Configuration/Configuration/EntityFrameworkBusOutboxConfigurator.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/BusOutboxDeliveryService.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/EntityFrameworkScopedBusContext.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/EntityFrameworkScopedBusContextProvider.cs
- src/Persistence/MassTransit.MongoDbIntegration/Configuration/Configuration/MongoDbBusOutboxConfigurator.cs
- src/Persistence/MassTransit.MongoDbIntegration/MongoDbIntegration/BusOutboxDeliveryService.cs
- src/Persistence/MassTransit.MongoDbIntegration/MongoDbIntegration/MongoDbScopedBusContext.cs
- src/Persistence/MassTransit.MongoDbIntegration/MongoDbIntegration/MongoDbScopedBusContextProvider.cs
- tests/MassTransit.EntityFrameworkCoreIntegration.Tests/ReliableMessaging/BusOutbox_Specs.cs
- tests/MassTransit.EntityFrameworkCoreIntegration.Tests/TransactionalBusOutbox_Specs.cs
- tests/MassTransit.EntityFrameworkCoreIntegration.Tests/docker-compose.yml
- tests/MassTransit.MongoDbIntegration.Tests/BusOutbox_Specs.cs
- tests/MassTransit.MongoDbIntegration.Tests/dbstart.sh
- tests/MassTransit.MongoDbIntegration.Tests/docker-compose.yml
- tests/MassTransit.MongoDbIntegration.Tests/scripts/rs-init.sh
Notify delivery service when Outbox completed to react on such immediately
> Notify delivery service when Outbox completed

- Directory.Packages.props
- src/MassTransit.SignalR/MassTransitHubLifetimeManager.cs
- src/MassTransit.SignalR/Scoping/DependencyInjectionHubLifetimeScopeProvider.cs
- src/MassTransit.SignalR/Scoping/IHubLifetimeScope.cs
- src/MassTransit/Configuration/DependencyInjection/DependencyInjectionTestingExtensions.cs
- src/MassTransit/DependencyInjection/DependencyInjection/BaseConsumeScopeProvider.cs
- src/MassTransit/DependencyInjection/DependencyInjection/DependencyInjectionSagaRepositoryContextFactory.cs
- src/MassTransit/DependencyInjection/DependencyInjection/FilterScopeProvider.cs
- src/MassTransit/DependencyInjection/DependencyInjection/Testing/ContainerTestHarness.cs
- src/MassTransit/Logging/NullLogger.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/BusOutboxDeliveryService.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/InboxCleanupService.cs
- src/Persistence/MassTransit.MongoDbIntegration/MongoDbIntegration/BusOutboxDeliveryService.cs
- src/Persistence/MassTransit.MongoDbIntegration/MongoDbIntegration/InboxCleanupService.cs
- tests/MassTransit.SignalR.Tests/Utils/BusHubLifetimeScopeProvider.cs
Bump depencies version to 6.x and use AsyncScope
> Bump Dependencies to 6.x

- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/EntityFrameworkScopedBusContext.cs
- src/Persistence/MassTransit.MongoDbIntegration/MongoDbIntegration/MongoDbContext.cs
- src/Persistence/MassTransit.MongoDbIntegration/MongoDbIntegration/MongoDbScopedBusContext.cs
- src/Persistence/MassTransit.MongoDbIntegration/MongoDbIntegration/NoMongoDbSessionContext.cs
- src/Persistence/MassTransit.MongoDbIntegration/MongoDbIntegration/TransactionMongoDbContext.cs
- tests/MassTransit.EntityFrameworkCoreIntegration.Tests/ReliableMessaging/BusOutbox_Specs.cs
- tests/MassTransit.MongoDbIntegration.Tests/BusOutbox_Specs.cs
> Check if context was committed

- src/MassTransit/Util/PartitionChannelExecutorPool.cs
- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/EventHubDataReceiver.cs
- tests/MassTransit.Benchmark/KafkaOptionSet.cs
- tests/MassTransit.Benchmark/Latency/KafkaMessageLatencyTransport.cs
- tests/MassTransit.Benchmark/docker-compose.yml
- Add Redpanda to Benchmark
- Improve concurrency for Kafka Benchmark
- Simplify Riders key concurrency.
> Simplify concurrency for riders. Improve benchmark

- src/Transports/MassTransit.KafkaIntegration/Configuration/IKafkaProducerConfigurator.cs
- src/Transports/MassTransit.KafkaIntegration/Configuration/IKafkaTopicReceiveEndpointConfigurator.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaProducerSpecification.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaTopicReceiveEndpointConfiguration.cs
> Add ability to set statistics handler

- src/MassTransit/DependencyInjection/DependencyInjection/GenericRequestClient.cs
https://github.com/MassTransit/MassTransit/blob/6ec989a6aec2e2abbe891379aed44e30ea68697c/src/MassTransit/DependencyInjection/DependencyInjection/ScopedMediator.cs#L27
> Fix GenericClient usage for ScopedMediator

- tests/MassTransit.Containers.Tests/Stop_Specs.cs
> Add Test for Redelivery and ConsumerStopTimeout

- src/MassTransit/Transports/ConsumerAgent.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/AmazonSqsClientContext.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/AmazonSqsReceiveLockContext.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/Batcher.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/ClientContext.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/ClientContextCacheDefaults.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/PublishBatchSettings.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/PublishBatcher.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/QueueCache.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/QueueInfo.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/ScopeClientContext.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/SharedClientContext.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/TopicCache.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/TopicInfo.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/TopicSendTransportContext.cs
- tests/MassTransit.AmazonSqsTransport.Tests/StartStop_Specs.cs
…s (not using the Batcher, so wrong exception type)
> Convert SNS publisher to use batching

- src/MassTransit/Transports/ConsumerAgent.cs
> Tests are failing on .NET Framework 4.6.2 #4169

- src/MassTransit.Abstractions/Internals/Extensions/TaskExtensions.cs
- src/MassTransit/Middleware/Outbox/BusOutboxNotification.cs
> Few task delay tweaks

- src/MassTransit.Abstractions/Configuration/IMessageFilterConfigurator.cs
- src/MassTransit.Abstractions/Configuration/IMessageTypeFilterConfigurator.cs
- src/MassTransit/Configuration/Configuration/ConsumeMessageFilterConfigurator.cs
- src/MassTransit/Configuration/Configuration/MessageTypeFilterConfigurator.cs
- src/MassTransit/Configuration/Configuration/SendMessageFilterConfigurator.cs
- src/MassTransit/Configuration/DependencyInjection/DependencyInjectionFilterExtensions.cs
- src/MassTransit/DependencyInjection/Configuration/ScopedCompensateActivityPipeSpecificationObserver.cs
- src/MassTransit/DependencyInjection/Configuration/ScopedConsumePipeSpecificationObserver.cs
- src/MassTransit/DependencyInjection/Configuration/ScopedExecuteActivityPipeSpecificationObserver.cs
- src/MassTransit/DependencyInjection/Configuration/ScopedFilterSpecificationObserver.cs
> Add Scoped filter message type filters

- src/MassTransit/Middleware/Outbox/InMemoryOutboxMessageRepository.cs
> Clean up InMemoryOutboxMessageRepository to use extension method.

- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/AmazonSqsReceiveLockContext.cs
https://github.com/MassTransit/MassTransit/discussions/4177
> Do not use CancellationToken for RenewMessageVisibility in SQS

- src/MassTransit/Initializers/PropertyConverters/ListPropertyConverter.cs
> Add support to MessageData on nested ICollection

- doc/content/3.documentation/5.configuration/observability.md
- src/MassTransit/Logging/Diagnostics/DiagnosticHeaders.cs
- src/MassTransit/Logging/Diagnostics/LogContextActivityExtensions.cs
- src/MassTransit/Logging/Monitoring/LogContextInstrumentationExtensions.cs
> OTel tweaks and docs

- src/MassTransit/Configuration/DependencyInjection/DependencyInjectionRegistrationExtensions.cs
> Add Instrumentation Options explicitly

- Directory.Packages.props
> upgrade packages

- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Serializers/DictionaryHeadersSerialize.cs
- tests/MassTransit.KafkaIntegration.Tests/DictionaryHeadersDeserializerTests.cs
> Fix kafka headers

- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaProducerSpecification.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaTopicReceiveEndpointConfiguration.cs
> Regenerate configs upon consumer/producer creation

- doc/content/3.documentation/1.concepts/1.messages.md
> Fix typo in message documentation

- src/MassTransit/Configuration/RetryConfigurationExtensions.cs
> Fixed docstring of None in RetryConfigurationExtensions

- src/MassTransit/InMemoryTransport/InMemoryTransport/InMemoryReceiveTransport.cs
- src/MassTransit/Transports/BaseReceiveContext.cs
- src/MassTransit/Transports/ConsumerAgent.cs
- src/Transports/MassTransit.ActiveMqTransport/ActiveMqTransport/Middleware/ActiveMqConsumer.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/AmazonSqsReceiveLockContext.cs
- src/Transports/MassTransit.AmazonSqsTransport/AmazonSqsTransport/Middleware/AmazonSqsMessageReceiver.cs
- src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/Receiver.cs
- src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/ServiceBusReceiveLockContext.cs
- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/EventHubDataReceiver.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaMessageConsumer.cs
- src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/RabbitMqBasicConsumer.cs
> Create LockContext beforehand always

- src/MassTransit/Configuration/Configuration/InMemoryOutbox/OutboxConsumePipeSpecificationObserver.cs
- src/MassTransit/Configuration/InMemoryOutboxConfigurationExtensions.cs
- src/MassTransit/Configuration/JobServiceConfigurationExtensions.cs
- src/MassTransit/Configuration/RegistrationContextExtensions.cs
- src/MassTransit/DependencyInjection/DependencyInjection/Registration/Futures/DefaultFutureDefinition.cs
- src/MassTransit/DependencyInjection/DependencyInjection/Registration/Futures/RequestConsumerFutureDefinition.cs
- src/MassTransit/JobService/Configuration/JobServiceConfigurator.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Configuration/EntityFrameworkOutboxConfigurationExtensions.cs
- src/Persistence/MassTransit.MongoDbIntegration/Configuration/MongoDbOutboxConfigurationExtensions.cs
- src/Scheduling/MassTransit.HangfireIntegration/Configuration/Configuration/PauseScheduledRecurringMessageConsumerDefinition.cs
- src/Scheduling/MassTransit.HangfireIntegration/Configuration/Configuration/ResumeScheduledMessageConsumerDefinition.cs
- src/Scheduling/MassTransit.HangfireIntegration/Configuration/Configuration/ScheduleMessageConsumerDefinition.cs
- src/Scheduling/MassTransit.HangfireIntegration/Configuration/Configuration/ScheduleRecurringMessageConsumerDefinition.cs
- src/Scheduling/MassTransit.QuartzIntegration/Configuration/Configuration/CancelScheduledMessageConsumerDefinition.cs
- src/Scheduling/MassTransit.QuartzIntegration/Configuration/Configuration/PauseScheduledMessageConsumerDefinition.cs
- src/Scheduling/MassTransit.QuartzIntegration/Configuration/Configuration/ResumeScheduledMessageConsumerDefinition.cs
- src/Scheduling/MassTransit.QuartzIntegration/Configuration/Configuration/ScheduleMessageConsumerDefinition.cs
> Additional backward changes

- src/MassTransit/Consumers/Configuration/ConsumerConnector.cs
- src/MassTransit/Consumers/Configuration/InstanceConnector.cs
- src/MassTransit/SagaStateMachine/Configuration/StateMachineConnector.cs
- src/MassTransit/SagaStateMachine/Configuration/StateMachineSagaConfigurator.cs
- src/MassTransit/Sagas/Configuration/SagaConnector.cs
- src/MassTransit/Testing/MultiTestConsumer.cs
> Predefine list size for connectors

- src/Transports/MassTransit.KafkaIntegration/Configuration/IKafkaTopicReceiveEndpointConfigurator.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaProducerSpecification.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaTopicReceiveEndpointConfiguration.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/ConsumerLockContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaConsumerBuilderContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/ReceiveSettings.cs
- tests/MassTransit.KafkaIntegration.Tests/TopicConnector_Specs.cs
> Add ability to rewind stream to custom offset

- doc/content/4.support/4.upgrade.md
- src/MassTransit/Configuration/DependencyInjection/DependencyInjectionExtensions.cs
- src/MassTransit/Configuration/DependencyInjection/DependencyInjectionReceiveEndpointExtensions.cs
- src/MassTransit/Configuration/InMemoryOutboxConfigurationExtensions.cs
- src/MassTransit/Configuration/JobServiceConfigurationExtensions.cs
- src/MassTransit/Configuration/JobServiceContainerConfigurationExtensions.cs
- src/MassTransit/Testing/ExtensionMethodsForSagas.cs
- src/MassTransit/Testing/Implementations/BaseSagaTestHarness.cs
- src/MassTransit/Testing/Implementations/RegistrationSagaStateMachineTestHarness.cs
- src/MassTransit/Testing/Implementations/RegistrationSagaTestHarness.cs
- src/MassTransit/Testing/Implementations/StateMachineSagaTestHarness.cs
- src/MassTransit/Testing/SagaTestHarness.cs
- src/MassTransit/Testing/SagaTestHarnessExtensions.cs
- src/MassTransit/Testing/StateMachineSagaTestingExtensions.cs
- src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Configuration/EntityFrameworkOutboxConfigurationExtensions.cs
- src/Persistence/MassTransit.MongoDbIntegration/Configuration/MongoDbOutboxConfigurationExtensions.cs
- tests/MassTransit.HangfireIntegration.Tests/Reschedule_Specs.cs
- tests/MassTransit.QuartzIntegration.Tests/Reschedule_Specs.cs
- tests/MassTransit.Tests/SagaStateMachineTests/CatchFault_Specs.cs
- tests/MassTransit.Tests/SagaStateMachineTests/Finalize_Specs.cs
- Update guidance for v8.1
- Mark methods with obsolete
- Refactor TestHarness to use correct Query/Load repository implementation
> Upgrade guidance for Scoped ConsumeContext

- doc/yarn.lock
> Updated packages for documentation

- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/EventHubProducerSendTransportContext.cs
https://github.com/MassTransit/MassTransit/issues/4503
> Fix batch for EventHub  #4503

- src/MassTransit/Configuration/DependencyInjection/IBusRegistrationConfigurator.cs
- src/MassTransit/Configuration/DependencyInjection/IRegistrationConfigurator.cs
- src/MassTransit/DependencyInjection/Configuration/BusRegistrationContext.cs
- src/MassTransit/DependencyInjection/Configuration/ConfigureReceiveEndpointDelegateProvider.cs
- src/MassTransit/DependencyInjection/Configuration/DependencyInjectionContainerRegistrar.cs
- src/MassTransit/DependencyInjection/Configuration/DependencyInjectionRiderContainerRegistrar.cs
- src/MassTransit/DependencyInjection/Configuration/IContainerSelector.cs
- src/MassTransit/DependencyInjection/Configuration/RegistrationConfigurator.cs
- src/MassTransit/DependencyInjection/Configuration/ServiceCollectionBusConfigurator.cs
- src/MassTransit/DependencyInjection/Configuration/ServiceCollectionMediatorConfigurator.cs
- src/MassTransit/DependencyInjection/Configuration/ServiceCollectionRiderConfigurator.cs
- tests/MassTransit.Containers.Tests/Common_Tests/MultiBus_Specs.cs
> Separate endpoint configurator per bus-type

- doc/content/3.documentation/5.configuration/2.transports/10.kafka.md
- src/Transports/MassTransit.KafkaIntegration/Configuration/IKafkaHostConfiguration.cs
- src/Transports/MassTransit.KafkaIntegration/Configuration/KafkaIntegrationExtensions.cs
- src/Transports/MassTransit.KafkaIntegration/Configuration/KafkaProducerRegistrationExtensions.cs
- src/Transports/MassTransit.KafkaIntegration/IKafkaRider.cs
- src/Transports/MassTransit.KafkaIntegration/ITopicProducerProvider.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaFactoryConfigurator.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaBaseReceiveContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaRider.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/TopicProducerProviderExtensions.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaTopicProducerProviderExtensions.cs
- tests/MassTransit.KafkaIntegration.Tests/Producer_Specs.cs
Add ability to resolve producer by using topic address
> TopicProducer provider for kafka

- doc/content/3.documentation/3.patterns/13.job-consumers.md
Hoping i've understood correctly ! :)
> Update job consumer docs

- doc/content/4.support/4.upgrade.md
> Add Job Service State Machine notice to upgrade

- src/MassTransit/Configuration/DependencyInjection/IRegistrationConfigurator.cs
- src/MassTransit/Configuration/DependencyInjection/RegistrationConfiguratorExtensions.cs
- src/MassTransit/DependencyInjection/Configuration/IActivityRegistration.cs
- src/MassTransit/DependencyInjection/Configuration/IConsumerRegistration.cs
- src/MassTransit/DependencyInjection/Configuration/IExecuteActivityRegistration.cs
- src/MassTransit/DependencyInjection/Configuration/ISagaRegistration.cs
- src/MassTransit/DependencyInjection/Configuration/RegistrationConfigurator.cs
- src/MassTransit/DependencyInjection/Configuration/RegistrationContext.cs
- src/MassTransit/DependencyInjection/Configuration/TestHarnessRegistrationConfigurator.cs
- src/MassTransit/DependencyInjection/DependencyInjection/Registration/Activites/ActivityRegistration.cs
- src/MassTransit/DependencyInjection/DependencyInjection/Registration/Activites/ExecuteActivityRegistration.cs
- src/MassTransit/DependencyInjection/DependencyInjection/Registration/Consumers/ConsumerRegistration.cs
- src/MassTransit/DependencyInjection/DependencyInjection/Registration/Sagas/SagaRegistration.cs
- src/MassTransit/DependencyInjection/DependencyInjection/Registration/Sagas/SagaStateMachineRegistration.cs
> Add More overloads with RegistrationContext

- doc/content/3.documentation/3.patterns/13.job-consumers.md
Based on commentary in Discord I wanted to add a note about when to use Job Consumers
> Add a Job Consumer Note

- doc/content/3.documentation/2.configuration/1.consumers.md
- src/MassTransit.Abstractions/Middleware/Middleware/CopyContextPipe.cs
- src/MassTransit/Configuration/JobOptions.cs
- src/MassTransit/JobService/JobService/JobService.cs
- src/MassTransit/MassTransitBus.cs
- tests/MassTransit.Containers.Tests/RedeliveryHeader_Specs.cs
> Fix 4676 - Redelivery Count

- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaMessageConsumer.cs
Mark kafka consumer ready only when partitions got assigned:
https://github.com/MassTransit/MassTransit/issues/4699
> Make Kafka ready only when Partitions got assigned

- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Middleware/KafkaConsumerFilter.cs
Wait before separate consumer Agent is ready and then Notify observers
fix 2 for: https://github.com/MassTransit/MassTransit/issues/4699
> Wait for Consumer Ready status before notifying

- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaMessageConsumer.cs
https://github.com/confluentinc/confluent-kafka-dotnet?tab=readme-ov-file#error-handling
> Restart kafka consumer on fatal error

- src/Transports/MassTransit.ActiveMqTransport/ActiveMqTransport/Middleware/ActiveMqConsumerFilter.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaMessageConsumer.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Middleware/KafkaConsumerFilter.cs
Another fix for kafka readiness
https://github.com/MassTransit/MassTransit/issues/4699
> Set Kafka not-ready if error received

- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/EventHubDataReceiver.cs
- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/PartitionCheckpointData.cs
- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/ProcessorLockContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Checkpoints/PendingConfirmationCollection.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/ConsumerLockContext.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaMessageConsumer.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/PartitionCheckpointData.cs
- tests/MassTransit.KafkaIntegration.Tests/Receive_Specs.cs
Making kafka to consume in order
https://github.com/MassTransit/MassTransit/issues/4777
> Consume messages in order kafka

- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaMessageConsumer.cs
- tests/MassTransit.KafkaIntegration.Tests/MultiBus_Specs.cs
Put `Subscribe` call in try catch, just in case
> Fix multibus Kafka test

- src/MassTransit/Configuration/DefaultEndpointNameFormatter.cs
- tests/MassTransit.Tests/EndpointName_Specs.cs
fixes https://github.com/MassTransit/MassTransit/issues/4795
If you have issues with the exception type or the message, please feel free to let me know. I wrote tests that verify the behavior.
> 4795 empty names

- doc/content/3.documentation/6.transports/2.rabbitmq.md
- docs/advanced/topology/rabbitmq.md
- Fixed the word "exchanges" in one sentence
- Created a table of RabbitMQ Exchange types
- Added comments, for consistency, to csharp comments
> Docs editorial

- src/MassTransit.Abstractions/Mediator/MediatorRequestHandler.cs
> Fixed mangled markup in MediatorRequestHandler's API doc.

- README.md
This PR only changes all net6 references to net8 in the README file
> updating net6 references to net8 in README

- src/Transports/MassTransit.EventHubIntegration/EventHubIntegration/Configuration/EventHubProducerSpecification.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaFactoryConfigurator.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Configuration/KafkaProducerSpecification.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/KafkaTopicSendTransportContext.cs
- tests/MassTransit.KafkaIntegration.Tests/Filter_Specs.cs
https://github.com/MassTransit/MassTransit/issues/4977
> Allow multiple configurations for send pipe in Riders

- doc/content/3.documentation/3.patterns/6.saga/guidance.md
Fixed state machine configuration typo in documentation
> Update guidance.md for typo

- doc/content/2.quick-starts/0.index.md
- doc/content/2.quick-starts/2.rabbitmq.md
- doc/content/2.quick-starts/5.postgresql.md
> Add SQL Quick Start

- .github/workflows/build.yml
- tests/MassTransit.Azure.Table.Tests/Configuration.cs
- tests/MassTransit.Azure.Table.Tests/docker-compose.yml
- tests/MassTransit.EventHubIntegration.Tests/BatchProducer_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/BatchReceive_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Configuration.cs
- tests/MassTransit.EventHubIntegration.Tests/EndpointConnector_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Faults_Receive_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Filter_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/HealthCheck_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Long_Receive_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/MultiBus_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Outbox_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/ProducerPipe_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Producer_Saga_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Producer_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Publish_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Receive_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Recycle_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/config.json
- tests/MassTransit.EventHubIntegration.Tests/docker-compose.yml
- tests/MassTransit.MongoDbIntegration.Tests/BusOutbox_Specs.cs
- Use EventHub emulator
- Migrated some projects to use our own docker-compose
> Migrate to EventHub emulator

- .github/workflows/build.yml
- tests/MassTransit.Azure.Cosmos.Tests/docker-compose.yml
> Add CosmosDB emulator

- src/MassTransit.Abstractions/Middleware/Middleware/Agent.cs
- src/MassTransit.Abstractions/Middleware/Middleware/Supervisor.cs
- src/Transports/MassTransit.ActiveMqTransport/ActiveMqTransport/Middleware/ActiveMqConsumerFilter.cs
- src/Transports/MassTransit.KafkaIntegration/KafkaIntegration/Middleware/KafkaConsumerFilter.cs
- tests/MassTransit.EventHubIntegration.Tests/BatchProducer_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/BatchReceive_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Configuration.cs
- tests/MassTransit.EventHubIntegration.Tests/EndpointConnector_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Faults_Receive_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Filter_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/HealthCheck_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Long_Receive_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/MultiBus_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Outbox_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/ProducerPipe_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Producer_Saga_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Producer_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Publish_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Receive_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/Recycle_Specs.cs
- tests/MassTransit.EventHubIntegration.Tests/config.json
- tests/MassTransit.KafkaIntegration.Tests/docker-compose.yml
- Do not stop Agent when already stopping
- Do not Add consumer to agent when already stopping
> Do not add consumer when Supervisor is Stopping #5260

- doc/vercel.json
> Updating documentation a bit

- src/MassTransit/Logging/MetricsContext.cs
- src/MassTransit/Logging/MetricsContextExtensions.cs
- src/MassTransit/Logging/Monitoring/LogContextInstrumentationExtensions.cs
- src/MassTransit/Middleware/OutboxMessagePipe.cs
Inspired by: https://github.com/MassTransit/MassTransit/pull/5373
> Add Ability to enrich metric tags

- src/MassTransit/Logging/MetricsContext.cs
- src/MassTransit/Logging/MetricsContextExtensions.cs
- src/MassTransit/Logging/Monitoring/LogContextInstrumentationExtensions.cs
Fix struct population with tags:
https://github.com/MassTransit/MassTransit/pull/5389#issuecomment-2278907781
> Fix struct population

- Directory.Packages.props
- tests/MassTransit.ActiveMqTransport.Tests/MassTransit.ActiveMqTransport.Tests.csproj
- tests/MassTransit.ActiveMqTransport.Tests/OpenTelemetry_Specs.cs
- tests/MassTransit.AmazonSqsTransport.Tests/MassTransit.AmazonSqsTransport.Tests.csproj
- tests/MassTransit.AmazonSqsTransport.Tests/OpenTelemetry_Specs.cs
- tests/MassTransit.RabbitMqTransport.Tests/MassTransit.RabbitMqTransport.Tests.csproj
- tests/MassTransit.RabbitMqTransport.Tests/OpenTelemetry_Specs.cs
- tests/MassTransit.Tests/ContainerTests/Metrics_Specs.cs
- tests/MassTransit.Tests/MassTransit.Tests.csproj
- Add Test for metrics
- Refactor OTEL tests to use OTEL Hosting extensions
> Add MetricCollector tests

- doc/package-lock.json
> Updating stuff.

- doc/content/2.quick-starts/2.rabbitmq.md
- doc/content/2.quick-starts/3.azure-service-bus.md
- doc/content/2.quick-starts/4.amazon-sqs.md
- doc/content/2.quick-starts/5.postgresql.md
Added links to guidance the reader likely is interested in
> Added what is next section to transport quickstarts

- doc/content/3.documentation/1.concepts/4.exceptions.md
> Link to guidance on how to use native tools to retry messages

- doc/content/3.documentation/2.configuration/2.transports/2.rabbitmq.md
Minor typo from 77682d61e2707d1d415
> Minor typo

- src/Transports/MassTransit.SqlTransport.PostgreSql/SqlTransport/PostgreSql/PostgresDatabaseMigrator.cs
Enahnce `PostgresDatabaseMigrator` to check if an index exists before trying to create it, which in some cases causes deadlock.
P.S. As a follow up of the [Postgres transport migration causes deadlocks](https://github.com/MassTransit/MassTransit/discussions/5772) discussion.
> Enahnce PostgresDatabaseMigrator to avoid deadlocks

- src/Transports/MassTransit.SqlTransport.SqlServer/SqlTransport/SqlServer/SqlServerDatabaseMigrator.cs
seeing some errors and not knowing what they're from, so added some error details like the postgres side has.
> specifics in error messages like postgres side has

- doc/content/3.documentation/1.concepts/4.exceptions.md
- doc/content/4.support/3.samples.md
Like the Particular Error Mangement
> Changes about eror manangement

- doc/content/3.documentation/2.configuration/2.transports/10.kafka.md
- doc/content/3.documentation/2.configuration/2.transports/11.azure-event-hub.md
> typo (changed withing => within)

- src/MassTransit/ForwardExtensions.cs
> Use context.CancellationToken in Forward

- doc/content/3.documentation/2.configuration/0.index.md
Minor documentation fix I came across
> Fix reference to Azure Service Bus documentation
